### ISSUE TITLE
Refine `RedisSerializer` implementations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1097]
**[Markus Heiden](https://jira.spring.io/secure/ViewProfile.jspa?name=markus_heiden)** opened **[DATAREDIS-521](https://jira.spring.io/browse/DATAREDIS-521?redirect=false)** and commented

Jackson2JsonRedisSerializer#serialize(Object) should be Jackson2JsonRedisSerializer#serialize(T). Jackson2JsonRedisSerializer implements RedisSerializer\<T> which defines the method as serialize(T). I do not understand why this compiles at all.

The current state makes it impossible to overwrite the method

---

**Affects:** 1.7.1 (Hopper SR1)

**Comment by mp911de** [comment]
`Jackson2JsonRedisSerializer.serialize(T)` compiles to `serialize(Object)`. We took this opportunity to polish up our code a bit.
