### ISSUE TITLE
Set ObjectMapper in the constructor of Jackson2JsonRedisSerializer [DATAREDIS-644]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1223]
**[Toshiaki Maki](https://jira.spring.io/secure/ViewProfile.jspa?name=making)** opened **[DATAREDIS-644](https://jira.spring.io/browse/DATAREDIS-644?redirect=false)** and commented

It would be better to have a constructor to set `ObjectMapper` in `Jackson2JsonRedisSerializer`.

At this moment, `ObjectMapper` can be configured only by the setter.
https://github.com/spring-projects/spring-data-redis/blob/00c433c74fe63376adb6a26b50b8ff3605aad238/src/main/java/org/springframework/data/redis/serializer/Jackson2JsonRedisSerializer.java

---
No further details from [DATAREDIS-644](https://jira.spring.io/browse/DATAREDIS-644?redirect=false)

**Comment by mp911de** [comment]
Fixed via #2332
