### ISSUE TITLE
the_docs_has_error [DATAREDIS-654]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1232]
**[张鑫](https://jira.spring.io/secure/ViewProfile.jspa?name=fluffy)** opened **[DATAREDIS-654](https://jira.spring.io/browse/DATAREDIS-654?redirect=false)** and commented

title : Example 10. Sample Map<String,byte[]> Converters

[^IZ%%AXDR)V4820DTY0X(WUX.png]

---

**Affects:** 1.8.4 (Ingalls SR4)

**Reference URL:** http://docs.spring.io/spring-data/redis/docs/1.8.4.RELEASE/reference/html/

**Attachments:**
- [IZ%%AXDR)V4820DTY0X(WUX.png](https://jira.spring.io/secure/attachment/25007/IZ%25%25AXDR%29V4820DTY0X%28WUX.png) (_48.48 kB_)

**Comment by mp911de** [comment]
Fixed via #575
