### ISSUE TITLE
RedisTemplate can't connect to Redis server using Jedis [DATAREDIS-742]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1324]
**[Ramkumar Krishnan](https://jira.spring.io/secure/ViewProfile.jspa?name=ramkumar.k)** opened **[DATAREDIS-742](https://jira.spring.io/browse/DATAREDIS-742?redirect=false)** and commented

Please take a look at the stackoverflow description.

---

**Affects:** 1.8.9 (Ingalls SR9)

**Reference URL:** https://stackoverflow.com/questions/47763245/cannot-get-jedis-connection-could-not-get-a-resource-from-the-pool

**Attachments:**
- [exception.txt](https://jira.spring.io/secure/attachment/25324/exception.txt) (_6.31 kB_)

**Comment by sunqb** [comment]
oh hoo ，this is a good issue.
