### ISSUE TITLE
enableTransactionSupport cause Redis Pool connections leak [DATAREDIS-823]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-redis#1395]
**[GaoChao](https://jira.spring.io/secure/ViewProfile.jspa?name=gaochao)** opened **[DATAREDIS-823](https://jira.spring.io/browse/DATAREDIS-823?redirect=false)** and commented

If set enableTransactionSupport=true and use RedisCache (Not use `@Transactional` Because 

we use `@Cacheable`)

```java
RedisTemplate<Object, Object> template = new RedisTemplate<>();
template.setEnableTransactionSupport(true);

RedisCacheManager redisCacheManager = new RedisCacheManager(template);
```

When call org.springframework.data.redis.core.RedisConnectionUtils#releaseConnection

isConnectionTransactional return true TransactionSynchronizationManager.isCurrentTransactionReadOnly() return false,so both unbindConnection and conn.close() are not executed.

```java
if (isConnectionTransactional(conn, factory)  
      && TransactionSynchronizationManager.isCurrentTransactionReadOnly()) {
   unbindConnection(factory);
} else if (!isConnectionTransactional(conn, factory)) {
   if (log.isDebugEnabled()) {
      log.debug("Closing Redis Connection");
   }
   conn.close();
}
```

The result is the connection is not released.

 

---

**Affects:** 1.8.11 (Ingalls SR11)

**Attachments:**
- [SpringDataRedisDemo.zip](https://jira.spring.io/secure/attachment/25708/SpringDataRedisDemo.zip) (_6.28 kB_)

1 votes, 1 watchers

**Comment by mp911de** [comment]
That issue was addressed with #573 in version 2.5.0 M1. Marking it as duplicate.
