### ISSUE TITLE
Add support for ZPOPMIN, ZPOPMAX, BZPOPMIN, BZPOPMAX commands [DATAREDIS-841]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1400]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAREDIS-841](https://jira.spring.io/browse/DATAREDIS-841?redirect=false)** and commented

---

**Reference URL:** https://redis.io/commands/bzpopmin

**Issue Links:**
- [DATAREDIS-837](https://jira.spring.io/browse/DATAREDIS-837) Add support for [B]Z[REV]POP commands
 (_**"duplicates"**_)

**Comment by yairlenga** [comment]
Any progress on this issue. We have a project where BZPOPMAX is critical (prioritized queues) - otherwise, we need to create LUA function to achieve the same result. Is there alternative - can RedisZsetOperation be extended ?

**Comment by christophstrobl** [comment]
Support has been added recently via #2088.
Closing this one.
