### ISSUE TITLE
Add `TtlFunction` to `RedisCacheConfiguration` for dynamic Time to Live

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1433]
**[Kyle Cronin](https://jira.spring.io/secure/ViewProfile.jspa?name=kylecronin@adp)** opened **[DATAREDIS-858](https://jira.spring.io/browse/DATAREDIS-858?redirect=false)** and commented

`RedisCache` should allow sub classes to define the TTL duration based on the cache key or value for use cases where the TTL is not know at configuration time or could change depending on the value being stored. For example access tokens where the token provider specifies how long the token is valid for.

 

```java
public class RedisCache {
   // default impementation delegates to cache config
   @NonNull protected Duration getTtl(Object key, Object value) { 
      return cacheConfig.getTtl(); 
   }
}

public class AccessTokenRedisCache extends RedisCache {
   @Override
   @NonNull
   protected Duration getTtl(Object key, Object value) {
      if (value instanceof AccessToken) {
         return ((AccessToken) value).getTtl();
      } else {
         return super.getTtl(key, value);
      }
   }
}
```

If there was a way to specify a TTL policy in the RedisCacheConfiguration that would be bonus

---
No further details from [DATAREDIS-858](https://jira.spring.io/browse/DATAREDIS-858?redirect=false)

**Comment by nicdard** [comment]
Hi, is this issue still active? I have multiple use cases were I would like to randomise the TTL at each put operation, and I would like to rise a PR for this :)
