### ISSUE TITLE
Enable Jedis Lua usage in transaction and pipeline

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1455]
**[Mikael Carlstedt](https://jira.spring.io/secure/ViewProfile.jspa?name=mikael.carlstedt)** opened **[DATAREDIS-882](https://jira.spring.io/browse/DATAREDIS-882?redirect=false)** and commented

Both eval() and evalSha() methods in JedisScriptingCommands throw [UnsupportedOperationException](https://github.com/spring-projects/spring-data-redis/blob/66945e62923adca2cbc98ba51736b948aa1de49a/src/main/java/org/springframework/data/redis/connection/jedis/JedisScriptingCommands.java#L124) when called from inside a transaction or pipeline. However, LUA script execution works fine inside transactions when using native Jedis API (I stumbled across this restriction while migrating working code from native Jedis with evalSha inside transactions to RedisTemplate). Is this some historical restriction?

---
No further details from [DATAREDIS-882](https://jira.spring.io/browse/DATAREDIS-882?redirect=false)

**Comment by mp911de** [comment]
To add a bit of detail: Jedis didn't support `SCRIPT …` commands for quite a while. Only starting with Jedis 4, `SCRIPT …` commands have been added to the pipelining/transaction API.
