### ISSUE TITLE
RedisCacheConfiguration doesnot allow use keySerliazerPair other than String SerialiazationPair. [DATAREDIS-926]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1497]
**[Rameez Raja Syed Ibrahim](https://jira.spring.io/secure/ViewProfile.jspa?name=rameezrajas)** opened **[DATAREDIS-926](https://jira.spring.io/browse/DATAREDIS-926?redirect=false)** and commented

RedisCacheConfiguration doesnot allow to use keySerliazerPair other than String SerialiazationPair.

We have set of services running on spring boot 1.5.12/spring-data-redis 1.8.14 and we are  migrating services to springboot 2.0.4 and spring-data-redis 2.1.0.M3 one by one.

spring-data-redis 1.8.14 default key serialization is JdkSerializer where as spring-data-redis 2.1.0.M3 default key serialization is String Serializer. We are not able to customize the key serializer in 2.1.0.M3. This is preventing us from smooth migration

---

**Affects:** 2.1.4 (Lovelace SR4)

**Comment by mp911de** [comment]
We have extensive support for converting cache keys to `String` that allows you registering a converter that converts the cache key into a string. We are using string-based keys because we support key prefixes and allows scanning by prefix.
