### ISSUE TITLE
The plan using @Cacheable in spring-web-flux [DATAREDIS-967]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1541]
**[kongh](https://jira.spring.io/secure/ViewProfile.jspa?name=kongh)** opened **[DATAREDIS-967](https://jira.spring.io/browse/DATAREDIS-967?redirect=false)** and commented

I am using spring-web-flux and want to use `@Cacheable` for caching the domain entity, but , 

org.springframework.data.redis.cache is not reactive .

 

How can I resovle the problem ?

 

 

---
No further details from [DATAREDIS-967](https://jira.spring.io/browse/DATAREDIS-967?redirect=false)

**Comment by christophstrobl** [comment]
There has been some movement on FW side recently resolving spring-projects/spring-framework#17920.
