### ISSUE TITLE
Provide TLS support for Sentinel clients in Jedis driver [DATAREDIS-989]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1560]
**[Mark Petrovic](https://jira.spring.io/secure/ViewProfile.jspa?name=mspetrovic@gmail.com)** opened **[DATAREDIS-989](https://jira.spring.io/browse/DATAREDIS-989?redirect=false)** and commented

Please support TLS connections to the Redis Sentinel and TLS connections to the sentinel-reported master.  I understand this requires support in the underlying major clients, such as [Jedis|https://github.com/xetorthio/jedis/issues/1987], for which corresponding issues have been filed

---

**Affects:** 2.1.8 (Lovelace SR8)

**Comment by mp911de** [comment]
Depends on https://github.com/redis/jedis/issues/1987 (Jedis 3.6)
