### ISSUE TITLE
Add support for final/Kotlin classes in `GenericJackson2JsonRedisSerializer` [DATAREDIS-995]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1566]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[DATAREDIS-995](https://jira.spring.io/browse/DATAREDIS-995?redirect=false)** and commented

As described in detail in this [Jackson issue](https://github.com/FasterXML/jackson-databind/issues/2349), it is currently not possible to use `GenericJackson2JsonRedisSerializer` with final classes. That's especially blocking in Kotlin where classes are final by default, and data classes always final.

This issue should be fixed at Jackson level

---
No further details from [DATAREDIS-995](https://jira.spring.io/browse/DATAREDIS-995?redirect=false)

**Comment by azizabah** [comment]
@mp911de - Started working on a simple PR for that to swap over the DefaultTyping to EVERYTHING enum and added a test for it. Looks like it breaks the null serialization though with shouldSerializeNullValueSoThatItCanBeDeserializedWithDefaultTypingEnabled() throwing a:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type org.springframework.cache.support.NullValue
```

I can still go ahead and submit the PR if you want but I'm a bit at a loss for that one.

**Comment by christophstrobl** [comment]
For the failing test in `GenericJackson2JsonRedisSerializerUnitTests` we need to add an override for `serializeWithType` to the `NullValueSerializer` that delegates to `serialize`.

Still, there are more problems related to moving to `EVERYTHING`. 

The `DefaultTypeResolverBuilder` always returns `true` when requesting `useType` even when the given one is a `TreeNode`. 
This breaks the integration test for the `Jackson2HashMapper`. It seems we need to provide our own flavour of `DefaultTypeResolverBuilder` that does something like 
```
case EVERYTHING:
	return !TreeNode.class.isAssignableFrom(t.getRawClass());
```
and hook it into the `ObjectMapper` by overriding `_constructDefaultTypeResolverBuilder`.
