### ISSUE TITLE
Add approximate trim support for XTRIM [DATAREDIS-1085]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1616]
**[Sergey Karimov](https://jira.spring.io/secure/ViewProfile.jspa?name=enforcer)** opened **[DATAREDIS-1085](https://jira.spring.io/browse/DATAREDIS-1085?redirect=false)** and commented

Redis from some version, don't know which exactly, supports following syntax:

xadd somekey maxlen ~ 1 * key1 value1

key feature here is "maxlen ~ 1" (may be any number).

same for:

xtrim somekey ~ 1

There is no way to specify "maxlen ~ 1" for xadd via ReactiveStreamCommands or RedisStreamCommands.

There is no way to specify "xtrim somekey ~ 1" via ReactiveStreamCommands or RedisStreamCommands, only "xtrim somekey 1", which is huge preformance impact compared to "xtrim somekey ~ 1"

---

**Affects:** 2.2.3 (Moore SR3)

**Issue Links:**
- [DATAREDIS-1122](https://jira.spring.io/browse/DATAREDIS-1122) Add support for MAXLEN attribute of XADD

**Referenced from:** pull request https://github.com/spring-projects/spring-data-redis/pull

2 votes, 5 watchers

**Comment by peterspikings** [comment]
What about XTRIM ~ ? There's a method in Lettuce which takes a boolean for approximate trimming, all it needs is a passthrough, should I do a PR? :)

**Comment by mp911de** [comment]
Care to elaborate what's missing? https://github.com/spring-projects/spring-data-redis/commit/99cf4a223852d6d5d6b7f9b014e196aa47f50975 introduced `xTrim(byte[] key, long count, boolean approximateTrimming)` on the connection API and `trim(K key, long count, boolean approximateTrimming)` on the Template API.

**Comment by peterspikings** [comment]
Sorry, my bad! It was exactly those I was after and didn't realise I was looking at an old version which didn't have them (2.3.7) even though the underlying Lettuce implementation did. From the comments it looks like you just changed the XADD :) I'll get my coat....
