### ISSUE TITLE
Add an event to RedisContainer when subscription is ready [DATAREDIS-1047]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1622]
**[Piotr](https://jira.spring.io/secure/ViewProfile.jspa?name=piotrzi)** opened **[DATAREDIS-1047](https://jira.spring.io/browse/DATAREDIS-1047?redirect=false)** and commented

Currently addMessageListener is asynchronous method and there is no way to determine if a subscription is ready (it uses lazy loading). In my scenario I need to know when a service is ready to receive messages from Redis as it needs to send initial state to connected clients.

The feature would be also useful for scenarios when subscriptions are added at runtime rather than at startup.

 

The similar problem was reported here: https://stackoverflow.com/questions/32297321/spring-data-redis-how-do-i-know-that-messagelistener-is-ready

---
No further details from [DATAREDIS-1047](https://jira.spring.io/browse/DATAREDIS-1047?redirect=false)

**Comment by mp911de** [comment]
Depends on #1697

**Comment by mp911de** [comment]
Depends on #2054

**Comment by mp911de** [comment]
This will be fixed via #964.
