### ISSUE TITLE
Add a parameter to control if we can call Cache.clear() [DATAREDIS-1102]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1672]
**[Daniel Woo](https://jira.spring.io/secure/ViewProfile.jspa?name=danielywoo)** opened **[DATAREDIS-1102](https://jira.spring.io/browse/DATAREDIS-1102?redirect=false)** and commented

There are many subclasses of Cache, sometimes clear() is not feasible. Like RedisCache, when you have a large Redis cluster and some unwary programmer writes `@CacheEvict`(allEntries=true), this will be a disaster. We suffered from a severe accident on this before, then we renamed Redis command "keys" and "flushdb" to something else, and created subclass of Cache to disable clear() totally.

Unconditional disabling clear() is not right in other cases, when the cache is in-memory and small enough, we can do it. So, is it possible to add a parameter to RedisCacheConfiguration like allowEvictAll? (default to true to keep compatibility)

If you agree this is a common requirement I can create a pull request for it

---

**Affects:** 2.2.4 (Moore SR4)

**Comment by mp911de** [comment]
Cache configuration isn't the right place for such requirements. Instead, please provide your own `CacheManager` and `Cache` by wrapping the Redis Cache. That way, you get the most control over the actual cache behavior.
