### ISSUE TITLE
Add Pub/Sub callbacks for subscribed/unsubscribed events [DATAREDIS-1129]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1697]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAREDIS-1129](https://jira.spring.io/browse/DATAREDIS-1129?redirect=false)** and commented

We should allow to get notified once a pub/sub activity (subscribe/unsubscribe at channel/pattern) has happened. Ideally an extension along the lines of:

```java
MessageListener {

 default void onSubscribe(Topic) {}
 default void onUnsubscribe(Topic) {}
}
```

 

 

---
No further details from [DATAREDIS-1129](https://jira.spring.io/browse/DATAREDIS-1129?redirect=false)

**Comment by mp911de** [comment]
Superseded by #2054.
