### ISSUE TITLE
DefaultRedisCacheWriter.clean() uses blocking KEYS command [DATAREDIS-1151]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1721]
**[eyison](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49602)** opened **[DATAREDIS-1151](https://jira.spring.io/browse/DATAREDIS-1151?redirect=false)** and commented

when I use `clean` method in class `DefaultRedisCacheWriter` ,it will excute `keys` command which is block,it may take a lot of time and cause other commands time out

---

**Affects:** 2.1.17 (Lovelace SR17), 2.2.7 (Moore SR7), 2.3 GA (Neumann)

**Reference URL:** https://github.com/spring-projects/spring-data-redis/blob/2bcb06acc88ee23d2d355568ed96ca303d9f86a3/src/main/java/org/springframework/data/redis/cache/DefaultRedisCacheWriter.java#L182

**Issue Links:**
- [DATAREDIS-1113](https://jira.spring.io/browse/DATAREDIS-1113) Use SCAN instead KEYS when clean cache
 (_**"is duplicated by"**_)
- [DATAREDIS-1176](https://jira.spring.io/browse/DATAREDIS-1176) org.springframework.data.redis.cache.DefaultRedisCacheWriter#clean method  may ruin performance
 (_**"is duplicated by"**_)
- [DATAREDIS-1152](https://jira.spring.io/browse/DATAREDIS-1152) change clean method  `keys` command to `scan` in DefaultRedisCacheWriter
 (_**"is duplicated by"**_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-redis/pull/532

1 votes, 4 watchers

**Comment by mp911de** [comment]
A potential way out could be introducing a clean strategy that either uses `KEYS` or `SCAN`.
