### ISSUE TITLE
Redis ReactiveValueOperations is blocking when redis-server is shutdown [DATAREDIS-1205]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1731]
**[Kannadasan](https://jira.spring.io/secure/ViewProfile.jspa?name=kanna)** opened **[DATAREDIS-1205](https://jira.spring.io/browse/DATAREDIS-1205?redirect=false)** and commented

I am working with Reactiveredis using springboot, after the implementation, I tried few negative scenarios, Lets consider, service is running and I forcefully shutdown the redis-server, during that time, while calling get(...) method its getting blocked, until it establish the connection. I need a behavior like "**if then else**" immediately. 

```java
@Repository
public class CustomerRepository {

	private ReactiveValueOperations<String, Object> valueOps;

	@Autowired
	public CustomerRepository (@Qualifier("reactiveRedisTemplate") ReactiveRedisOperations<String, Object> redisTemplate) {
		this.valueOps = redisTemplate.opsForValue();
	}


	public Mono<Object> get(String key) {
		return valueOps.get(key);
	}
}
```

If I have disable the "autoReconnect" feature, then during the next redis command execution its not attempting to establish connection to redis server.
Could you please suggest here?

---
No further details from [DATAREDIS-1205](https://jira.spring.io/browse/DATAREDIS-1205?redirect=false)

**Comment by mp911de** [comment]
The issue should be resolved by now.
