### ISSUE TITLE
Redis Data ignores method annotated with @Id [DATAREDIS-1183]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1757]
**[Huo12345](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49952)** opened **[DATAREDIS-1183](https://jira.spring.io/browse/DATAREDIS-1183?redirect=false)** and commented

I'm trying to store an object whith a composite key with redis data. According to [DATAREDIS-1078](https://jira.spring.io/browse/DATAREDIS-1078), this is supported as long as the method follows the getter pattern. This seems not to be the case. Example:

```java
@RedisHash
public class Entry {
    @Indexed
    private String internalId;
    private String externalId;
    private String partnerId;

    @Id
    public String getId() {
        return String.format("%s_%s", partnerId, internalId);
    }
}
```

When spring creates the accoring CrudRepository, it fails with the following exception:

```java
Caused by: org.springframework.data.mapping.MappingException: Entity com.example.Entry requires to have an explicit id field. Did you forget to provide one using @Id?
```

Therefore my question, does redis data support methods as id source and if not, what is the pattern foreseen for composite keys?

 

Additional version info:
JDK: 11
spring-boot-starter-data-redis: 2.2.8.RELEASE

---

**Affects:** 2.2.8 (Moore SR8)

**Comment by conlaoch1** [comment]
Hi there. I'm having the same problem. `@AccessType(Type.PROPERTY)` does not fix it, unfortunately.
