### ISSUE TITLE
Ability to inherit/override DefaultRedisCacheWriter [DATAREDIS-1209]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-redis#1778]
**[Anton Golenkovskiy](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50225)** opened **[DATAREDIS-1209](https://jira.spring.io/browse/DATAREDIS-1209?redirect=false)** and commented

In our project we use Spring Data Redis for caching, but we need an ability to gracefully fallback to fetching from DB when cache instance fails.
Regular DefaultRedisCacheWriter throws errors if redis connection hangs and overriding Spring's CacheErrorHandler only helps with RuntimeExceptions (some connection exceptions are not part of that inheritance chain).
So what we end up doing is wrapping DefaultRedisCacheWriter methods with try/catch blocks in order to return "null" from cache operations (which makes spring fallback to DB query)

```
class SafeLoggingCacheWriter(connectionFactory: RedisConnectionFactory) : DefaultRedisCacheWriter(connectionFactory) {

    private val log = KotlinLogging.logger {}

    override fun get(name: String, key: ByteArray): ByteArray? {
        return try {
            super.get(name, key)
        } catch (t: Throwable) {
            log.warn("Error executing cache operation: {}", t.message)
            null
        }
    }
// Other methods omitted
}
```

But since **DefaultRedisCacheWriter is package-private** class - we had to make a copy inside our project instead of inheriting from it.

So request is to either make DefaultRedisCacheWriter class public or provide some decorating capabilities

---

**Affects:** 2.1.19 (Lovelace SR19)

**Comment by mp911de** [comment]
Please configure a `CacheErrorHandler` on your Cache. The default implementation (`SimpleCacheErrorHandler`) simply rethrows an exception. If the exception is handled, then failed gets are considered a cache miss.

**Comment by M1strall** [comment]
@mp911de Cache Error handler only handle RuntimeExceptions. Some of the connection timeout exceptions are not Runtime therefore can still affect application when it cannot connect to the cache.

**Comment by mp911de** [comment]
`Cache` only throws `RuntimeException`, none of the methods of `Cache` declares checked exceptions so you should be good.
