### ISSUE TITLE
org.springframework.data.redis.RedisSystemException: Redis command interrupted; nested exception is io.lettuce.core.RedisCommandInterruptedException: Command interrupted [DATAREDIS-1211]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-redis#1780]
**[JackChen1866](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50306)** opened **[DATAREDIS-1211](https://jira.spring.io/browse/DATAREDIS-1211?redirect=false)** and commented

org.springframework.data.redis.RedisSystemException: Redis command interrupted; nested exception is io.lettuce.core.RedisCommandInterruptedException: Command interruptedorg.springframework.data.redis.RedisSystemException: Redis command interrupted; nested exception is io.lettuce.core.RedisCommandInterruptedException: Command interrupted at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:62) at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:270) at org.springframework.data.redis.connection.lettuce.LettuceHashCommands.convertLettuceAccessException(LettuceHashCommands.java:471) at org.springframework.data.redis.connection.lettuce.LettuceHashCommands.hIncrBy(LettuceHashCommands.java:246) at org.springframework.data.redis.connection.DefaultedRedisConnection.hIncrBy(DefaultedRedisConnection.java:1062) at org.springframework.data.redis.core.DefaultHashOperations.lambda$increment$3(DefaultHashOperations.java:91) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) at org.springframework.data.redis.core.DefaultHashOperations.increment(DefaultHashOperations.java:91) at cn.qpyl.server.base.cache.Redis.hincr(Redis.java:322) at cn.qpyl.game.match.gold.room.RoomService.onSaveOverData(RoomService.java:207) at cn.qpyl.game.match.room.RoomMatch.onGameRequestPlayOver(RoomMatch.java:313) at cn.qpyl.game.match.gold.room.RoomService.onGameRequestPlayOver(RoomService.java:163) at cn.qpyl.game.match.gold.room.RoomService$$FastClassBySpringCGLIB$$3f2346c9.invoke(\<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) at cn.qpyl.game.match.gold.room.RoomService$$EnhancerBySpringCGLIB$$36912aa5.onGameRequestPlayOver(\<generated>) at cn.qpyl.game.match.game.room.GameRoomBase.savePlayOverData(GameRoomBase.java:604) at cn.qpyl.game.match.game.room.GameRoomBase.onPlayOver(GameRoomBase.java:538) at cn.qpyl.games.majiang.PlayMaJiang.runPlayOver(PlayMaJiang.java:333) at cn.qpyl.games.majiang.PlayMaJiang.onPlayOver(PlayMaJiang.java:320) at cn.qpyl.games.majiang.rules.r1534.play.PlayMaJiangObject.onPlayOver(PlayMaJiangObject.java:110) at cn.qpyl.games.majiang.solitary.fapai.FaPaiMaJiang.onPlayOver(FaPaiMaJiang.java:411) at cn.qpyl.games.majiang.solitary.fapai.FaPaiMaJiang.zhuaPai(FaPaiMaJiang.java:367) at cn.qpyl.games.majiang.solitary.operate.OperateMaJiang.zhuaPai(OperateMaJiang.java:153) at cn.qpyl.games.majiang.solitary.operate.OperateMaJiang.checkCommandSelectForPlayStatusPlay(OperateMaJiang.java:400) at cn.qpyl.games.majiang.solitary.operate.OperateMaJiang.sendToSeat(OperateMaJiang.java:627) at cn.qpyl.games.majiang.solitary.operate.OperateMaJiang.sendToSeat(OperateMaJiang.java:46) at cn.qpyl.games.majiang.PlayMaJiang.checkCommand(PlayMaJiang.java:531) at cn.qpyl.games.majiang.PlayMaJiang.sendCommandToSeat(PlayMaJiang.java:498) at cn.qpyl.games.majiang.trusteeship.OperateTrusteeshipChecker.trusteeshipChuPai(OperateTrusteeshipChecker.java:35) at cn.qpyl.games.majiang.rules.r1534.play.solitary.OperateTrusteeshipCheckerObject.trusteeshipChuPai(OperateTrusteeshipCheckerObject.java:19) at cn.qpyl.games.majiang.solitary.operate.starter.StartAtZhuaPai.trusteeshipChuPai(StartAtZhuaPai.java:243) at cn.qpyl.games.majiang.solitary.operate.starter.StartAtZhuaPai.onTimeout(StartAtZhuaPai.java:221) at cn.qpyl.games.majiang.PlayMaJiang.lambda$newTimer$0(PlayMaJiang.java:88) at cn.qpyl.thread.SingleThreadRuner.funTryRun(SingleThreadRuner.java:175) at cn.qpyl.thread.SingleThreadRuner.funTryRunThreadId(SingleThreadRuner.java:49) at cn.qpyl.thread.SingleThreadRuner.runTask(SingleThreadRuner.java:39) at cn.qpyl.game.match.game.room.GameRoomBase.lambda$taskTimeoutPlay$11(GameRoomBase.java:1020) at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)Caused by: io.lettuce.core.RedisCommandInterruptedException: Command interrupted at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:87) at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:112) at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69) at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) at com.sun.proxy.$Proxy107.hincrbyfloat(Unknown Source) at org.springframework.data.redis.connection.lettuce.LettuceHashCommands.hIncrBy(LettuceHashCommands.java:244) ... 44 common frames omittedCaused by: java.lang.InterruptedException: null at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347) at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:83) ... 49 common frames omitted

---

1 votes, 3 watchers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by XiaoPenPen** [comment]
hi, My version is [3.2.8-alpine], I have the same error in spring-cloud-gateway:2.2.1.RELEASE， spring-boot-starter-data-redis:2.2.0.RELEASE， in my [Filter] class use redisTemplate.get(myKey)， Will report this error. It is sporadic. It will not appear until the program runs for a period of time, and will become normal after restarting. Do you have any good suggestions.

**Comment by XiaoPenPen** [comment]
@spring-projects-issues
