### ISSUE TITLE
Lettuce driver breaks after receiving Thread interrupt [DATAREDIS-1266]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-redis#1817]
**[Duncan Casteleyn](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50808)** opened **[DATAREDIS-1266](https://jira.spring.io/browse/DATAREDIS-1266?redirect=false)** and commented

I recently upgraded to Spring Boot 2.4.1 from 2.3.6.RELEASE and started getting problems with Spring Data Redis throwing null pointer exceptions, when I revert to the previous version of Spring Boot this does not happen.

[Here is a stack trace of the issues](https://gist.github.com/DuncanCasteleyn/43c84c266e91ab1b9acb470d8a4387af), I'm using Redis with repositories and they all start throwing this exception. My code of the application can be found [here](https://github.com/DuncanCasteleyn/DiscordModBot/tree/feature/upgrade-spring-2.4.x). This application uses the starter auto configuration with no additional Redis specific properties configured.

I tried switching to Jedis and this seems to resolve my problem, I assume there is a problem somewhere with the lettuce driver. I use the default configuration provided by Spring Boot with no configured spring.redis.* properties everything is default as provided by the starter auto configuration.

 

I included stack traces of all the different exceptions I'm getting, the logs are mainly spammed with org.springframework.data.keyvalue.core.UncategorizedKeyValueException.

 

Edit:

After checking out the logs more in detail it seems the lettuce driver breaks if it receives a thread interrupt while performing an operation, permanently breaking the lettuce driver connection, this also means that whichever operation was busy might have been lost or got corrupted and any new operations will fail to be performed

---

**Affects:** 2.4.2 (2020.0.2)

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/24562

**Comment by mp911de** [comment]
`InterruptedException` is a consequence of some code calling `Thread.interrupt()`. There's nothing we can do in Spring about that.

**Comment by DuncanCasteleyn** [comment]
@mp911de This however was not a problem in previous versions, but introduced starting this version and it also does not happen with Jedis.

If it won't be fixed then I assume that switching to Spring Data Reactive would resolve this problem right?

**Comment by mp911de** [comment]
Jedis doesn't come with a Threading infrastructure so it's a natural consequence that this behavior cannot occur with Jedis. Since the actual cause isn't known, the reactive API usage is affected as well since that's just a different API.
