### ISSUE TITLE
Reactive Repositories are not supported by Redis [DATAREDIS-1250]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1823]
**[Abhijit Sarkar](https://jira.spring.io/secure/ViewProfile.jspa?name=asarkar)** opened **[DATAREDIS-1250](https://jira.spring.io/browse/DATAREDIS-1250?redirect=false)** and commented

The following repository definition fails:

```
interface TestRepo: CoroutineCrudRepository<Uuid, String>
```

with

```
org.springframework.dao.InvalidDataAccessApiUsageException: Reactive Repositories are not supported by Redis. Offending repository is com.mycompany.persistence.TestRepo!
```

However, Lettuce 6.0 has [Coroutines support](https://lettuce.io/core/release/reference/index.html#kotlin). Even without it, the commands from `ReactiveRedisTemplate` can be translated to Coroutines using extensions.

Data Cassandra supports `CoroutineCrudRepository`. Why won't Redis?

---

**Affects:** 2.3.5 (Neumann SR5)

**Comment by mp911de** [comment]
We do not support reactive Redis repositories because a reactive implementation doesn't provide any value regarding reactive properties. Additionally, the inherent complexity that a reactive implementation requires leads us to the decision not to provide reactive Redis repositories.
