### ISSUE TITLE
Allow configuration of `RedisMessageListenerContainer` through `@EnableRedisRepositories`

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1827]
**[j-razeed](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49947)** opened **[DATAREDIS-1256](https://jira.spring.io/browse/DATAREDIS-1256?redirect=false)** and commented

Currently I am facing an issue similar to https://jira.spring.io/browse/DATAREDIS-499.

As advised, I am checking the possibility of assigning my own TaskExecutor (ThreadPool) to RedisMessageListenerContainer. 

RedisKeyValueAdapter creates RedisMessageListenerContainer as a private instance variable. Hence, I am not able to assign my own TaskExecutor. Can you please help

---
No further details from [DATAREDIS-1256](https://jira.spring.io/browse/DATAREDIS-1256?redirect=false)

**Comment by sm0217** [comment]
Posted a message in gitter for the same problem and do not want to create a new issue in here. Any help on this please. 

`Any ideas on how to override the RedisMessageListenerContainer/taskExecutor on RedisKeyValueAdapter.MappingExpirationListener. It is initialised when we enable keyspace events on startup. By default, it uses a SimpleAsync executor for which there is no limit on threads and I do not see a way to override the redis listener container/task executor for RedisKeyValueAdapter.`
