### ISSUE TITLE
Why the execute method can get the value, but the opsForValue/boundValueOps method cannot

### ISSUE THREAD

**Issue by a123demi** [spring-projects/spring-data-redis#1953]
method1:
 byte[]  values = redisTemplate.opsForValue().get(cacheKey.getBytes());
method2:
RedisCallback<byte[]> redisCallback = connection -> connection.get(cacheKey.getBytes());
values = redisTemplate.execute(redisCallback);

 <bean id="redisTemplate" class="org.springframework.data.redis.core.RedisTemplate">
        <property name="connectionFactory" ref="redisConnFactory"/>
        <property name="keySerializer" ref="jdkSerializationRedisSerializer"/>
        <property name="valueSerializer" ref="jdkSerializationRedisSerializer"/>
    </bean>

Through redistemplate, why the execute method can get the value, but the opsForValue/boundValueOps method cannot

**Comment by mp911de** [comment]
This looks like a serialization issue. `RedisTemplate` uses its configured `RedisSerializer` to encode objects before writing these to Redis. If you're operating already on the `byte[]` level, then configuring `RedisTemplate` with `RedisSerializer.byteArray()` will help there. Alternatively, you can use a `String` serializer (or any other type depending on what Java types you want to use for Redis serialization).

**Comment by a123demi** [comment]
Thanks, I get it.  
It’s a serialization problem, I reimplemented the serialization method
