### ISSUE TITLE
Cache hit/miss statistics

### ISSUE THREAD

**Issue by asiletto** [spring-projects/spring-data-redis#1956]
I would like to propose an enhancement

 Is it possible to collect metrics about hit/miss for each cache?

Eg: increment one of two spring metrics counters for each defined cache (hit/miss) in the method **private Object execute(final CacheOperationInvoker invoker, Method method, CacheOperationContexts contexts)** of the class   **org.springframework.cache.interceptor.CacheAspectSupport**

```
		if (cacheHit != null && !hasCachePut(contexts)) {
			// If there are no put requests, just use the cache hit
			cacheValue = cacheHit.get();
			returnValue = wrapCacheValue(method, cacheValue);
		}
		else {
			// Invoke the method if we don't have a cache hit
			returnValue = invokeOperation(invoker);
			cacheValue = unwrapReturnValue(returnValue);
		}

```

and expose those counters in the actuator endpoint

**Comment by mp911de** [comment]
`CacheAspectSupport` is a Spring Framework class that has isn't related to cache statistics at all.

**Comment by mp911de** [comment]
Spring Data has no access to access to `CacheAspectSupport` so we can't do anything about it here. You can apply these customizations in your own code.

**Comment by snicoll** [comment]
> Is it possible to collect metrics about hit/miss for each cache?

Don't we do that already? `RedisCache` has a `CacheStatistics` object that exposes that information and this is auto-configured by Spring Boot so it should just work. 

If you're talking about a generic hit/miss feature, this isn't the job of the cache abstraction to do that. One reason is that it is the wrong layer of abstraction.
