### ISSUE TITLE
Support for storing data locally

### ISSUE THREAD

**Issue by jaspreetsingh96** [spring-projects/spring-data-redis#1958]
Is support for storing data locally provided so that number of calls to redis can be reduced?

**Comment by mp911de** [comment]
Care to elaborate? Redis is a remote service and Spring Data Redis provides connectivity to Redis so I fail to see how we can provide something locally.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
