### ISSUE TITLE
Class with @RedisHash and byte[] property is turned into Map<String, Byte>

### ISSUE THREAD

**Issue by bergerst** [spring-projects/spring-data-redis#1981]
I discovered that if you define a class with @RedisHash and a byte[] property, one key-value pair is stored for each byte.

Here's some example code:

```java
@RedisHash("myclass")
@lombok.Data
public class MyClass {
  @Id
  private String id;
  private byte[] property;

  public MyClass(String id) {
    this.id = id;
    property = new byte[4000];
    Random rd = new Random();
    rd.nextBytes(property);
  }
}
```

When an object of this class is stored in Redis using a `CrudRepository<MyClass, String>`, the Redis content will look like this:
```
property.[3018] = 50
property.[298] = 156
property.[1892] = 2
...
```

When you then use `findById` on the repository, `Bucket.extract()` will be called by `MappingRedisConverter.readCollectionOrArray()` for each key, leading to about 16 million `String.startsWith()` calls.

In my opinion, the `byte[]` should be stored as a `String` value, not as a `Map<String, Byte>`.

Replacing the byte[] with a String reduced the run time of my webservice operation from 1200 ms to 45 ms.

**Comment by bergerst** [comment]
Generally speaking, the performance of `MappingRedisConverter.readCollectionOrArray()` can be improved in all cases when large collections or arrays are stored.

I was able to reduce the time from 1200 ms to 144 ms by rewriting `MappingRedisConvert.readCollectionOrArray()` like this:
```java
@Nullable
  private Object readCollectionOrArray(String path, Class<?> collectionType, Class<?> valueType,
      Bucket bucket) {

    boolean isArray = collectionType.isArray();
    Class<?> collectionTypeToUse = isArray ? ArrayList.class : collectionType;

    Bucket data = bucket.extract(path + ".[");
    Collection<Object> target =
        CollectionFactory.createCollection(collectionTypeToUse, valueType, data.entrySet().size());

    List<String> keys = new ArrayList<>(data.keySet());
    keys.sort(listKeyComparator);

    for (String key : keys) {
      byte[] value = data.get(key);

      if (conversionService.canConvert(byte[].class, valueType)) {
        target.add(fromBytes(value, valueType));
      } else {
        Bucket elementBucket = new Bucket();
        elementBucket.put(key, value);
        target.add(readInternal(key, valueType, new RedisData(elementBucket)));
      }
    }

    return isArray ? toArray(target, collectionType, valueType)
        : (target.isEmpty() ? null : target);
  }
```

Do you want me to create a PR for that part? It may not be the optimal solution, but it does the job much better.

A second change will be needed in order to read `byte[]` properties at once. How it's done right now:
1. Read byte as byte[]
2. Convert byte[] to Byte
3. Add Byte to `Collection<Byte>`
4. Convert `Collection<Byte>` to byte[]
5. Set property with byte[]

**Comment by christophstrobl** [comment]
We'd be happy to review a PR. 
Please follow the [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc) and make sure all tests are passing. The above change seems break some in `MappingRedisConverterUnitTests`.

**Comment by bergerst** [comment]
You're right, I didn't understand the full logic of the existing implementation.

The unit tests pass for my submitted PR.

**Comment by mp911de** [comment]
It would make sense to consider `byte[]` as a native simple type as the underlying data structure for Strings, numbers, etc. is a `byte[]`. Following the path opens a discussion about backward compatibility. Our code should be able to read byte arrays in the current format and directly from the hash value.

I'd be generally fine with tweaking the representation as of the next feature release. Any objections @christophstrobl?

**Comment by christophstrobl** [comment]
fine with me.
