### ISSUE TITLE
Cannot infer type arguments when compiling with Eclipse

### ISSUE THREAD

**Issue by bergerst** [spring-projects/spring-data-redis#1983]
I'm using Eclipse 2020-09 and the following locations produce compiler errors:

https://github.com/spring-projects/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceScriptingCommands.java#L101L103

https://github.com/spring-projects/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceScriptingCommands.java#L119L121

https://github.com/spring-projects/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L655L656

The compiler messages are:
```
Cannot infer type argument(s) for <R, T1, T2, T3, T4> from(LettuceInvoker.ConnectionFunction4<T1,T2,T3,T4,R>, T1, T2, T3, T4)
Cannot infer type argument(s) for <R, T1, T2, T3, T4> from(LettuceInvoker.ConnectionFunction4<T1,T2,T3,T4,R>, T1, T2, T3, T4)
Cannot infer type argument(s) for <R, T1, T2, T3> just(LettuceInvoker.ConnectionFunction3<T1,T2,T3,R>, T1, T2, T3)
```

It compiles just fine using Maven, but not with the Eclipse Java Compiler.

Is there some way to fix this?

**Comment by mp911de** [comment]
You might report the issue to the ECJ issue tracker so they can have a look.
