### ISSUE TITLE
Add support for CONFIG REWRITE

### ISSUE THREAD

**Issue by kender1314** [spring-projects/spring-data-redis#1992]
Hi, I called the setConfig method in the RedisConnection class to modify some configurations, but I did not find the config rewrite command. It seems that this command is not supported. Will this command be supported in the future? How do I write the modified config into the configuration file now?
Thanks.

**Comment by kender1314** [comment]
@mp911de

**Comment by kender1314** [comment]
Hello，anyone there?

**Comment by mp911de** [comment]
Good catch. Feel free to submit a pull request to add this method.
