### ISSUE TITLE
ScanOptions.ScanOptionsBuilder count can be null 

### ISSUE THREAD

**Issue by ChunMengLu** [spring-projects/spring-data-redis#1994]
ScanOptions and ScanOptionsBuilder  field count is  Nullable，but ScanOptionsBuilder  count method args is not nullable.

I hope it can be optimized to avoid judgments in the business code.

**Comment by mp911de** [comment]
This is by intent. The nullability in `ScanOptions` regarding both fields models presence/absence of the actual values. If you want to set the count option, then you need to call this method with a non-null count value as we do not want to propagate unchecked values into the options object.
