### ISSUE TITLE
Lettuce uses monitoring events to monitor the offline events of the primary repository of the Redis service in sentinel mode, the time of reconfiguration of the slave repository, and the switching events of the new primary repository

### ISSUE THREAD

**Issue by niuyonggang** [spring-projects/spring-data-redis#2018]

**Comment by niuyonggang** [comment]
由于一次线上事故，aws服务故障导致redis做了failover,failover时间是15s，我们看到的现象是应用重启或者长达15分钟才恢复，所以我们想要监控哨兵的通知事件。

spring-boot-starter-data-redis : 2.2.6
lettuce-core : 5.2.2

**Comment by mp911de** [comment]
I have no idea what you're asking for.

**Comment by niuyonggang** [comment]
I mean: is there an API for communication between the spring-boot-data-redis package lettuce drive and the sentinel?

**Comment by mp911de** [comment]
Spring Data Redis can make use of Redis Sentinel via Lettuce in two ways:

1. Connecting to the master only and determine the current master upon disconnect as Lettuce auto-reconnects disconnected connections
2. Connect to masters and replicas to route commands accordingly (read-write and read-only commands) to the configured `ReadFrom` setting. Configuring `ReadFrom` enables this behavior.

**Comment by niuyonggang** [comment]
https://github.com/lettuce-io/lettuce-core/wiki/Connection-Events

Does Spring Data Redis support the use of commection-events?

**Comment by mp911de** [comment]
Spring Data Redis doesn't make use of these.

**Comment by niuyonggang** [comment]
Will there be relevant use in the future?

**Comment by niuyonggang** [comment]
why doesn't Spring Data Redis support it

**Comment by mp911de** [comment]
Because it doesn't make sense and there's nothing Spring Data Redis can get out of using connection events. Since this discussion isn't going anywhere towards something actionable, I'm closing this ticket.

**Comment by niuyonggang** [comment]
thanks
