### ISSUE TITLE
Add support for `COPY` via `RedisOperations` and `ReactiveRedisOperations`

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-redis#2040]
`COPY` is a variant of `MOVE` that retains the key in the source database/key.

See also https://redis.io/commands/copy

**Comment by ihaohong** [comment]
hi, I am haohong, I write some code to support COPY command. This is my first-time to contribute to open source project.
 I am a fish, aha. if I ignored some checklist, could you please help me to point out,  And I will continue to fix it.

Thank you~

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.
