### ISSUE TITLE
how to dertermine which redis server version supported by specific spring-data-redis release or is it forward&backward compatible

### ISSUE THREAD

**Issue by lyhistory** [spring-projects/spring-data-redis#2061]
can not find the compatibility matrix for redis server and this spring-data-redis client, I'm wondering whether it's bidirectional compatible, that I can use any client version with any version of redis server

**Comment by mp911de** [comment]
Generally speaking, Redis compatibility depends on the commands that you intend to use. Closing as per your comment.
