### ISSUE TITLE
Deserialization is not working for ENUM with Jackson2JsonRedisSerializer

### ISSUE THREAD

**Issue by Deepu978** [spring-projects/spring-data-redis#2062]
Jackson2JsonRedisSerializer is not working to  deserialize enum.

suppose i have  an enum APPLE("test").  "APPLE" is stored in redis database as a String so when retrieving it just returns string  instead of ENUM

**Comment by lpint55** [comment]
@Deepu978 I also encountered this issue. I want to ask if you've found a solution?
