### ISSUE TITLE
used redis cluster mode error，need resove

### ISSUE THREAD

**Issue by heyu19841118** [spring-projects/spring-data-redis#2067]
this project occur error when  used cluster model to connect redis group。this bug need  resolve.error message is：
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy85 cannot be cast to io.lettuce.core.api.sync.RedisCommands
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.getDedicatedRedisCommands(LettuceConnection.java:1061) ~[classes/:2.5.1]
this error occur  reason is LettuceConnection class  convert RedisClusterCommands to RedisCommands return.  class code at line 572:
private RedisCommands<byte[], byte[]> getDedicatedRedisCommands() {
        return (RedisCommands) getDedicatedConnection();
    }

**Comment by mp911de** [comment]
This issue tracker uses English and we're not able to understand your request.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
