### ISSUE TITLE
Any BoundListOperations method spend a lot of time

### ISSUE THREAD

**Issue by fujian26** [spring-projects/spring-data-redis#2068]
When server is restarted, on first call BoundListOperations method, such as size(), will spend almost 6 second, but after first call, the following call just spend some milliseconds. why ... is there some solution ??

some code:
```
    @Autowired
    private RedisTemplate redisTemplate;
...
    @RequestMapping(value = "/getCityHotCommunity", method = RequestMethod.GET, produces = "application/json;charset=UTF-8")
    public BaseData<List<Community>> getCityHotCommunity(HttpServletRequest request, HttpServletResponse response,
                                                         String cityCode, int pageIndex, int pageSize) {
...
            BoundListOperations operations = redisTemplate.boundListOps("oy");
            operations.size();
...
```

**Comment by mp911de** [comment]
`BoundListOperations` uses `LLEN` to determine the list size. Can you pin down the issue to a specific key or phase of your application (at startup, at any point in time, during high load)?

**Comment by fujian26** [comment]
> `BoundListOperations` uses `LLEN` to determine the list size. Can you pin down the issue to a specific key or phase of your application (at startup, at any point in time, during high load)?

Not just size() method but also others, like leftPush()... It happend any point in time as long as first call those methods.

RedisConnection I use the default: LettuceConnection.

Redis server and Application are run in the same computer, Mac.

Relatively complete code:
```
@CrossOrigin
@RestController
@RequestMapping("/house")
public class MCommunityController {

    @Autowired
    private RedisTemplate redisTemplate;

    @RequestMapping(value = "/getCityHotCommunity", method = RequestMethod.GET, produces = "application/json;charset=UTF-8")
    public BaseData<List<Community>> getCityHotCommunity(HttpServletRequest request, HttpServletResponse response,
                                                         String cityCode, int pageIndex, int pageSize) {
        BoundListOperations operations = redisTemplate.boundListOps("community");
        long size = operations.size(); // first call here after application started will spend a few seconds 

        ....
    }
}
```

**Comment by mp911de** [comment]
Sounds like a warm-up issue though 6 seconds is a bit long. Can you run your app with a profiler to determine which methods (except for waiting for the result) are hotspots?

**Comment by fujian26** [comment]
> Sounds like a warm-up issue though 6 seconds is a bit long. Can you run your app with a profiler to determine which methods (except for waiting for the result) are hotspots?

I can't do it right now, but I found another point before, 

"redisTemplate.getConnectionFactory().getConnection()" will spend same time when first call. So I think the reason is associated with first connection, may be create connection spend too much time, I don't known...

**Comment by mp911de** [comment]
Does the same happen if you spin up the Lettuce Client yourself? (e.g. `RedisClient.create(…).connect(…).sync().llen(…)`)

**Comment by fujian26** [comment]
> Does the same happen if you spin up the Lettuce Client yourself? (e.g. `RedisClient.create(…).connect(…).sync().llen(…)`)

I tried this just now, and it also spend almost 6 seconds.

**Comment by mp911de** [comment]
Thanks. It looks that the Lettuce client bootstrap takes quite a while on your machine. Lettuce is an external project so we cannot do there anything. Without recording the internals with a profile, the Lettuce team won't be able to diagnose anything either.
