### ISSUE TITLE
Remove the Keyspace as mandatory prefix.

### ISSUE THREAD

**Issue by ckbhatt** [spring-projects/spring-data-redis#2070]
We use Redis for storing only one type of data and keyspace prefix is not required. Can we make spring data redis implementation more flexible to honor empty keyspace and not prefix keys with class name if keyspace is explicitly set to "". Is there a way to work around this issue?

**Comment by mp911de** [comment]
Can you help us understand which functionality you're talking about? Do you mean caching or Redis Repositories?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
