### ISSUE TITLE
How do officials ensure that the APIs in spring data redis are consistent with the latest version of Jedis APIs？

### ISSUE THREAD

**Issue by startjava** [spring-projects/spring-data-redis#2075]
How do officials ensure that the APIs in spring data redis are consistent with the latest version of Jedis APIs? I'm worried that the API in spring data redis is always a step slower, and I don't know if that worry is superfluous.

**Comment by mp911de** [comment]
Spring Data Redis is built against a particular Jedis version. If Jedis changes their API in an incompatible way, then we only know about that once we've upgraded to that version. Have you experienced any issues or where does your question come from?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
