### ISSUE TITLE
Support findAll with sorting in derived query methods

### ISSUE THREAD

**Issue by Thunderforge** [spring-projects/spring-data-redis#2080]
Consider this POJO code:

```java
@RedisHash("somehash")
public class Example {

    @Id
    private String id;
    @Indexed
    private String some;
    @Indexed
    private String thing;
    @Indexed
    private Integer rank;
```

The following code would be expected to return elements sorted:

```java
@Repository
public interface ExampleRepository extends CrudRepository<Example, string> {
    List<Example> findAllOrderByRank(Integer rank);
}
```

As described in [this StackOverflow post](https://stackoverflow.com/q/54339026)) and corroborated by several users in the comments (and my own project), this does return all elements, but they are not sorted as expected. Indeed, [the table of supported keywords inside method names](https://docs.spring.io/spring-data-redis/docs/current/reference/html/#redis.repositories.queries) does not list `OrderBy` as a valid keyword.

The [section for Query By Example](https://docs.spring.io/spring-data-redis/docs/current/reference/html/#query-by-example.running) also specifically says that `findAll` with sorting is not supported.

This is important functionality that I would like to see supported in future releases.

**Comment by mp911de** [comment]
To simplify things, you're looking for sorting support through keywords/by passing in a `Sort` object into the query method. Query by Example isn't applicable in this context.

**Comment by Thunderforge** [comment]
Correct, I'm looking for sorting support through keywords (`findAllOrderByFoo`) as well as passing in a `Sort` object into the query method. 

My mistake with Query by Example; I assumed that since it called it out as an unsupported feature that there was a use case in which it was desirable.

**Comment by mp911de** [comment]
After investigating the code, sorting has never worked. We need to fix that.
