### ISSUE TITLE
ValueOperation setIFAbsent with ttl not working.

### ISSUE THREAD

**Issue by codeayra** [spring-projects/spring-data-redis#2081]
I am using RedisTemplate with LettuceConnection Factory(in spring boot) to set key in Redis with ttl , 
Key is getting Set in redis but its ttl not getting set.

when I try to set ttl using redis-cli , its getting set.

here is the code. 
`public Boolean setIfAbsent(String key, Object value, long timeout, TimeUnit unit) {
        Boolean isSuccess = Boolean.FALSE;
        String absoluteKey = generateAbsoluteKey(key);
        log.info("Setting key {} in redis..", absoluteKey);
        try {
            String sValue = objectMapper.writeValueAsString(value);
            redisTemplate.opsForValue()
                    .setIfAbsent(absoluteKey, sValue, timeout, unit);
        } catch (Exception e) {
            log.error("Error in saving value to redis cache for key: " + absoluteKey, e);
        }
        return isSuccess;
    }`

RedisConfiguration is like following

implementation group: 'org.springframework.data', name: 'spring-data-redis'

`@Bean
    public LettuceConnectionFactory lettuceConnectionFactory() {
        return new LettuceConnectionFactory(hostName, port);
    }

    @Bean
    public RedisTemplate<String, String> redisTemplate() {
        RedisTemplate<String, String> redisTemplate = new RedisTemplate<String, String>();
        redisTemplate.setConnectionFactory(lettuceConnectionFactory());
        redisTemplate.setExposeConnection(true);
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(new StringRedisSerializer());
        return redisTemplate;
    }`

There is no error on console.
I am using spring-data-redis-2.5.0-M5
redis version I have tried with 6.2 also 4.0 .

Please suggest.

**Comment by christophstrobl** [comment]
I checked `DefaultValueOperationsIntegrationTests#testSetIfAbsentWithExpiration` for `Lettuce` and everything seems to work as expected. Maybe you can provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by codeayra** [comment]
try to set key as key = 

`"a:eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyZ3EzRTN1WGNFYjZkYXd0dFQzQWRlb1YxdF85NVQtVS1aZmtLY0ZrUlpJIn0.eyJleHAiOjE2MjM0MTc4MjgsImlhdCI6MTYyMzQxNzUyOCwiYXV0aF90aW1lIjoxNjIzNDE3NTI4LCJqdGkiOiJmMTVmYTM4OS1hOTBkLTQyMzYtOTZkZi1lMmE3YTFmYTVlNDQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvaXRyb24iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiOTFlZGJkOWQtNjUxOC00NTFmLThmOWQtYTNhMGU1MTJiNGRjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoia2V5Y2xvYWstYW5ndWxhciIsIm5vbmNlIjoiYTRiMGU3ZjAtNjA1MS00MWRkLWE4NTQtMzM5YjRiMmI4ZmViIiwic2Vzc2lvbl9zdGF0ZSI6ImYwNWZjNDM1LWYwOTQtNDZiMi1hMjlkLTliZGM1NGQ2OTE2MiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo0MjAwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiYW5raXQga3VtYXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImdpdmVuX25hbWUiOiJhbmtpdCIsImZhbWlseV9uYW1lIjoia3VtYXIiLCJlbWFpbCI6ImFkbWluQGl0cm9uLmNvbSJ9.FU6dc4lLd5jm76NkDkg6v8mInNbn0MVxds2ElyblVsG_VK3Et35tOFJS72ItT8ypjC-z0qWo6pNSG5x8l1r9CK93UHjoIztuYx242HTxZOpKmGmf-O_XRuWaUPe9YUVax9sIJLxsG9frMsF2hBisoO6772tE5zUJ0qN0SiIzQN9q82u8xBjkSIGZsIjrZoLL0s1ctVg1nXo5qDWJObqtIh0vNcKsESEHAvy6wxKXBZJLrm5zn7dS5BRRpfZnTmX2JjG6dNuxwSWoJqh3Lu6wl0k2m4eBAkMCOQ2JorQ-ObdB_IjYR1bHkKOEStHp1DchSFXRxYoiASK4CnRzHQgaHQ"`

you can see the key in redis but not its ttl.

**Comment by codeayra** [comment]
I got the problem, 
What I am doing first calling setIfAbsent with ttl and its working after that I get the key update its value and calling setIfPresent without ttl and which might be clearing its ttl.

How can I update a key value without clearing its ttl ?

**Comment by christophstrobl** [comment]
I see - there's an`keepTtl` option on `Expiration` that allows to do this. But it is not present on `ValueOperations` so you'd have to call it something like the following on the template.
```java
return execute(connection -> connection.set(rawKey, rawValue, Expiration.keepTtl(), SetOption.ifPresent()), true);
```
I created #2084 for that.

**Comment by codeayra** [comment]
Got this  this error 

org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR syntax error

code is 
` public void update(String key, Object value) {
        String absoluteKey = generateAbsoluteKey(key);
        String valueString = objectMapper.writeValueAsString(value);
        try {
            redisTemplate.execute(connection -> connection
                    .set(rawKey(absoluteKey), rawValue(valueString), Expiration.keepTtl(), RedisStringCommands.SetOption
                            .ifPresent()), true);

        } catch (Exception e) {
            log.error("Error in saving value to redis cache for key: " + absoluteKey, e);
        }
    }`

**Comment by christophstrobl** [comment]
`KEEPTTL` is available as off Redis 6.
Does lettuce tell you more than just `ERR syntax error`?

**Comment by codeayra** [comment]
nothing..just this error.

**Comment by codeayra** [comment]
its working finally with redis 6. Thanks.
