### ISSUE TITLE
Throw UnsupportedOperationException for dynamic queries with unsupported keywords

### ISSUE THREAD

**Issue by Thunderforge** [spring-projects/spring-data-redis#2099]
Consider #2080, which added support for the `OrderBy` keyword in dynamic queries. For example, your repository can call `findAllOrderByBar()` and it will return all elements sorted by the `bar` field. 

Before this change, if your repository had `findAllOrderByBar()`, the method gets called and nothing is sorted. This is definitely a surprise for the user. Similarly, if the user tries to use [other keywords they might expect ](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation) (perhaps `findByAgeLessThan(int age)`, Spring Redis will return data that doesn't match the user's expectations.

I would like to suggest that for situations like this with unsupported keywords, an `UnsupportedOperationException` is thrown (or another exception if it is more appropriate). Perhaps more generally if there is anything about the method name that isn't understood (like if field `bar` doesn't exist or isn't `@Indexed`), an exception could be thrown as well.

This would save developers time debugging code that appears to be valid, but will never work.

## Current Behavior

Calling a dynamic query with an unsupported keyword does not return data that the developer expects.

## Desired behavior

Calling a dynamic query with an unsupported keyword  should throw an UnsupportedOperationException or a similarly appropriate exception.

**Comment by mp911de** [comment]
Actually, [this is already in place](https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/repository/query/RedisQueryCreator.java#L73). The missing bit in #2080 was the missing invocation of sorting.

The relationship between `@Indexed` and a derived query using such property is a bit more tricky as indexing can happen also outside of Spring Data Redis so we do not have a way to know about that. Generally, starting with tests to ensure proper usage is a good approach.

Is there anything actionable on this ticket left?

**Comment by Thunderforge** [comment]
So the issue in #2080 was that the `OrderBy` keyword was supported, but not working properly?

In that case, I may have overgeneralized the situation. If there are technical hurdles with `@Indexed`, then I do not think there is anything actionable to do with this ticket.
