### ISSUE TITLE
StreamOffset.latest() does NOT work for subscription in standalone mode

### ISSUE THREAD

**Issue by endlesscpp** [spring-projects/spring-data-redis#2126]
When I register subscription using StreamOffset.latest(), it does NOT work; however StreamOffset.fromStart works.

        String streamKey = "stream:topic";
        // create listener
        StreamMessageListenerContainer.StreamMessageListenerContainerOptions<String, ObjectRecord<String, TrackItem>> options =
                StreamMessageListenerContainer.StreamMessageListenerContainerOptions.builder()
                        .pollTimeout(Duration.ZERO) 
                        .targetType(TrackItem.class) 
                        .build();
        StreamMessageListenerContainer<String, ObjectRecord<String, TrackItem>> container =
                StreamMessageListenerContainer.create(mRedisConnectionFactory, options);

// does NOT work
        container.receive(StreamOffset.latest(streamKey),
                new StreamMessageListener(mRedisTemplate));

// this one work
container.receive(StreamOffset.fromStart(streamKey), new StreamMessageListener(mRedisTemplate));

Don't know the reason.

**Comment by mp911de** [comment]
Care to elaborate on:

> does NOT work

`latest()` translates to `$`. As per Redis' behavior, `$` only works if the stream already exists.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
