### ISSUE TITLE
`DefaultRedisScript` checks for `isModified` in a `synchronized` block that affects multi-threaded performance

### ISSUE THREAD

**Issue by qq2357509207** [spring-projects/spring-data-redis#2128]
org.springframework.data.redis.core.script.DefaultRedisScript

![Snipaste_2021-07-21_15-08-14](https://user-images.githubusercontent.com/50605346/126446414-1e7350bd-8f80-4a50-8935-3f45b1e114b1.png)
synchronized  seriously affects the performance of executing redis lua scripts
Usually, the redis lua script will not change

**Comment by mp911de** [comment]
Please refrain from pasting images into bug reports as these cannot be searched or indexed. Instead, use stable links to code such as the following one:

https://github.com/spring-projects/spring-data-redis/blob/b57a1e0376a55c42eb3f8be5cc1a6ebfe7b33afc/src/main/java/org/springframework/data/redis/core/script/DefaultRedisScript.java#L85-L93

**Comment by mp911de** [comment]
The code could be improved by limiting the `synchronized` block to the `sha1` assignment. In return, the `sha1` field can become subject to visibility issues across multiple threads which can lead to multiple computations of the SHA value but that is the flip side of best effort caching.

**Comment by rawalprafull** [comment]
@mp911de can I contribute in this to kick start my journey ? if no one is working on this.

**Comment by mp911de** [comment]
Sure, feel free.

**Comment by rawalprafull** [comment]
```
public String getSha1() {
	if (sha1 == null || scriptSource.isModified()) {
		synchronized (shaModifiedMonitor) {
			this.sha1 = DigestUtils.sha1DigestAsHex(getScriptAsString());
		}
	}
	return sha1;
}
```

`private @Nullable ScriptSource scriptSource;`  // line no. 42

@mp911de method invocation scriptSource.isModified() may produce NullPointerException. please correct me if wrong here..

**Comment by psw0946** [comment]
> The code could be improved by limiting the `synchronized` block to the `sha1` assignment. In return, the `sha1` field can become subject to visibility issues across multiple threads which can lead to multiple computations of the SHA value but that is the flip side of best effort caching.
> 
> Feel free to submit a pull request.

@mp911de 
Even when limiting the `synchronized` block to the `sha1` assignment, `scriptSource.isModified()` method is also executed in synchronized block both in `StaticScriptSource` and `ResourceScriptSource`. It would be the bottleneck in high TPS multi-thread environment.
As the reporter said, the redis lua script will not change during runtime in most cases, I think.
How about creating new ScriptSource like `UnmodifiableScriptSource` in this project for those cases?

**Comment by psw0946** [comment]
Or we can just create new `RedisScript` implementing `RedisScript<T>` or extending `DefaultRedisScript`, and override `getSha1()` method without checking `scriptSource.isModified`.
