### ISSUE TITLE
Sorted Set: Insert 4 equals object, then get it, is not the latest one

### ISSUE THREAD

**Issue by javalover123** [spring-projects/spring-data-redis#2134]
Override object's equals() and hashCode(), then insert 4 objects equals, get them all, result has 1 object, but is the first one, not the latest one, because LinkedHashSet does not override the HashMap key. Possible solution is remove first then add, but is not good.

org.springframework.data.redis.serializer.SerializationUtils#deserializeValues
```
    /**
     * Adds the specified element to this set if it is not already present.
     * More formally, adds the specified element {@code e} to this set if
     * this set contains no element {@code e2} such that
     * {@code Objects.equals(e, e2)}.
     * If this set already contains the element, the call leaves the set
     * unchanged and returns {@code false}.
     *
     * @param e element to be added to this set
     * @return {@code true} if this set did not already contain the specified
     * element
     */
    public boolean add(E e) {
        return map.put(e, PRESENT)==null;
    }
```

**Comment by mp911de** [comment]
If your value objects render to a different binary representation but in deserialized state equal (via `hashCode`/`equals`), then there's a mismatch in the contract between their serialized and deserialized state.

We expose specific method results as `Set` to comply with type contracts provided by the underlying data structure. Can you provide a bit of code so that we understand your arrangement?

**Comment by javalover123** [comment]
[HashSetNotOverride.zip](https://github.com/spring-projects/spring-data-redis/files/6882032/HashSetNotOverride.zip)

**Comment by mp911de** [comment]
The `price` property isn't considered in `equals`/`hashCode`, therefore the binary and the logical comparison can't ever be the same. Fixing both methods helps to solve the issue. Since there isn't anything left to do here, closing this ticket.
