### ISSUE TITLE
pre-warm lettuce pool

### ISSUE THREAD

**Issue by strictnerd** [spring-projects/spring-data-redis#2137]
When I start the springboot service, the redis latency is particularly high, about four times that after startup; 

Does the lettuce pool provide a way to warm up the connection pool before startup？

springboot vesion：2.3.6.RELEASE
spring-data-redis：2.3.5.RELEASE
lettuce-core：5.3.5.RELEASE

**Comment by strictnerd** [comment]
The back-end service use codis

**Comment by mp911de** [comment]
The only way is to configure a proper min-idle size. Alternatively, you might want to introduce a bean with a lifecycle hook (e.g. `@PostConstruct`) to properly warm up the infrastructure as part of the application startup.
