### ISSUE TITLE
Spring Data Redis issue with CRUDRepository

### ISSUE THREAD

**Issue by arianlopezc** [spring-projects/spring-data-redis#2146]
My team and I are using a CRUD repository with Redis to perform some operations on it. The problem is that there is an entry in Redis that gets generated as an index which stores the keys associated to the Redis entries, and this entry never removes entries that were already flushed when TTL reached 0.

Here is an example of the code we use.

```
@RedisHash("rate")
public class RateRedisEntry implements Serializable {
    @Id
    private String tenantEndpointByBlock; // A HTTP end point
    ...
}

// CRUD repository.
@Repository
public interface RateRepository extends CrudRepository<RateRedisEntry, String> {}
```

This generates the entry `rate` in Redis which is the Set object I mentioned before.

When we check the memory usage on it, it just keeps growing all the time until the memory usage reaches 100% from the available in Redis.'

  > MEMORY USAGE "rate"
  (integer) 153034
  .
  .
  > MEMORY USAGE "rate"
  (integer) 153876
  .
  .
  > MEMORY USAGE "rate"
  (integer) 163492

Is there a way to prevent this index from being created or for the values stored to be removed once the entries' TTL reaches 0?

Any assistance is appreciated.

**Comment by mp911de** [comment]
Index cleanup happens on the application side and isn't automatically performed by Redis servers. Spring Data Redis repositories maintain secondary indexes by inserting and removing data from sets. Expirations are detected by listening to keyspace events to perform index cleanup upon expiration. That requires proper keyspace settings (`CONFIG SET notify-keyspace-events KEY`) and subscribing to keyspace events through Pub/Sub.

If the application is down, then keyspace events can get lost and therefore index maintenance cannot happen.

**Comment by arianlopezc** [comment]
> Index cleanup happens on the application side and isn't automatically performed by Redis servers. Spring Data Redis repositories maintain secondary indexes by inserting and removing data from sets. Expirations are detected by listening to keyspace events to perform index cleanup upon expiration. That requires proper keyspace settings (`CONFIG SET notify-keyspace-events KEY`) and subscribing to keyspace events through Pub/Sub.
> 
> If the application is down, then keyspace events can get lost and therefore index maintenance cannot happen.

What it seems to work is actually this setting:

`@EnableRedisRepositories(enableKeyspaceEvents = EnableKeyspaceEvents.ON_STARTUP)`

We do set up our TTL for each entry but the Set/Index that is created does not flush the keys away without that option enabled.

Any other recommendations?

**Comment by mp911de** [comment]
Can you provide a reproducer?

**Comment by arianlopezc** [comment]
I found a solution to the problem but it wasn't the best for my case. Considering that this was an interesting issue to address on my end, I created an article about it.

[Lessons Learned using Spring Data Redis](https://engineering.salesforce.com/lessons-learned-using-spring-data-redis-f3121f89bff9)
