### ISSUE TITLE
The jedis connection-pool can be closed in cluster mode

### ISSUE THREAD

**Issue by chickWang** [spring-projects/spring-data-redis#2174]
It is mentioned in the official document: The parameter` isUsePooling` is applied only to single node Redis. Sentinel and Cluster modes use always connection-pooling regardless of the pooling setting.
In actual development, I found that I can use `isUsePooling: false` to turn off the cluster mode connection-pool.
My development environment is Jdk 8, spring-boot:2.5.5, spring-data-redis:2.5.5.

**Comment by mp911de** [comment]
Care to elaborate? `DefaultJedisClientConfigurationBuilder` is pre-initialized with `GenericObjectPoolConfig poolConfig = new JedisPoolConfig()` that is required for `JedisCluster`.

**Comment by chickWang** [comment]
I don't understand what you mean, can you elaborate？
Mentioned in the source code:
`/**
  * @return {@literal true} to use connection-pooling. Applies only to single node Redis. Sentinel and Cluster modes
  *         use always connection-pooling regardless of the pooling setting.
  */
boolean isUsePooling();`
If we can use `isUsePooling: false` to close the connection-pool in cluster mode, should we modify the comments in the source code to the following : 
`/**
  * @return {@literal true} to use connection-pooling. Applies to single node and Cluster modes Redis. Sentinel modes
  *         use always connection-pooling regardless of the pooling setting.
  */
boolean isUsePooling();
`
In addition, the sentinel mode is not affected by the isUsingPool parameter.It should be because of these codes:
`/**
  * Indicates the use of a connection pool.
  * <p />
  * Applies only to single node Redis. Sentinel and Cluster modes use always connection-pooling regardless of the
  * pooling setting.
  *
  * @return the use of connection pooling.
  */
public boolean getUsePool() {

// Jedis Sentinel cannot operate without a pool.
if (isRedisSentinelAware()) {
	return true;
}

return clientConfiguration.isUsePooling();
}`
If we do not modify the above-mentioned comments, should we also add a judgment similar to the sentinel mode to the cluster mode here?

**Comment by mp911de** [comment]
> If we can use isUsePooling: false to close the connection-pool in cluster mode

That isn't possible in the first place. You cannot disable pooling for Jedis Cluster, it uses pooling internally anyway. Since this ticket isn't actionable and we weren't able to find a flaw together, closing it.
