### ISSUE TITLE
The Param `isUsePooling` can be set to false in redis cluster mode

### ISSUE THREAD

**Issue by chickWang** [spring-projects/spring-data-redis#2177]
It is mentioned in the official document: The parameter `isUsePooling` is applied only to single node Redis. Sentinel and Cluster modes use always connection-pooling regardless of the pooling setting.
In actual development, I found that I can use `spring.redis.jedis.pool.enabled: false` set `isUsePooling` to false.
The test code is as follows:
```
@Test
void testRedisConfigurationWithClusterWT() {

this.contextRunner.withPropertyValues("spring.redis.cluster.nodes=127.0.0.1:27379, 127.0.0.1:27380",
				"spring.redis.jedis.pool.enabled:false","spring.redis.jedis.pool.max-active:50")
		.run((context) -> {
			JedisClientConfiguration jedisClientConfiguration = context.getBean(JedisConnectionFactory.class)
					.getClientConfiguration();
			assertThat(jedisClientConfiguration.isUsePooling()).isFalse();

		});

}
```
My development environment is Jdk 8, spring-boot:2.5.5, spring-data-redis:2.5.5.

**Comment by mp911de** [comment]
This is totally fine as `JedisClientConfiguration` is related to the Jedis client regardless of the mode of connection. `JedisClientConfiguration` is not aware of how you want to connect to Redis.

Care to elaborate on your use-case why you're querying `JedisClientConfiguration.isUsePooling()`?

**Comment by chickWang** [comment]
Do you mean that in the redis cluster mode, when `isUsePooling=false` is still using the connection pool?

**Comment by mp911de** [comment]
Exactly as `JedisConnectionFactory` handles that internally.
