### ISSUE TITLE
Lettuce Connection pooling not working

### ISSUE THREAD

**Issue by gvemula** [spring-projects/spring-data-redis#2178]
I am usng springboot 2.5.5 and spring-boot-data-redis. Using lettuce to connect to redis.

I define following connection pool size
spring.redis.lettuce.pool.max-active=25
spring.redis.lettuce.pool.max-idle=25
spring.redis.lettuce.pool.min-idle=10

In redis it is always showing only one client. Also the netstat of spring-boot server shows only one socket. I was expecting minimum 10 sockets.

I set LettuceConnectionFactory.setValidateConnection(false). No change in sockets. 

what i am doing wrong here?

**Comment by mp911de** [comment]
Apache Commons Pool does not pre-warm its pool, instead, it allocates connections with growing activity. If your workload can be performed with a single connection without requiring another one then you experience a scenario as described above.

The same applies to Jedis.
