### ISSUE TITLE
Why choose double-colons as the default separator?

### ISSUE THREAD

**Issue by scruel** [spring-projects/spring-data-redis#2191]
Redis itself use single-colon as its separator to manager the keys, so depending on which consideration, this project use double-colons as the default separator?

**Comment by mp911de** [comment]
> Redis itself use single-colon as its separator to manager the keys

Do you have a pointer that documents this? Redis doesn't have generally a convention for keys, that is why we need to come up with `$something`.

**Comment by scruel** [comment]
> 
> 
> > Redis itself use single-colon as its separator to manager the keys
> 
> Do you have a pointer that documents this? Redis doesn't have generally a convention for keys, that is why we need to come up with `$something`.

All examples on redis.io docs prefer to use single-colon rather than double-colons as the default delimiter.
See: https://redis.io/topics/indexes
