### ISSUE TITLE
RedisCommands::execute with parameters different than string

### ISSUE THREAD

**Issue by Anitka** [spring-projects/spring-data-redis#2194]
Hi!
As I couldn't find "wait" command implemented, I've tried to execute it directly using execute() method from RedisCommands interface implemented in LettuceConnection class. 
However, I didn't succeed when parameters are different than strings. I tried some commands with strings (like "EXISTS") and it worked fine. But when I tried to pass an integer or a long to "WAIT" or "EXPIRE" it failed with an error: "ERR value is not an integer or out of range" which is strange as the second method doesn't even require integer.
This is how I invoke it:
```
RedisConnection connection = ...;
byte[] numReplicas = Ints.toByteArray(2);
byte[] timeout = Longs.toByteArray(5);
byte[] key = Strings.toByteArray("somekey");
connection.execute("EXISTS", key);  // works fine
connection.execute("WAIT", numReplicas, timeout); // throws exception
connection.execute("EXPIRE", key, timeout);  // throws exception
```
What's wrong here? Could you please guide me? Thanks!

**Comment by Anitka** [comment]
Could you comment how this method should be invoked to work with parameters different than strings?

**Comment by mp911de** [comment]
Connections use binary data types (byte array, `ByteBuffer`) to exchange data between Redis and the application as Redis keys and values are binary and not guaranteed to be a proper string. However, some Redis commands require a textual representation of the parameter and that is especially true when passing on numbers to commands. `Ints.toByteArray(…)` returns a big-endian representation of value in a 4-element byte array and not a textual representation of the number.

`byte[] numReplicas = "2".getBytes()` is what you're looking for.
