### ISSUE TITLE
RedisOperations::slaveOf deprecated

### ISSUE THREAD

**Issue by toddmerrill** [spring-projects/spring-data-redis#2195]
In the Redis documentation I see 'slaveof' is deprecated for 'replicaof': [https://redis.io/commands/slaveOf](url) We should deprecate the 'slaveOf' and 'slaveOfNoOne' methods in RedisOperations and add new 'replicaOf' and 'replicaOfNoOne' methods.

**Comment by mp911de** [comment]
None of the drivers (Jedis, Lettuce) support this command. Can you file tickets there? Once we have the pre-requisites in place, we can continue here.

**Comment by christophstrobl** [comment]
Merged to _3.0.x_ via #2276.
