### ISSUE TITLE
RedisCommands::execute with int and long

### ISSUE THREAD

**Issue by Anitka** [spring-projects/spring-data-redis#2197]
Regarding my previous issue #2194. I've tried to invoke the method the way you suggested
```
RedisConnection redisConnection = ...;
byte[] replicas = "1".getBytes();
byte[] timeout = "100".getBytes();
connection.execute("WAIT", replicas, timeout);
```
And now the error is 
org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.UnsupportedOperationException: io.lettuce.core.output.ByteArrayOutput does not support set(long)

What's wrong this time?

**Comment by mp911de** [comment]
The general `execute` mechanism doesn't cover all commands and all invariants of Redis replies. Please either use the native connection or call `execute` with `new IntegerOutput<>(…)` to consume the response correctly.

**Comment by Anitka** [comment]
I used native connection after all.

**Comment by KiitosKaloista** [comment]
Using `AbstractRedisAsyncCommands` seems to get you there with lettuce, here's a sample with cluster setup:

```
RedisClusterConnection = redisTemplate.getConnectionFactory().getClusterConnection();
RedisAdvancedClusterAsyncCommandsImpl<String, String> conn = (RedisAdvancedClusterAsyncCommandsImpl<String, String>) clusterConnection.getNativeConnection();
StatefulConnection<String, String> connection = conn.getConnection();
RedisCodec<String, String> codec = StringCodec.UTF8;
AbstractRedisAsyncCommands<String, String> commands = new AbstractRedisAsyncCommands<>(connection, codec) {};
RedisFuture<Long> redisFuture =  commands.waitForReplication(1, 100L);
Long output = redisFuture.get();
```
