### ISSUE TITLE
KeyEvent Event Subscriptions are broken on Redis restart, leading to dirty indexes

### ISSUE THREAD

**Issue by bergerst** [spring-projects/spring-data-redis#2200]
When the Redis server is restarted while an application with spring-data-redis is running, Lettuce or Jedis (depending on the library used) will resubscribe to the pattern `__keyevent@*__:expired`.

The problem with this is that the subscription will be broken because the config value of `notify-keyspace-event` set by `KeyspaceEventMessageListener.init()` is lost. Therefore the Redis server will never publish any keyspace events again.

At that point, no more expiration events will be received, so the phantoms and, more importantly, the indexes will never be cleaned up.

If that happens, #1145 will be triggered because the indexed data is used to answer the queries.

## Steps to reproduce

1. Start Redis server
2. Start your application with `@EnableRedisRepositories(enableKeyspaceEvents = EnableKeyspaceEvents.ON_STARTUP)`
3. Restart the Redis server
4. Trigger something in your application which writes a `@RedisHash` object with a TTL into the database
5. Wait until the TTL reaches 0
6. Phantom object still exists because MappingExpirationListener was never called

## Workaround

Set `notify-keyspace-events Ex` either in the redis.conf file or via `--notify-keyspace-events Ex` in the command line arguments.

**Comment by mp911de** [comment]
Setting `notify-keyspace-event` is more of a get-quickly-started feature. It should not be used in production and many Redis Cloud services disallow using the `CONFIG` command. If you run in production, please configure your server externally instead of using Spring Data Redis to configure the server. Leaving `@EnableRedisRepositories(keyspaceNotificationsConfigParameter=…)` empty will disable the config mechanism in Spring Data Redis.

**Comment by bergerst** [comment]
That should be included in the documentation, then. Additionally, I would wish for a logger.warn() call [here](https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/listener/KeyspaceEventMessageListener.java#L92) if no `notify-keyspace-event` config is set, informing them that they should set it themselves.

The only mention of `notify-keyspace-events` is your point that the `CONFIG` command may not work and you should disable it, but nothing about any recommendations for setting the config property directly in your Redis server.
