### ISSUE TITLE
Update `RedisOperations#convertAndSend` to return number of subscribers

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-data-redis#2209]
Currently, `RedisOperations#convertAndSend` is `void` event though the underlying `RedisPubSubCommands#publish` returns a `Long` that represents the number of subscribers receiving the published message (see https://redis.io/commands/publish).

The information about the number of subscribers can be useful in some scenarios, and is also returned by the reactive counterpart in `ReactiveRedisOperations#convertAndSend`.

Digging through the history of `RedisOperations`, it seems that `#convertAndSend` used to return `Long` for a brief period of time in 2013: it was introduced in b35f6a3c and reverted in d46bee7e.

I understand that adding return value would be a breaking change, but the impact doesn't seem to be too big (?). I'm willing to submit a PR to address this, if the change is welcome.

**Comment by mp911de** [comment]
Thanks for the report. Seems the method signature was reverted to keep binary compatibility. We could consider the change for the next major revision of Spring Data Redis.
