### ISSUE TITLE
Unable to get an error while using opsForHash().get() command

### ISSUE THREAD

**Issue by MariaNosareva** [spring-projects/spring-data-redis#2210]
Hi,
I came across some strange behavior while working with `ReactiveHashOperations`: it seems that there is no error propagation in the case of getting value from hash by only one key (`.get(key)` method). 

https://github.com/spring-projects/spring-data-redis/blob/bae2eae4f910cce1fcdd60da0e411e0b44701a5d/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceReactiveHashCommands.java#L109-L110

For example, if the service has trouble reconnecting to Redis, the endpoint user of that method will never know if any problems exist. But in the case of using `.multiGet()` (uses the same method under the hood - `hMGet()`) there is no such issue, all errors are delivered well.

Is there any chance of changing this behavior?

Thanks!

**Comment by mp911de** [comment]
Thanks for reporting the issue. It is indeed a regression in which the empty response should return a collection with an empty element.
