### ISSUE TITLE
Add username support for Sentinel Configuration

### ISSUE THREAD

**Issue by vikasgarghb** [spring-projects/spring-data-redis#2218]
In order to use authentication on sentinel using ACLs there needs to be support added on sentinel configuration for Lettuce. Similar to what has been done on spring-boot: https://github.com/spring-projects/spring-boot/commit/36382e599c2a78f5b2ba7b91b453fe346ddac0c5

**Comment by mourezwell** [comment]
is there a plan to expand this enhancement to spring-boot, in deed org.springframework.boot.autoconfigure.data.redis.RedisProperties does not support sentinel username yet, 
so does org.springframework.boot.autoconfigure.data.redis.RedisConnectionConfiguration can't set SentinelUsernma you've just added here ?
