### ISSUE TITLE
Sentinel Configuartion Master Failover

### ISSUE THREAD

**Issue by abhisheksurve45** [spring-projects/spring-data-redis#2232]
Hi Team,

While creating an object of RedisSentinelConfiguration for JedisConnectionFactory, we expected to set the sentinel list, database as well as master.

Is it really required to set the master, because lets say I've a setup wherein I've 1 Master, 2 Slaves and 3 Sentinel with quorum as 2. Now lets say in the spring app I confugure master as masterA, and due to some reason it goes down, sentinel itself will re-elect new master slaveB and hopefully spring-data-redis would fallback to newly elected master (slaveB).

In the same timeframe if the spring application is restarted, since it has configured the old master (which is slave now), not sure what would happen here.

Working with spring-data-redis 2.5.5, jedis 3.6.3 and redis 6.2.3

**Comment by mp911de** [comment]
I'm not sure I understand your request. The `master` specified at `RedisSentinelConfiguration` points to the symbolic name of the HA group that participates in master/replica failover controlled by sentinels. It is not possible to swap to a different master name as we do not get any indication for when to switch master groups.

**Comment by mp911de** [comment]
Both Jedis and Lettuce perform (re)connects to the currently active master by querying Sentinel servers to obtain the currently active master.

**Comment by abhisheksurve45** [comment]
Cool. Thanks for clarification @mp911de
