### ISSUE TITLE
strange BIG KEY type SET for each Repository

### ISSUE THREAD

**Issue by normenczepa0815** [spring-projects/spring-data-redis#2244]
Hi Guys, we are struggling with a strange **BIG KEY** in our Redis, looks like an useless overhead to the existing data structure

we implemented five Repository Objects like this, e.g.
```
import org.springframework.data.redis.core.RedisKeyValueAdapter;
import org.springframework.data.redis.repository.configuration.EnableRedisRepositories;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

@Repository
@EnableRedisRepositories(shadowCopy = RedisKeyValueAdapter.ShadowCopy.OFF)
public interface ClientSessionRepository extends CrudRepository<ClientSession, String> {

}
```
in our redis data base, everything looks fine for the HASH keys, millions of hashes with around 250 bytes per key
```
10.xxx.xxx.xx:6379> type "ClientSession:671a97cf-a46b-4cc6-8290-xxx"
hash
10.xxx.xxx.xx:6379> memory usage  "ClientSession:671a97cf-a46b-4cc6-8290-xxx"
286
```
**but now the big surprise came to us**, we found exactly five big keys in our redis, which are type SET and **which constantly growing**! never saw any remove on the members
```
10.xxx.xxx.xx:6379> type "ClientSession"
set
10.xxx.xxx.xx:6379> memory usage "ClientSession"
755718552
10.xxx.xxx.xx:6379> smembers "ClientSession"
1) 671a97cf-a46b-4cc6-8290-xxx
2) c7718b77-1a59-4326-898e-xxx
3) 1020cc6a-a2bc-4fb3-9aa4-xxx
4) etc..
10.xxx.xxx.xx:6379> memory usage "IdentToken"
7372887704
```
the members of this SET "ClientSession" are just the hashes from the HASH keys, the size of this one SET is for "ClientSession" about 0.755 GB but we found the largest SET "IdentToken" with a size of  7.372 GB!!! (these are short living 10min tokens)

this is absolutly critical size for us, its a memory usage with no clear purpose or use, billions of string collections, since the first beginning of their ceation, but all these hash strings in this SET that you can map to real HASH keys are sooner or later expired! but there is no process that removes them out of this SET, we only see SADD on this SET, probably until our memory ends up full on production, when deleting this BIG SET KEY it comes again and grows :-(

so the HOT QUESTION is now: is this an issue or a feature when using **org.springframework.data** with **org.springframework.stereotype.Repository** ? and when yes, is there a flag to disabled it?

thank you for checking this and supporting us

**Comment by mp911de** [comment]
I'm not sure I follow. Spring Data Redis is doing what you tell the API to do. If there's a hash with a bigger size, then something has added that hash. Please note that using Spring Data Redis repositories comes has a notable performance and storage cost associated. Spring Data Redis needs to maintain secondary indexes to make the Repository pattern work.

Also, Redis does not have the possibility to expire individual elements within a data structure. Disabling phantom copies can leave secondary indexes in place without a chance of cleaning these up. Also, your application must be running to listen to expiration events in order to clean up indexes.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by normenczepa0815** [comment]
indirectly the answer is given with your feedback, thx @mp911de 😃 

what we are doing now with this issue is a simple practical approach, that we are "UNLINK" these dispensable five big KEYS of TYPE SET which grow in one day to a GigaByte Size in a nightly job, sounds funny but it helps and keeps our memory growing rate low AND the most important thing, it has no side effects in the application and especially to our customers 👍

**Comment by mp911de** [comment]
Thanks for the details. Since this ticket isn't actionable for us, I'm closing it. If you find something that indicates a desire for change, let us know and we're happy to reopen the ticket.

**Comment by conet** [comment]
I find it bad practice to offer spring data redis repository support without at lease a big warning in case TTL is used while the corresponding mechanism is setup to be able to properly cleanup those sets. May I ask why does spring redis need to maintain a separate set for the `@Id` field (the redis key)? I understand secondary idexes but for has keys it seems like an overkill.
