### ISSUE TITLE
When jedisConnectionFactory is deployed in cluster mode, if the Redis service is unavailable when the Redis service is started, the connection pool cannot be restored even if the Redis service is restored.

### ISSUE THREAD

**Issue by lvyuqi** [spring-projects/spring-data-redis#2252]
When `jedisConnectionFactory` is deployed in cluster mode, if the Redis service is unavailable when the Redis service is started, the connection pool cannot be restored even if the Redis service is restored.

I think the problem lies in this part of the code:

```java
private void initializeSlotsCache(Set<HostAndPort> startNodes, JedisClientConfig clientConfig) {
  ArrayList<HostAndPort> startNodeList = new ArrayList<>(startNodes);
  Collections.shuffle(startNodeList);

  for (HostAndPort hostAndPort : startNodeList) {
    try (Jedis jedis = new Jedis(hostAndPort, clientConfig)) {
      cache.discoverClusterNodesAndSlots(jedis);
      return;
    } catch (JedisConnectionException e) {
      // try next nodes
    }
  }
}
```

**Comment by christophstrobl** [comment]
The `JedisClusterConnectionHandler` is part of the [Jedis](https://github.com/redis/jedis) Redis client. The issue seems to be related to redis/jedis#2550.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
