### ISSUE TITLE
Support for `scan` in `RedisTemplate`

### ISSUE THREAD

**Issue by LeonhardtC** [spring-projects/spring-data-redis#2260]
Recently I use redis scan in my project. But I found that I can't use it in RedisTemplate directly and use RedisCallback instead. It was implemented in ReactiveRedisTemplate, is there any issue when implement it in RedisTemplate? If not, I would like to implement it.

**Comment by mp911de** [comment]
Thanks for reaching out. I think that mostly no one asked for this feature yet. A specialty with `SCAN` is that the underlying cursor requires a connection to work on so the connection must not be closed/released after the command (see `DefaultSetOperations.scan(…)` for example). Other than that, feel free to submit a pull request.
