### ISSUE TITLE
`StaticMasterReplicaConnectionProvider` throws exception on `getConnectionAsync`

### ISSUE THREAD

**Issue by cfredri4** [spring-projects/spring-data-redis#2296]
Return statement is missing?

https://github.com/spring-projects/spring-data-redis/blob/fea6e7842b505d8eb6d3c16203221804557c5063/src/main/java/org/springframework/data/redis/connection/lettuce/StaticMasterReplicaConnectionProvider.java#L93

**Comment by mp911de** [comment]
Good catch, that's fixed now.
