### ISSUE TITLE
after the method LettuceConnectionFactory.afterPropertiesSet() is called, 'destroyed' property not set to false

### ISSUE THREAD

**Issue by peachlin** [spring-projects/spring-data-redis#2301]
when i call LettuceConnectionFactory.destroy() then LettuceConnectionFactory.afterPropertiesSet(),'destroyed' is true, i got assertInitialized() failed and IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore.
  'destroy' property should be reset to false when LettuceConnectionFactory.afterPropertiesSet() is called

**Comment by mp911de** [comment]
The combination of `InitializingBean` and `DisposableBean` isn't meant to start over a disposed instance, that is calling `afterPropertiesSet` after `destroy`. Care to elaborate on what you want to achieve and why you're disposing a bean and calling `afterPropertiesSet` afterwards?

**Comment by peachlin** [comment]
> 
because redis address may changes,so i use destroy() and afterPropertiesSet() to dynamically change the redis host,this is my example code:
`    @Bean
    public LettuceConnectionFactory lettuceConnectionFactory() {
        return new LettuceConnectionFactory(new RedisStandaloneConfiguration("localhost", 6379));
    }

    public void changeRedisAddress(String newAddress) {
        LettuceConnectionFactory lettuceConnectionFactory = applicationContext.getBean(LettuceConnectionFactory.class);
        lettuceConnectionFactory.destroy();
        lettuceConnectionFactory.getStandaloneConfiguration().setHostName(newAddress);
        lettuceConnectionFactory.afterPropertiesSet();
    }`

**Comment by mp911de** [comment]
If the hostname changes, then you need to configure a new bean. Lettuce is able to refresh addresses from a given DNS name but changing the hostname isn't supported.
