### ISSUE TITLE
Spring Redis Does Not Delete the Stream Entries

### ISSUE THREAD

**Issue by SidathWeerasinghe** [spring-projects/spring-data-redis#2302]
I'm using the Redis Template and I want to delete the entries of the stream after processing it. I used the below code but it didn't delete from the Redis Streams.

`redisTemplate.opsForStream().delete("my-stream-key",record.getId().getValue());`

**Comment by SidathWeerasinghe** [comment]
Here is my code:- 

```

@Service
@Slf4j
@RequiredArgsConstructor
public class MyConsumer implements StreamListener<String, ObjectRecord<String, MyObject>> {

	@Autowired
	private ReactiveRedisTemplate<String, String> redisTemplate;

	@Override
	@SneakyThrows
	public void onMessage(ObjectRecord<String, MyObject> record) {

        log.info(InetAddress.getLocalHost().getHostName() + " - consumed :" + record.getValue());

		System.out.println(record.getId().getValue());

		this.redisTemplate.opsForStream().delete("my-stream-key",record.getId().getValue());
    }
}

```

**Comment by ShaneLee** [comment]
Hi, 

I believe you're just missing the .subscribe()

```
this.redisTemplate.opsForStream().delete("my-stream-key",record.getId().getValue()).subscribe();
```

https://projectreactor.io/docs/core/release/reference/#_from_imperative_to_reactive_programming

Also, you might be better using a consumer group with Redis streams than deleting the message for each read. This way you can scale your application to multiple consumers if required.

**Comment by SidathWeerasinghe** [comment]
@ShaneLee, 
Thank you so much for pointing out the issue. After putting the subscribe() it worked as expected.
