### ISSUE TITLE
Avoid interrupt initialization of application if Redis is down

### ISSUE THREAD

**Issue by frolando** [spring-projects/spring-data-redis#2306]
JVM 1.8
Sprnig data Redis version: 2.3.4

There is a way to avoid application crashing if Redis is down?
This is my configuration class

```
import org.springframework.boot.autoconfigure.data.redis.RedisProperties;
import org.springframework.cache.Cache;
import org.springframework.cache.annotation.CachingConfigurerSupport;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.cache.interceptor.CacheErrorHandler;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.data.redis.cache.RedisCacheConfiguration;
import org.springframework.data.redis.cache.RedisCacheManager;
import org.springframework.data.redis.connection.RedisPassword;
import org.springframework.data.redis.connection.RedisSentinelConfiguration;
import org.springframework.data.redis.connection.lettuce.LettuceClientConfiguration;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.serializer.JdkSerializationRedisSerializer;
import org.springframework.data.redis.serializer.RedisSerializationContext;
import java.time.Duration;

@Profile("!test")
@RequiredArgsConstructor
@Configuration
@EnableCaching(proxyTargetClass=true)
@Slf4j
public class CacheDataCaptureConfig extends CachingConfigurerSupport {
```

	private final RedisProperties redisProps;

	@Bean
	protected LettuceConnectionFactory redisConnectionFactory() {
		RedisSentinelConfiguration sentinelConfig = new RedisSentinelConfiguration().master(redisProps.getSentinel().getMaster());
		redisProps.getSentinel().getNodes().forEach(s -> {
			String[] array = s.split(":");
			sentinelConfig.sentinel(array[0], Integer.valueOf(array[1]));
		});
		sentinelConfig.setPassword(RedisPassword.of(redisProps.getPassword()));
		return new LettuceConnectionFactory(sentinelConfig, LettuceClientConfiguration.defaultConfiguration());
	}

	@Bean
	public RedisTemplate<String, String> redisTemplate() {
		RedisTemplate<String, String> redisTemplate = new RedisTemplate<>();
		redisTemplate.setConnectionFactory(redisConnectionFactory());
		redisTemplate.afterPropertiesSet();
		redisTemplate.setDefaultSerializer(new GenericJackson2JsonRedisSerializer());

		return redisTemplate;
	}

	@Bean
	public RedisCacheManager redisCacheManager(LettuceConnectionFactory lettuceConnectionFactory) {
		RedisCacheManager redisCacheManager = RedisCacheManager.RedisCacheManagerBuilder.fromConnectionFactory(lettuceConnectionFactory)
				.build();
		redisCacheManager.setTransactionAware(false);
		return redisCacheManager;
	}

	@Override
	public CacheErrorHandler errorHandler(){
		return new CacheErrorHandler() {
			@Override
			public void handleCacheGetError(RuntimeException exception, Cache cache, Object key) {
				log.info("Failure getting from cache: " + cache.getName() + ", exception: " + exception.toString());
			}

			@Override
			public void handleCachePutError(RuntimeException exception, Cache cache, Object key, Object value) {
				log.info("Failure putting into cache: " + cache.getName() + ", exception: " + exception.toString());
			}

			@Override
			public void handleCacheEvictError(RuntimeException exception, Cache cache, Object key) {
				log.info("Failure evicting from cache: " + cache.getName() + ", exception: " + exception.toString());
			}

			@Override
			public void handleCacheClearError(RuntimeException exception, Cache cache) {
				log.info("Failure clearing cache: " + cache.getName() + ", exception: " + exception.toString());
			}
		};
	}

}
`

**Comment by mp911de** [comment]
What do you mean with "avoid application crashing if Redis is down"? Do you see any errors? If so, please provide a stack trace.

**Comment by frolando** [comment]
My application don't start and execute any scheduled process. The only thing that is logging is the RedisException

[logs-from-featurespace-data-capture-in-featurespace-data-capture-54b47f56db-4fn5f.txt](https://github.com/spring-projects/spring-data-redis/files/8513438/logs-from-featurespace-data-capture-in-featurespace-data-capture-54b47f56db-4fn5f.txt)

**Comment by mp911de** [comment]
According to the log, the application has been started up properly. It's just a thread or worker in your code that tries to connect to Redis, so all is well here. If Redis is required in your code to run tasks, then there's nothing we can do on the Spring side.

**Comment by frolando** [comment]
You're right man, I was reading the exception and I though that the scheduler didn't ran due Redis but was due a wrong try catch. Sorry for this missunderstand.
Regards
