### ISSUE TITLE
Handle io.lettuce.core.RedisReadOnlyException when network is partitioned 

### ISSUE THREAD

**Issue by mattiasvendler** [spring-projects/spring-data-redis#2317]
I have a situation where I use sentinel to get current redis master from sentinel. My setup is one redis master and three slaves and three sentinel nodes. This works fine in most situations but I have found that if I get a network split where the current master and the sentinel node that is configured first in the list of sentinel nodes are isolated from the other nodes, the other two sentinel nodes are doing a reelection to a new master, as intended.

My problem is that when the isolated previous master is accessing the common network again  and is reconfigured to slave, my application is never notified that a new master is elected and continues to write to a slave since it still thinks it is writing to a master, ending up in getting "Error in execution; nested exception is io.lettuce.core.RedisReadOnlyException: READONLY You can't write against a read only slave."

I do not know if this is a redis problem or framework problem. Should redis when it is reconfigured from master to save terminate the connection like it is done in normal circumstances when a new master is elected or should the framework handle exceptions and query for current master?

One more interesting aspect of this is if the sentinel node configured first in the sentinel node list continues to be isolated, the behavior continues even if the application accessing redis is restarted. 

Is there any mechanism to handle this situation or is this a bug or enhancement to the framework?

**Comment by mp911de** [comment]
`RedisReadOnlyException` is thrown when Redis has reconfigured its cluster but Lettuce hasn't upgraded the topology yet. Depending on your configuration, you can react in different ways. Can you provide your configuration properties (if using Spring Boot) or the code that you use to configure `LettuceConnectionFactory`?

Generally, it is the Lettuce driver that maintains the topology configuration and Spring Data Redis uses the driver.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
