### ISSUE TITLE
Provide read/write customization hooks for `GenericJackson2JsonRedisSerializer`

### ISSUE THREAD

**Issue by ashraf-revo** [spring-projects/spring-data-redis#2322]
ObjectMapper provide `writerWithView` method for controlling which property to be serialize this make us able to adjust and make sure which properties written to the cache server
for example 

    public class User {
        @JsonView(Views.Basic.class)
        public int id;
        @JsonView(Views.Basic.class)
        public String name;
        @JsonView(Views.Detailed.class)
        public String email;
        @JsonView(Views.Detailed.class)
        public String mobile;
    }

    public class Views {
        public static class Basic {
        }
        public static class Detailed {
        }
        public static class ViewBasic extends Basic{
        }
        public static class ViewDetailed extends ViewBasic , Detailed {
        }
    }

so if we want to cache only `id,name` we only pass `ViewBasic` to the `WriterView`

for example 
    
    objectMapper.writerWithView(Views.ViewBasic.class).writeValueAsBytes(user)

if we need basic+`email,mobile` we should pass `ViewDetailed` to the `WriterView`

#### easy fix 
we could override `GenericJackson2JsonRedisSerializer.serialize`
with this code 

        @Override
        public byte[] serialize(Object source) throws SerializationException {
            if (source == null) {
                return EMPTY_ARRAY;
            }
            try {
                if (source instanceof CacheView) {
                    CacheView cacheView = (CacheView) source;
                    return cachingObjectMapper.writerWithView(cacheView.getCacheView()).writeValueAsBytes(source);
                } else {
                    return cachingObjectMapper.writeValueAsBytes(source);
                }
            } catch (JsonProcessingException e) {
                throw new SerializationException("Could not write JSON: " + e.getMessage(), e);
            }
        }
-------------------------------------------------------------------------------------------------------------------

        import com.fasterxml.jackson.annotation.JsonIgnore;

        public interface CacheView {
            @JsonIgnore
            Class<?> getCacheView();
        }
--------------------------------------------------------------------------------------------------------------------
    public class User implements Serializable, CacheView{
        @JsonView(Views.Basic.class)
        public int id;
        @JsonView(Views.Basic.class)
        public String name;
        @JsonView(Views.Detailed.class)
        public String email;
        @JsonView(Views.Detailed.class)
        public String mobile;

        private Class<?> cacheView;

    }

**Comment by mp911de** [comment]
Right now, the contextual scope is a bit unclear. `ObjectWriter` instances can be obtained through various means. An approach could be providing reading- and writing functions (something along the lines of `BiFunction<Object, ObjectMapper, byte[]>`). 

For the time being, subclassing and implementing the detail in a subclass would be the best workaround.

**Comment by ashraf-revo** [comment]
hi @mp911de thanks for you response
the problem not with passing `ObjectWriter` its about passing `writerWithView` value that will differ every time to control which property serialize to the cache server

**Comment by mp911de** [comment]
Related ticket: FasterXML/jackson-databind#3506 to enable `ObjectMapper` reuse.

**Comment by ashraf-revo** [comment]
hi @mp911de thank you for this big effort in implementing this task 
i think we not need the `read customization` we care alot about the `write customization` because the data already written to the cache server with the `write customization` and the `GenericJackson2JsonRedisSerializer` will fetch all the data from the cache server that already written  with `write customization` 
we care about the the `write customization` because we can have control on which property should be written to the server , fix `jackson infinite recursion (stackoverflowerror)`  , `only cache data that not having security issue`
