### ISSUE TITLE
Add getter method(getMapper()) to Serializer class that uses ObjectMapper

### ISSUE THREAD

**Issue by doljae** [spring-projects/spring-data-redis#2342]
## Description

After creating the `XXXSerializer` class, I suggest to add a getter method that can access the `ObjectMapper` to adjust the configurations.

If `ObjectMapper` is not specified in the current Serializer class constructor, the `ObjectMapper` that has been set internally by default is used.

In this state, if the user wants to make minor modifications to the `ObjectMapper`, since it cannot be accessed, **it is inconvenient to create an `ObjectMapper` with new settings and then create a new Serializer.**

And I know that `DefaultTyping` of `ObjectMapper` of `GenericJackson2JsonRedisSerializer` has been changed from `DefaultTyping.NON_FINAL` to `EVERYTHING` since version 2.7.0 due to the issue & PR below.
- https://github.com/spring-projects/spring-data-redis/issues/1566
- https://github.com/spring-projects/spring-data-redis/commit/93c25b0608173fafaddb485c539b84ab4db5801d

If there is a method that can access the `ObjectMapper`, it has the advantage of being able to flexibly change only the necessary parts of the default setting even after creating the Serializer.

#### Without getter()
```java
// always make new ObjectMapper when add Modules or adjust configurations
final ObjectMapper mapper = new ObjectMapper()
    .registerModule(new ParameterNamesModule(JsonCreator.Mode.DEFAULT))
    .registerModule(new Jdk8Module())
    .registerModule(new JavaTimeModule())
    .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
    .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

// duplicated -> same as default ObjectMapper configurations, 
mapper.activateDefaultTyping(mapper.getPolymorphicTypeValidator(),
                             DefaultTyping.EVERYTHING,
                             As.PROPERTY);

return new GenericJackson2JsonRedisSerializer(mapper);
```

#### If a getter() method is provided for the ObjectMapper, it can be used flexibly in the same way as the test code below.
``` java
@Test
void genericJackson2JsonRedisSerializerCanCustomizeObjectMapperAfterCreated() {

    GenericJackson2JsonRedisSerializer serializer = new GenericJackson2JsonRedisSerializer();

    serializer.getMapper() // add getter method for accessing ObjectMapper in Serializer
              .registerModule(new JavaTimeModule()) // just add module with default ObjectMapper
	      .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false) // adjust configurations
	      .configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false);
 
    ObjectWithOffsetDateTime source = new ObjectWithOffsetDateTime(1L, "doljae", OffsetDateTime.now());

    assertThat(serializer.deserialize(serializer.serialize(source))).isEqualTo(source);
}
```

### Additional info

Regarding this, after folking the repository, I've already done some work targeting the `GenericJackson2JsonRedisSerializer`.
- https://github.com/doljae/spring-data-redis/commit/9422a2653197e16fcc57917a81ce045fe68488be

**Comment by doljae** [comment]
@mp911de
It's been about two weeks since you posted the issue, so I'm curious about your opinion.

**Comment by mp911de** [comment]
We do not want to expose the `ObjectMapper` from the serializer because that is a potential source for bugs and it leaks internal implementation details. Instead, please configure multiple serializers or create the serializer with a given `ObjectMapper`.
