### ISSUE TITLE
Snyk Issue

### ISSUE THREAD

**Issue by harshagarwal00** [spring-projects/spring-data-redis#2344]
Snyk Issue needs to be fixed:
https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-1042268

**Comment by mp911de** [comment]
Spring Data Redis doesn't depend directly on Netty. See https://github.com/lettuce-io/lettuce-core/issues/1845 for further details.

**Comment by harshagarwal00** [comment]
Thanks @mp911de  for quick revert this helped me a lot :)
