### ISSUE TITLE
Add support for `ZRANGESTORE`

### ISSUE THREAD

**Issue by pratham1002** [spring-projects/spring-data-redis#2345]
I wanted to use the [ZRANGESTORE](https://redis.io/commands/zrangestore/) command along with the `BYSCORE` option but seems like there is no corresponding method for it in `RedisTemplate.opsForZSet()`. 

Both [Jedis](https://github.com/redis/jedis/issues/2626) and [Lettuce](https://github.com/lettuce-io/lettuce-core/issues/1506) support this command.

Can it be added to `spring-data-redis` too?

**Comment by mp911de** [comment]
Lettuce does not support by-rank comparison: https://github.com/lettuce-io/lettuce-core/issues/2202
