### ISSUE TITLE
RedisClusterConfiguration  not support IPv6 clusterNodes

### ISSUE THREAD

**Issue by fufk2022** [spring-projects/spring-data-redis#2360]
excuse me     
i find  org.springframework.data.redis.connection.RedisClusterConfiguration not support  ipv6 .

for example  Configuration yml file:
- ![捕获](https://user-images.githubusercontent.com/109076275/178250601-631e2087-bbef-41f1-803a-408c3224ce36.PNG)

but get the ipv error  such as:

![捕获](https://user-images.githubusercontent.com/109076275/178251325-9ec6b4cf-16fe-46ff-935b-67851c86577c.PNG)

the ipv6 fe80::a00:27ff:fe4b:ee48/6379  split   fe80:  and   a00:27ff:fe4b:ee48/6379

how to  solve?

**Comment by mp911de** [comment]
Please use hostnames for the time being.

**Comment by jxblum** [comment]
@fufk2022 - I'm curious how you arrived at the format for the host(s) and port(s) declared in your YAML configuration file when configuring Redis (cluster) nodes located with an IPv6 addresses?

For instance, in your `application.yaml` (?) configuration file shown above, for the `spring.redis.cluster.nodes` property, you declared:


```
fe80::a00:27ff:fe4b:ee48/6379,...
```

> NOTE: Just singling out 1 Redis server node here...

Where host is `fe80::a00:27ff:fe4b:ee48` and port is `6379` separated by the `/`. How did you come up with the host/port separator of `/`?

I did not find any specification of the host & port format separated by a `/` when declared in configuration in any of our documentation; not in Spring Data Redis docs [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:connectors) or [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#cluster), nor in Spring Boot's documentation, [here](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.yaml) or [here](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.nosql.redis.connecting).

Though the `spring.redis.cluster.nodes` property is specific to Spring Data Redis, Spring Boot also [declares](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties) (search for "_spring.data.redis_")  the `spring.data.redis.cluster.nodes` property as a comma-separated list of "host:port" pairs, that is where the `host` and `port` are separated by `:`.

Anyway, after digging through the SD Redis source code, starting with the `RedisClusterConfiguration` class you referenced above (and specifically, [this source](https://github.com/spring-projects/spring-data-redis/blob/3.0.1/src/main/java/org/springframework/data/redis/connection/RedisClusterConfiguration.java#L78-L104)), after reading the value of the `spring.redis.cluster.nodes` property ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.1/src/main/java/org/springframework/data/redis/connection/RedisClusterConfiguration.java#L96)), the class calls the [`appendClusterNodes(..)`](https://github.com/spring-projects/spring-data-redis/blob/2c9e0fb2173ac031fce9cf062f7eef280c9ceec4/src/main/java/org/springframework/data/redis/connection/RedisClusterConfiguration.java#L170-L175) method, which delegates to the `RedisNode` class ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/RedisNode.html)), and specifically, the [`RedisNode.fromString(hostPortString)`](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/RedisNode.html#fromString(java.lang.String)) method.

As you can see by the Javadoc of the `RedisNode.fromString(..)` method, it should handle both IPv4 and IPv6 addresses and port specifications.

However, the format, in your case, would be:

````yaml
spring:
  redis:
    cluster
      nodes: [fe80::a00:27ff:fe4b:ee48]:6379, [fe80::a00:27ff:fe4b:ee48]:6378
````

Can you please confirm that this would work in your case, in addition to hostnames stated @mp911de, also?

**Comment by jxblum** [comment]
@fufk2022 - Following up to my earlier post above, to verify my findings, I wrote an [additional unit test](https://github.com/spring-projects/spring-data-redis/blob/main/src/test/java/org/springframework/data/redis/connection/RedisClusterConfigurationUnitTests.java#L140-L154) verifying that using an IPv6 address and port combinations for Redis cluster configuration via the `spring.redis.cluster.nodes` property in YAML, or any other configuration source for that matter, works as expected.

As you can see in the [IPv6 address and port declarations](https://github.com/spring-projects/spring-data-redis/blob/main/src/test/java/org/springframework/data/redis/connection/RedisClusterConfigurationUnitTests.java#L42-L43) at the beginning of the test class, the pattern is exactly as I described in my previous post, essentially:

```
[IPv6-address]:port
```

I will wait for a short period of time before closing this ticket, in case you have any additional feedback on this matter. But, I would have to say this works as expected.

**Comment by jxblum** [comment]
@fufk2022 - 1 final thing worthing noting here, I thought it would be pertinent to also document the format of an IP address when declared in Spring Data Redis properties like this.

This is part of a larger effort that I am currently undertaking to revise and edit the Spring Data Redis reference documentation, in general. So, I deliberately make a special mention about the `RedisConfiguration` interface, where the implementations are commonly used to (in)directly customize the `RedisConnection`, such as by declaring or specifying a comma-delimited list of host/port pairs (for example, by using the `spring.redis.cluster.nodes` property with "clustered" Redis connections).

Anyway, you can track my progress and changes in the topic branch ([issue/2484](https://github.com/spring-projects/spring-data-redis/tree/issue/2484)) for #2484.

Feedback welcomed.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
