### ISSUE TITLE
how to config JedisClientConfiguration in spring xml bean config

### ISSUE THREAD

**Issue by linweichao** [spring-projects/spring-data-redis#2371]
`JedisConnectionFactory.setPoolConfig` is deprecated: 
> since 2.0, configure JedisPoolConfig using JedisClientConfiguration.

when i need to config beans in xml, set both `RedisStandaloneConfiguration` and `JedisClientConfiguration` for `JedisConnectionFactory`, how do i create a `JedisClientConfiguration` bean? `DefaultJedisClientConfiguration` don't have setXxx methods, use it's constructor need to set all properties，and `MutableJedisClientConfiguration` is an inner class with package access
```
<bean id="jedisPoolConfig" .../>
<bean id="jedisClientConfiguration" class=".." p:poolConfig-ref=""/>
<bean id="jedisConnectionFactory" class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory">
  <constructor-arg>
    <bean class="org.springframework.data.redis.connection.RedisStandaloneConfiguration" p:hostName="" p:port=""/>
  </constructor-arg>
  <constructor-arg ref="jedisClientConfiguration"/>
</bean>
```

**Comment by mp911de** [comment]
If you cannot switch to Java `@Bean` methods it would be easier to create a `FactoryBean` for `JedisConnectionFactory` in your code that is setting all the required properties. The configuration classes aren't designed for XML use.

**Comment by linweichao** [comment]
Thank for your reply. I will try to use `@Bean` method.
