### ISSUE TITLE
Support for Lettuce's 6.2  RedisCredentialsProvider

### ISSUE THREAD

**Issue by jiantosca** [spring-projects/spring-data-redis#2376]
Hi Folks - Our app is using spring-data-redis with Lettuce and we're hoping to be able to supply our own implementation of RedisCredentialsProvider so we can ensure fresh creds are pulled on any reconnects. Is this on the roadmap yet?

**Comment by mp911de** [comment]
We could introduce a `RedisCredentialsProviderFactory` that is able to construct `RedisCredentialsProvider` based on `RedisConfiguration`. The default implementation would use username/password from the given configuration yielding a static credentials arrangement effectively when using e.g. Spring Boot.

You could configure your own `RedisCredentialsProviderFactory` that pulls credentials from e.g. Vault and exposes these to the application.
