### ISSUE TITLE
Is "Jedis Cluster Pipeline" supported?

### ISSUE THREAD

**Issue by noseew** [spring-projects/spring-data-redis#2381]
I didn't find "SpringDataRedis" support for "Jedis Cluster Pipeline", I saw that "jedis" version has been upgraded to 4.x, please ask if there is planned support?

**Comment by mp911de** [comment]
The Jedis Cluster API does not support Pipelining therefore we cannot provide pipelining features on top of Redis Cluster usage through Jedis.

**Comment by noseew** [comment]
The 'cluster pipeline' is already supported in the jedis4.0 version. I don't know what you mean by not supporting it?

**Comment by noseew** [comment]
https://github.com/redis/jedis/pull/2700

**Comment by mp911de** [comment]
Thanks for the pointer. I wasn't aware of the pipeline utility. Still, we have little intentions to add pipelining support. Several methods emulate single-node behavior (e.g. moving keys across slots) and we have an increased complexity in the cluster support that would require significant effort to make things work.

**Comment by noseew** [comment]
Thank you for the clear reply, I plan to implement it in other ways
