### ISSUE TITLE
cannot access redis.clients.jedis.JedisShardInfo on upgrading to Jedis 4.2.0

### ISSUE THREAD

**Issue by srishtikeshari** [spring-projects/spring-data-redis#2383]
I am using Jedis v4.2 and Spring-data-redis version v2.7

I am trying to setup a Jedis Cluster using Spring-data-redis - 

```
        RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration();
        redisClusterConfiguration.setClusterNodes(getClusterNodes());

        JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory(redisClusterConfiguration);
```

Error - 
```

  java: cannot access redis.clients.jedis.JedisShardInfo
  class file for redis.clients.jedis.JedisShardInfo not found
```
  
The above code works fine if jedis 3.9.0 version is used.

**Comment by mp911de** [comment]
`JedisShardInfo` was removed with the Jedis 4 upgrade, see the [migration guide](https://github.com/redis/jedis/blob/cfc3418a246866dfcd7310fd1664cd8b8c28a7b2/docs/3to4.md) for further details.

**Comment by Udhayarajan** [comment]
@mp911de why newest spring-data-redis 2.6.4 JedisConnectionFactory, still uses JedisShardInfo internally?
