### ISSUE TITLE
Add support for multiSet with Expire Time

### ISSUE THREAD

**Issue by zhenglzh** [spring-projects/spring-data-redis#2388]
Hi,Is there possible supoort multiSet with Expire Time，as our we know we only hava multiSet method in ValueOperations

**Comment by mp911de** [comment]
Do you mean something like `MSETEX`? If so, there's no such command yet, however you can leave your vote at https://github.com/redis/redis/issues/5867.

**Comment by zhenglzh** [comment]
No，I Know Redis dose not apply MSETEX right now ，Is There Any Possible We Can Use Pipelined to add this feature。

**Comment by mp911de** [comment]
You can call `MSET` and `EXPIRE` in a pipeline yourself. We only expose commands that exist in Redis, we avoid constructing methods that look like commands as they no longer behave in an atomic way. Since there isn't anything else left to do, closing this ticket.
