### ISSUE TITLE
`JedisClusterHashCommands.hStrLen()` should calls `hstren` on `JedisCluster` object

### ISSUE THREAD

**Issue by DonalEvans** [spring-projects/spring-data-redis#2392]
The `JedisClusterHashCommands.hStrLen()` method does not use the `getCluster()` method to allow the command to be executed correctly in Cluster mode:

```
	@Nullable
	@Override
	public Long hStrLen(byte[] key, byte[] field) {
		return Long.class.cast(connection.execute("HSTRLEN", key, Collections.singleton(field)));
	}
```
For comparison, all other methods in the class use `connection.getCluster()` e.g.:

```
	@Override
	public Map<byte[], byte[]> hGetAll(byte[] key) {

		Assert.notNull(key, "Key must not be null!");

		try {
			return connection.getCluster().hgetAll(key);
		} catch (Exception ex) {
			throw convertJedisAccessException(ex);
		}
	}
```
This can lead to exceptions in the client if servers are shutdown during execution of the command, instead of retying on a different server as is expected.

This bug appears to have been introduced [with this commit](https://github.com/spring-projects/spring-data-redis/commit/f6a17fb2685d27a97ff813bddc91ccde4aae3573) and is still present in the latest unreleased version.

**Comment by mp911de** [comment]
Do you want to submit a pull request to fix the problem?

**Comment by DonalEvans** [comment]
> Do you want to submit a pull request to fix the problem?

I'm afraid I don't have a lot of spare time to work on this, and my familiarity with the Spring Data Redis codebase and testing is almost nonexistent, so I don't feel that I would be a good choice to implement this fix.
