### ISSUE TITLE
org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.TypeResolverBuilder

### ISSUE THREAD

**Issue by ForJ-W** [spring-projects/spring-data-redis#2393]
Hello, could you tell me why in version 2.7.2 'GenericJackson2JsonRedisSerializer.TypeResolverBuilder#useForType' rewrite 'ObjectMapper.DefaultTypeResolverBuilder', at the same time the statement: 'Note: "natural types" (String, Boolean, Integer, Double) will never use typing'. We have experienced conversion failure of 'natural Types' while using version 2.7.2 ( '[" java.lang.long ",0] -> Integer:0', 'Integer:0 -> Long:0' ), and change the logic in useForType to allow the wrapper type to pass. I don't know what consequences this change will cause. I want to learn the original intention of the author's design. Thank you!

change before:
    /**
     * Method called to check if the default type handler should be used for given type. Note: "natural types" (String,
     * Boolean, Integer, Double) will never use typing; that is both due to them being concrete and final, and since
     * actual serializers and deserializers will also ignore any attempts to enforce typing.
     */
    public boolean useForType(JavaType t) {

        if (t.isJavaLangObject()) {
            return true;
        }

        t = resolveArrayOrWrapper(t);

        if (ClassUtils.isPrimitiveOrWrapper(t.getRawClass())) {
            return false;
        }

        // [databind#88] Should not apply to JSON tree models:
        return !TreeNode.class.isAssignableFrom(t.getRawClass());
    }

change after:
    /**
     * Method called to check if the default type handler should be used for given type. Note: "natural types" (String,
     * Boolean, Integer, Double) will never use typing; that is both due to them being concrete and final, and since
     * actual serializers and deserializers will also ignore any attempts to enforce typing.
     */
    public boolean useForType(JavaType t) {
    
        if (t.isJavaLangObject() || ClassUtils.isPrimitiveWrapper(t.getRawClass())) {
            return true;
        }

        t = resolveArrayOrWrapper(t);

        if (t.getRawClass().isPrimitive()) {
            return false;
        }

        // [databind#88] Should not apply to JSON tree models:
        return !TreeNode.class.isAssignableFrom(t.getRawClass());
    }

**Comment by christophstrobl** [comment]
Please have a look at #2361. Thank you.
