### ISSUE TITLE
The implementation of GenericJackson2JsonRedisSerializer has changed in a non-back-compatible manner - and perhaps, by accident?

### ISSUE THREAD

**Issue by oliverlockwood** [spring-projects/spring-data-redis#2396]
### Context

We make significant use of Redis across our microservices platform, including `spring-data-redis`.
We are in the process of upgrading from Spring-Boot 2.6.x to Spring-Boot 2.7.x.

As a consequence, we have started to see exceptions being thrown when one microservice tries to deserialize data that had been serialised by another microservice running a different spring-boot layer.  Given that some state is allowed to survive as we upgrade our platform, this poses problems.

### Investigation

After a little investigation, it became clear that the 2.7.x `spring-data-redis` has fundamentally changed the implementation of the `GenericJackson2JsonRedisSerializer` class.  One example is serialization of a `java.util.UUID`, where a UUID like `730145fe-324d-4fb1-b12f-60b89a045730`:
1.  used to be serialized - as one might expect, for JSON! - as `"730145fe-324d-4fb1-b12f-60b89a045730"`
2.  from Spring-Boot 2.7.x, the same UUID gets serialized as a strange array, that looks like `["java.util.UUID","730145fe-324d-4fb1-b12f-60b89a045730"]`

I looked into the [history of the `GenericJackson2JsonRedisSerializer` class](https://github.com/spring-projects/spring-data-redis/commits/2.7.2/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java) and found commit https://github.com/spring-projects/spring-data-redis/commit/0e23a805cab15a87f537006c1c5db6c655d60327 which is described as fixing issue https://github.com/spring-projects/spring-data-redis/issues/2361.  That issue, in turn, is titled:
> `GenericJackson2JsonRedisSerializer` fails with `Unexpected token` when deserializing `int[]` with default typing

It strikes me as possible that this change, intended to address problems with the (de)serialization of arrays, has inadvertently caused things that _aren't_ arrays to be serialised as arrays.

If the change is deliberate, is there any reference documentation I can take a look at, to understand why this change has been made - and what else the change has done, which I might not yet have realised? 

I would very much welcome some feedback on this issue.  Thank you for your time.

### Example

An example repo demonstrating the issue is available at https://github.com/oliverlockwood/sb2.7-spring-data-redis-example.

**Comment by christophstrobl** [comment]
@oliverlockwood thanks for the reproducer - we'll have a look.

**Comment by YLombardi** [comment]
I have a similar issue when upgrading from spring-boot 2.6 to 2.7

https://github.com/YLombardi/localdate-deserialization-issue-with-redis

The first time I use the web service, it stores the data in redis and this works fine.  
![image](https://user-images.githubusercontent.com/9447223/188102793-959abda0-7f3f-44eb-bf18-ff07b571bbf4.png)

But when I use the web-service a second time, it read the data in redis and fail to deserialize.  
![image](https://user-images.githubusercontent.com/9447223/188102841-60044acb-e5b9-4b3b-809f-a748be7f5cc8.png)
```org.springframework.data.redis.serializer.SerializationException: Could not read JSON: Java 8 date/time type `java.time.LocalDate` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling```

**Comment by christophstrobl** [comment]
@YLombardi - thanks, will consider this as well.
