### ISSUE TITLE
Reactive `multiGet` returns empty string on non-existing key

### ISSUE THREAD

**Issue by dittos** [spring-projects/spring-data-redis#2402]
Reactive `multiGet` does not distinguish between null and empty string.

```kotlin
// redis: ReactiveStringRedisTemplate instance
redis.opsForValue().set("a", "").block()
val result = redis.opsForValue().multiGet(listOf("a", "nonexisting")).block()!!
println(result) // expects ["", null] but actually ["", ""]
```

The behavior is inconsistent with Reactive `get` and blocking `multiGet` which returns null on non-existing key.

(Tested on spring-data-redis 2.6.2)

----

`LettuceReactiveStringCommands` needs to be changed. (but it would break existing usages)

https://github.com/spring-projects/spring-data-redis/blob/7d34afbcaa9f9060344c6969bf1ba047fd15974d/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceReactiveStringCommands.java#L73

**Comment by mp911de** [comment]
See also #2210

**Comment by Manasadaram** [comment]
I am still observing the issue in version 3.0.1
