### ISSUE TITLE
Whether the exists method should return false rather than null when the key does actually not exist

### ISSUE THREAD

**Issue by Xin-Sheng-5075** [spring-projects/spring-data-redis#2404]
The position is org.springframework.data.redis.connection.RedisKeyCommands
I think that an exists method should return only true or false , or we need to check whether the return value is null to prevent NPE
Or , is returning null expected to show that there were some faults occured during the previous process , which we can't consider that the key does not exist
```java
@Nullable
default Boolean exists(byte[] key) {
    Assert.notNull(key, "Key must not be null");
    Long count = exists(new byte[][] { key });
    return count != null ? count > 0 : null;
}
```

**Comment by mp911de** [comment]
When using transactions, commands return `null` during the invocation. Later by calling `exec` we receive all the command responses but at that time, we no longer have the correlation to the called method.
