### ISSUE TITLE
how to monitor get connection cost

### ISSUE THREAD

**Issue by zhangyanglei** [spring-projects/spring-data-redis#2415]
i want get the cost of time for my springboot  application client get connection from redis server

**Comment by mp911de** [comment]
If you would like us to spend some time helping you, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the issue that you want to solve. What do you mean with cost?

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
