### ISSUE TITLE
Allow ReactiveRedisOperations to save data in RedisJSON format

### ISSUE THREAD

**Issue by tushar-sharma** [spring-projects/spring-data-redis#2429]
Hi, currently I am using reactive ReactiveRedisOperations to save key in redis with string data type. 

```java
@Autowired
ReactiveRedisOperations<String, Foo> redisOperation;

public void save(Foo foo) {
    redisOperation.map(operation -> 
     operation
     .opsForValue()
     .set(foo.getId(), foo);
}
``` 

I want to save data in JSON format reactively (https://oss.redislabs.com/redisjson/). Does ReactiveRedisOperations supports this functionality ?

**Comment by mp911de** [comment]
No, Spring Data Redis does not support Redis-specific modules. Check out Redis OM (https://redis.io/docs/stack/get-started/tutorials/stack-spring/) for this kind of functionality.
