### ISSUE TITLE
Under certain setings StringRedisConnection unlink throws exception

### ISSUE THREAD

**Issue by theoren** [spring-projects/spring-data-redis#2443]
Calling StringRedisConnection unlink causes java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

Here's the relevant code snip.
...
stringRedisTemplate.executePipelined(
 new RedisCallback<Object>() {
  public Object doInRedis(RedisConnection connection) throws DataAccessException {
   StringRedisConnection stringRedisConn = (StringRedisConnection) connection;
   for (int i = 0; (i < 100) && it.hasNext(); ++i) {
    stringRedisConn.unlink(it.next());
  }
  return null;
 }
});
Tested using 
 SDR 2.7.4-2.7.5
 Redisson 3.17.6-3.17.7
 
DefaultStringRedisConnection.unlink(byte[]) keys has length 1
RedissonConnection.unlink keys has length 0

hGetAll and del work

**Comment by mp911de** [comment]
Can you include the full stack trace and provide a minimal reproducer that is able to demonstrate the problem?
