### ISSUE TITLE
How to disable the connection

### ISSUE THREAD

**Issue by jpdev01** [spring-projects/spring-data-redis#2444]
in a development environment it will not be necessary to run redis, but it keeps trying to connect. Is there a way to disable it?

 o.s.d.r.l.RedisMessageListenerContainer  : Connection failure occurred. Restarting subscription task after 5000 ms

**Comment by mp911de** [comment]
Only if you remove the configuration beans from your application context. Other than that, if you register a `RedisMessageListenerContainer` with a subscription, Spring Data Redis attempts to connect to Redis.
