### ISSUE TITLE
spring data redis short of production code example or configure best pracice

### ISSUE THREAD

**Issue by nzb15555196162** [spring-projects/spring-data-redis#2445]
hi i have a question when i read doc of spring data redis,  i only found short example of how to use, it's no good for normal user  in production or may be i not found correct, can office provider more production example or doc paramter example explain, may be will be better for developer, please think about it.
see following snapshot, it's so simple
![image](https://user-images.githubusercontent.com/18350673/198532423-f6042a3a-710b-45d7-8bbb-035c8d9b776a.png)

**Comment by mp911de** [comment]
Care to elaborate what you're looking for and what issues you've experienced with a simple connection factory configuration that does not work for you?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
