### ISSUE TITLE
Redis command metrics

### ISSUE THREAD

**Issue by zhangyanglei** [spring-projects/spring-data-redis#2447]
i want put some metrics to the prometheus when i use redisTemplate but i can not find a friendlly way.  DefaultValueOperations is not public

**Comment by mp911de** [comment]
You can either use the Lettuce driver with Micrometer or integrate through the [Observability API](https://docs.spring.io/spring-data/redis/docs/3.0.0-RC2/reference/html/#redis.observability) that was added in the 3.0.0 RC2 milestone just recently.

**Comment by zhangyanglei** [comment]
i can not 3.0.0 RC2 for a short time,I'll look at that lettuce driver with Micrometer, thank you for reply
