### ISSUE TITLE
Add a writing Redis healthcheck

### ISSUE THREAD

**Issue by trajano** [spring-projects/spring-data-redis#2449]
The current redis healthcheck only does a connectivity check.  It does not attempt to perform a write which may fail.

https://stackoverflow.com/questions/67904609/how-do-you-perform-a-healthcheck-in-the-redis-docker-image

Shows how I did it on the docker image itself.  For the Spring applications I implemented it as [IncrRedisReactiveHealthIndicator](https://github.com/trajano/spring-cloud-demo/blob/rework/jwks-provider/src/main/java/net/trajano/swarm/jwksprovider/redis/IncrRedisReactiveHealthIndicator.java).  Feel free to use it, the concept is simply to perform an INCR operation twice and check that it moves forward (in case there's multiple services hitting the ping key it won't matter since it will still be one after the other).

Ideally, you'd have a the key configurable right now I hard coded it to `ping`.

**Comment by mp911de** [comment]
Healthchecks are generally a Spring Boot concern.
