### ISSUE TITLE
Values of indices are not removed from Redis after notifications come

### ISSUE THREAD

**Issue by IlyaShatskikh** [spring-projects/spring-data-redis#2469]
`spring data redis 2.7.6`
`redis 7.0.5`

Entity:
`@RedisHash(value = "test:testing", timeToLive = 60)
public class CachedEntity {
    @Id
    private String id;
...`

Configuration:
`@EnableRedisRepositories(enableKeyspaceEvents = EnableKeyspaceEvents.ON_STARTUP, keyspaceNotificationsConfigParameter = "")`

Spring repository uses `test:testing` as keyspace and works well, but messages from Redis notification channel about expiration contains data with "test" as keyspace and "testing:12" as key. 
Because of that `org.springframework.data.redis.core.IndexWriter` can't remove keys from the indices set, so dead index values collect in Redis.
If using just `word` as keyspace it works.

**Comment by mp911de** [comment]
Index values must be actively removed. That works only if the application is running while the key expires.

**Comment by IlyaShatskikh** [comment]
> Index values must be actively removed. That works only if the application is running while the key expires.

Yes, the app is running. In debugger, I see coming notifications, but the key doesn't match the index value.

**Comment by mp911de** [comment]
Then there is a mismatch between the project and the Redis notifications. Please provide a minimal reproducer if you want us to look into the ticket.
