### ISSUE TITLE
Why does `GenericJackson2JsonRedisSerializer` default constructor use `mapper.enableDefaultTyping`?

### ISSUE THREAD

**Issue by stager0909** [spring-projects/spring-data-redis#2470]
Hi

```
public GenericJackson2JsonRedisSerializer() {
		this((String) null);
}

public GenericJackson2JsonRedisSerializer(@Nullable String classPropertyTypeName) {

	this(new ObjectMapper());

	registerNullValueSerializer(mapper, classPropertyTypeName);

	if (StringUtils.hasText(classPropertyTypeName)) {
		mapper.enableDefaultTypingAsProperty(DefaultTyping.NON_FINAL, classPropertyTypeName);
	} else {
		mapper.enableDefaultTyping(DefaultTyping.NON_FINAL, As.PROPERTY);
	}
}
```

If you use the GenericJackson2JsonRedisSerializer default constructor, the code below applies.
```
mapper.enableDefaultTyping(DefaultTyping.NON_FINAL, As.PROPERTY);
```
With the above settings, @JsonTypeInfo must be present when using kotlin data class.

There is no problem to serialize/deserialize even without that setting, why do you have that setting?

**Comment by mp911de** [comment]
Our serializers expect the serialized representation to contain typing information as we deserialize objects without a type hint. This is required in many places. Hence we require default typing.
