### ISSUE TITLE
why RedisTemplate not to support bloomfilter

### ISSUE THREAD

**Issue by MiniSC** [spring-projects/spring-data-redis#2471]
Hi
I have an question
I want use redis's bloomfilter in my application,and redis 4.0 have been released over 3 years, but spring-data-redis project not support ,  if anything wrong in test or another reason?

**Comment by mp911de** [comment]
Because Redis doesn't support Bloom filters natively. It's only supported via modules like [redis-bloom](https://redis.com/blog/bloom-filter/).
