### ISSUE TITLE
MOVED 6203 error when fetching data using findAll of spring repositories from Clustered Redis

### ISSUE THREAD

**Issue by hawkeye310** [spring-projects/spring-data-redis#2477]
We are using spring-data-redis latest version 3.0.1 with the following configuration to connect to Redis.

`RedisConfiguration.java`
```java
    ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()
            .timeoutOptions(TimeoutOptions.enabled(Duration.ofSeconds(60L)))
            .topologyRefreshOptions(ClusterTopologyRefreshOptions.builder()
                    .enablePeriodicRefresh(Duration.ofSeconds(10L)) // Refresh the topology periodically.
                    .enableAllAdaptiveRefreshTriggers() // Refresh the topology based on events.
                    .dynamicRefreshSources(false)
                    .build())
            .autoReconnect(true)
            .cancelCommandsOnReconnectFailure(true)
            .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
            .build();
    LettuceClientConfiguration clientConfig = LettucePoolingClientConfiguration.builder()
            .commandTimeout(Duration.ofSeconds(60L))
            .readFrom(ReadFrom.REPLICA_PREFERRED) // Preferentially read data from the replicas.
            .clientOptions(clusterClientOptions)
            .useSsl()
            .build();
    RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration();
    redisClusterConfiguration.addClusterNode(new RedisNode(redisHost, redisPort));
    redisClusterConfiguration.setPassword(redisPassword);
    return new LettuceConnectionFactory(redisClusterConfiguration, clientConfig);
```

Whenever the fetch operation is executed the following error is observed:
```
java.util.concurrent.ExecutionException: org.springframework.data.redis.RedisSystemException: 

Error in execution;nested exception is io.lettuce.core.RedisCommandExecutionException: MOVED 6203 redisHost:2665
```

The repository definition is as follows:

```java
@Repository
public interface ExampleRepository extends CrudRepository<ExampleRepo, String> {}
```

The Example Repo class definition is as follows:

```java
@Data
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@RedisHash("hash:ex")
public class ExampleRepo implements Serializable {

    @Id
    @EqualsAndHashCode.Include
    private String field1;

    private String field2;

    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime field3;

}
```

The code used to fetch data is: `exampleRepository.findAll()`

**The Redis cluster is hosted on AWS in a multi-AZ (Availability Zones) mode**

The `@EnableRedisRepositories` annotation has been added to the RedisConfiguration class.

Please provide any inputs to fix this issue.

**Comment by mp911de** [comment]
Lettuce auto-follows redirections so I'm wondering what has happened here. Can you provide more details, such as the complete stack trace and enable debug logging for the Lettuce client that shows the interaction with the `MOVED` key and the subsequent command responses?

**Comment by hawkeye310** [comment]
[DebugLogs.pdf](https://github.com/spring-projects/spring-data-redis/files/10337966/DebugLogs.pdf)
[StackTraceLettuce.pdf](https://github.com/spring-projects/spring-data-redis/files/10337968/StackTraceLettuce.pdf)
@mp911de  Please find the attached files containing the stack trace and debug logs. 
I could only capture this as our application environment has a limitation in the number of log lines per second.
Hope this is useful.

**Comment by mp911de** [comment]
The stack trace and debug logs do not match your configuration. The config shows you're using Lettuce while the logs show Jedis. Also, the stack trace shows that you're not using the Cluster mode but rather standalone mode which doesn't support command routing. 

Please fix your config and retry.
