### ISSUE TITLE
Error: use using junit testing multithreaded access redis IO. Lettuce. Core. RedisConnectionException: Unable to connect to 10.50.70.1: * * * *

### ISSUE THREAD

**Issue by MsencSir** [spring-projects/spring-data-redis#2481]
Environment:
spring-boot:2.2.2
spring-data-redis:2.5.2
spring-cloud-dependencies-parent:3.0.3
Configuration:
![image](https://user-images.githubusercontent.com/46589466/210954494-91661eb3-11d4-42fc-ab21-b0b09cf9d6d3.png)
Code:
![image](https://user-images.githubusercontent.com/46589466/210954612-8f3b0552-1fbe-47e3-a6ee-f0563df24270.png)
Result:
test1:Normal
![image](https://user-images.githubusercontent.com/46589466/210955128-99ed1a3b-682e-44ee-ac24-d3ce1c102efc.png)

test2:Anomaly
![image](https://user-images.githubusercontent.com/46589466/210955446-6e89577a-131a-4532-bff7-7b49025153c8.png)

What causes it?

**Comment by mp911de** [comment]
This is a consequence of improper synchronization. Your code starts threads but does not await their completion. Please fix your code.
