### ISSUE TITLE
blpop or brpop GET value error

### ISSUE THREAD

**Issue by buhecoffee** [spring-projects/spring-data-redis#2486]
spring data Redis version is 2.6.3

`  
    @Autowired
    private StringRedisTemplate template;
    
    private String LIST_KEY = "LIST_KEY";
    
    
    @Override
    public void pushMag() {
        template.opsForList().leftPush(LIST_KEY, "A:" + System.currentTimeMillis());
    }
    
    
    @Override
    public String popMsg() {
        
        String result = template.execute(new RedisCallback<String>() {
            @Override
            public String doInRedis(RedisConnection connection) throws DataAccessException {
                List<byte[]> bytes = connection.bRPop(30, LIST_KEY.getBytes(StandardCharsets.UTF_8));
                String value = ColUtils.toObj(EntityUtils.toList(bytes, String::new));
                System.out.println("value = " + value);
                return value;
            }
        });
        return result;
    }`

why brpop GET value is key? such as `value = LIST_KEY`

amazing! please help me

**Comment by christophstrobl** [comment]
The behaviour of the connection interface is consistent with the [BRPOP](https://redis.io/commands/brpop/) command returning: 
> A two-element multi-bulk with the first element being the name of the key where an element was popped and the second element being the value of the popped element.

You may want to use `ListOperations` which will extract the element at position 1 for you if present.
