### ISSUE TITLE
@Nullable annotation is missing at ListOperations::indexOf

### ISSUE THREAD

**Issue by amaembo** [spring-projects/spring-data-redis#2488]
Methods `indexOf` and `lastIndexOf` [here](https://github.com/spring-projects/spring-data-redis/blob/e9e2c53d78c479d9ea2e2f50534a31464b364c99/src/main/java/org/springframework/data/redis/core/ListOperations.java#L391) are documented as nullable but not annotated correspondingly.

The documentation says:
> `@return {@literal null} when used in pipeline / transaction or when not contained in list.`

However, the methods are not annotated as `@Nullable`, and the package is [annotated](https://github.com/spring-projects/spring-data-redis/blob/e9e2c53d78c479d9ea2e2f50534a31464b364c99/src/main/java/org/springframework/data/redis/core/package-info.java#L6) as `@NonNullApi`. This causes false-positive static analysis warnings. Sorry if I'm missing something.

**Comment by jxblum** [comment]
Looking at the corresponding Redis [List commands](https://redis.io/commands/?group=list), the corresponding SD Redis `ListOperations`, [`indexOf(key, value)`](https://github.com/spring-projects/spring-data-redis/blob/3.0.1/src/main/java/org/springframework/data/redis/core/ListOperations.java#L391) and [`lastIndexOf(key, value)`](https://github.com/spring-projects/spring-data-redis/blob/3.0.1/src/main/java/org/springframework/data/redis/core/ListOperations.java#L403) correspond to the [LPOS](https://redis.io/commands/lpos/) Redis command, which documents that `nil` will be returned when no match is found.

Therefore, it is correct to annotate our API with the Spring `@Nullable` annotation.
