### ISSUE TITLE
RedisCache.clear() is not work when i use serializeCacheKey add some prefix 

### ISSUE THREAD

**Issue by aimilin6688** [spring-projects/spring-data-redis#2496]
I use RedisCacheConfiguration custom serialize  key add some prefix  RedisCache.clear()  can't clear cache key;

Example i custom serialize key add prefix 'test:'

```txt
key  = 'a.b.c'
createCacheKey(key) -> 'a.b.c'
serializeCacheKey(createCacheKey(key)) -> 'test:a.b.c'   
```

but clear not call  serializeCacheKey method cause not to clear cache;

```java
	@Override
	public void clear() {

		byte[] pattern = conversionService.convert(createCacheKey("*"), byte[].class);
		cacheWriter.clean(name, pattern);
	}
```

use 2.6.x 2.7.x will reproduce the issue
use 3.0.x no this issue

**Comment by mp911de** [comment]
What type of serializer do you use? The general `String`-based serializer doesn't cause that kind of issues.

**Comment by aimilin6688** [comment]
I use String-based serializer

```java
    @Override
    public byte[] serialize(@Nullable String string) {
        return (string == null ? null : this.addTencentCodePrefix(string).getBytes(charset));
    }

    private String addTencentCodePrefix(String key) {
        if (key == null || ignorePrefix(key)) {
            return key;
        }
        TenantInfo info = TenantHolder.get();
        return (Objects.isNull(info) || Objects.isNull(info.getCode())) ? key : info.getCode() + ":" + key;
    }
```

**Comment by mp911de** [comment]
I'm not able to reproduce the issue:

```java
LettuceConnectionFactory factory = new LettuceConnectionFactory();
factory.afterPropertiesSet();

RedisCacheConfiguration config = RedisCacheConfiguration.defaultCacheConfig()
		.serializeKeysWith(SerializationPair.fromSerializer(new MyStringRedisSerializer()));
RedisCacheManager cacheManager = RedisCacheManagerBuilder.fromCacheWriter(RedisCacheWriter.nonLockingRedisCacheWriter(factory))
		.cacheDefaults(config)
		.initialCacheNames(Set.of("my-cache"))
		.build();

cacheManager.afterPropertiesSet();
Cache mycache = cacheManager.getCache("my-cache");

mycache.put("my-entry", "value");

mycache.clear();
```


Output of `MONITOR` command:

```
1675067191.686483 [0 127.0.0.1:61992] "SET" "tn1:my-cache::my-entry" "\xac\xed\x00\x05t\x00\x05value"
1675067191.688413 [0 127.0.0.1:61992] "KEYS" "tn1:my-cache::*"
1675067191.689281 [0 127.0.0.1:61992] "DEL" "tn1:my-cache::my-entry"
```

```
127.0.0.1:6379> keys *
(empty array)
```

**Comment by aimilin6688** [comment]
3.0.x  [RedisCache](https://github.com/spring-projects/spring-data-redis/blob/3.0.x/src/main/java/org/springframework/data/redis/cache/RedisCache.java) no this issue
```java
@Override
	public void clear() {
		clear("*");
	}

	public void clear(String keyPattern) {
		cacheWriter.clean(name, createAndConvertCacheKey(keyPattern));
	}

```

use 2.6.x 2.7.x will  reproduce the issue:

2.7.x [RedisCache](https://github.com/spring-projects/spring-data-redis/blob/2.7.x/src/main/java/org/springframework/data/redis/cache/RedisCache.java)

```java
@Override
	public void clear() {

		byte[] pattern = conversionService.convert(createCacheKey("*"), byte[].class);
		cacheWriter.clean(name, pattern);
	}
```

**Comment by mp911de** [comment]
Thanks for clarifying. We improved the `clear` method with #2379 to consistently use `createAndConvertCacheKey` and decided not to backport these changes into the 2.x branches as it was part of the feature. Switching from `ConversionService` usage to `SerializationPair` can introduce application behavioral changes that aren't obvious. 

If you want to apply a cache prefix, please use the `computePrefixWith(CacheKeyPrefix)` configuration method and let us know whether this approach has worked for you.

**Comment by aimilin6688** [comment]
Thank you very much. That solved my problem
