### ISSUE TITLE
hi, My version is [3.2.8-alpine], I have the same error in spring-cloud-gateway:2.2.1.RELEASE， spring-boot-starter-data-redis:2.2.0.RELEASE， in my [Filter] class use redisTemplate.get(myKey)， Will report this error. It is sporadic. It will not appear until the program runs for a period of time, and will become normal after restarting. Do you have any good suggestions.

### ISSUE THREAD

**Issue by XiaoPenPen** [spring-projects/spring-data-redis#2501]
hi, My version is [3.2.8-alpine], I have the same error in spring-cloud-gateway:2.2.1.RELEASE， spring-boot-starter-data-redis:2.2.0.RELEASE， in my [Filter] class use redisTemplate.get(myKey)， Will report this error. It is sporadic. It will not appear until the program runs for a period of time, and will become normal after restarting. Do you have any good suggestions.

_Originally posted by @XiaoPenPen in https://github.com/spring-projects/spring-data-redis/issues/1780#issuecomment-1423564780_

**Comment by XiaoPenPen** [comment]
![1R%B1TH`D0PYM)S6`9R 9@4](https://user-images.githubusercontent.com/42669253/217728977-4bf58053-cb72-4a22-8e5b-cb0d3cfb97c8.png)

**Comment by mp911de** [comment]
Command interrupted is a consequence of a `Thread` being interrupted. Since neither Spring Data nor Lettuce are interrupting threads (as they are not controlling application shutdown), there isn't anything we can do to address your issue.
