### ISSUE TITLE
Migrate `RedisConnectionFactory` to `Lifecycle` beans

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-redis#2503]
Based on https://github.com/spring-projects/spring-framework/issues/29921, we could move our connection factories towards beans that implement the lifecycle. This would be especially useful to decouple `afterPropertiesSet` from the connection pool startup and `dispose()` where we dispose resources. With `start()` and `stop()` connection factories could start up pools and tear down as necessary without destroying the entire bean.

**Comment by jxblum** [comment]
I'd need to think on this a bit more, but my first reaction when I read your comment (@mp911de) is that this might also be beneficial when using Spring Data Redis with Project Loom (Threading model).
