### ISSUE TITLE
Redis native image issue

### ISSUE THREAD

**Issue by kartik-kaushik** [spring-projects/spring-data-redis#2519]
Describe the bug
Redis serialization issue in Spring Boot native image

Sample
Via the Spring Initializer, create any project with:
spring-boot-starter-parent:3.0.2
add dependency: spring-boot-starter-data-redis

redis template
   @Bean(name = "redis")
    RedisTemplate<String, Object> redisTemplate1() {
        final RedisTemplate<String, Object> template = new RedisTemplate<String, Object>();
        template.setConnectionFactory(jedisConnectionFactory());
        template.setKeySerializer(template.getStringSerializer());
        template.setValueSerializer(new JsonRedisSerializer());
        return template;
    }

 static class JsonRedisSerializer implements RedisSerializer<Object> {

        private final ObjectMapper om;

        public JsonRedisSerializer() {

            this.om = new ObjectMapper().activateDefaultTyping(LaissezFaireSubTypeValidator.instance, ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);
        }

        @Override
        public byte[] serialize(Object t) throws SerializationException {
            try {
                return om.writeValueAsBytes(t);
            } catch (JsonProcessingException e) {
                throw new SerializationException(e.getMessage(), e);
            }
        }

        @Override
        public Object deserialize(byte[] bytes) throws SerializationException {

            if (bytes == null) {
                return null;
            }

            try {
                return om.readValue(bytes, Object.class);
            } catch (Exception e) {
                throw new SerializationException(e.getMessage(), e);
            }
        }
    }
}

the application works normally but in native mode give error:
org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:64) ~[na:na]
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:33) ~[na:na]
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:94)

**Comment by christophstrobl** [comment]
From the error it seems the `JdkSerializationRedisSerializer` is used. Since we cannot determine at build time which types will be sent over to Redis and require [Serialization](https://www.graalvm.org/22.1/reference-manual/native-image/Limitations/#serialization), the according hints need to be provided.

You may add required hints as described in the [Reference Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.custom-hints).

```java
@Configuration
@ImportRuntimeHints({MySerializationRuntimeHints.class})
class Config { ... }

class MySerializationRuntimeHints implements RuntimeHintsRegistrar {
	@Override
	public void registerHints(RuntimeHints hints, @Nullable ClassLoader classLoader) {
		hints.serialization().registerType(...);
	}
}
```

If the above does not solve your problem, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kartik-kaushik** [comment]
@christophstrobl thanks for your response.
It worked by making modifications in our custom template and finally adding the same as per your mentioned
