### ISSUE TITLE
Cleanup APIs in SD Redis returning Streams, Collections or arrays that are null

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-data-redis#2523]
An API that returns an array, `Collection` / `Map` type, or `Stream` should never be `null` in most cases.

https://thefinestartist.com/effective-java/43

If `null` is returned, then it should be adequately and appropriately documented why we are (or must) deviating from the generally accepted best practice.

**Comment by jxblum** [comment]
Seems this may be by design given the unfortunate side effect produced by Redis client drivers (themselves) returning `null` aggregate data structure references. :(

**Comment by mp911de** [comment]
As this isn't actionable, I suggest closing the ticket. We can always come back later and repoen if necessary.

**Comment by jxblum** [comment]
Closing due to inability to act on this ticket.
