### ISSUE TITLE
Documentation inaccuracy for Redis Pub/Sub section

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-data-redis#2524]
Hi

Here's the code from the reference documentation to attach custom message handler:

```
  @Bean
  RedisMessageListenerContainer redisMessageListenerContainer(RedisConnectionFactory connectionFactory, DefaultMessageDelegate listener) {

    RedisMessageListenerContainer container = new RedisMessageListenerContainer();
    container.setConnectionFactory(connectionFactory);
    container.addMessageListener(new MessageListenerAdapter(listener, "handleMessage"), ChannelTopic.of("chatroom"));
    return container;
  }
```

However it would fail with the error message:
```

java.lang.NullPointerException: Cannot invoke "org.springframework.data.redis.listener.adapter.MessageListenerAdapter$MethodInvoker.getMethodName()" because "this.invoker" is null
	at org.springframework.data.redis.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:307)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:845)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lambda$dispatchMessage$7(RedisMessageListenerContainer.java:993)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

The issue that this code doesn't invoke afterPropertiesSet as clearly mentioned in JavaDocs of MessageListenerAdapter:

`Make sure to call {@link #afterPropertiesSet()} after setting all the parameters on the adapter.`

**Comment by mp911de** [comment]
`afterPropertiesSet` is a lifecycle callback method invoked by the bean container. If you define `RedisMessageListenerContainer` in a `@Bean` method, then Spring Framework is going to call that method for you.

So in that regard, our documentation is accurate. If you want to spin up beans on your own without using the Spring bean container, then you need to take care of all lifecycle callbacks (`afterPropertiesSet`, `destroy`, `start`, `stop` and a few more).

**Comment by sergey-morenets** [comment]
Hi @mp911de 

Thank you for the quick response.
I talked about this piece of code from your documentation:

```
@Bean
  RedisMessageListenerContainer redisMessageListenerContainer(RedisConnectionFactory connectionFactory, DefaultMessageDelegate listener) {

    RedisMessageListenerContainer container = new RedisMessageListenerContainer();
    container.setConnectionFactory(connectionFactory);
    container.addMessageListener(new MessageListenerAdapter(listener, "handleMessage"), ChannelTopic.of("chatroom"));
    return container;
  }
```

so this code just doesn't work because afterPropertiesSet is not invoked. I had to deep dive into source code to understand why. So I suggest to change this piece of code and add invocation of afterPropertiesSet().

**Comment by mp911de** [comment]
Apologies, I mixed up `RedisMessageListenerContainer` and `MessageListenerAdapter`. After realizing what we're talking about, you're totally right, that we rather should declare `MessageListenerAdapter` as bean instead of requiring `afterPropertiesSet`. Also, calling the constructor with both required arguments (delegate, `defaultListenerMethod`), we are able to create a method invoker instance.
