### ISSUE TITLE
Java uses Redison v3.16.8 to connect to Redis 6

### ISSUE THREAD

**Issue by demonzhangzhe** [spring-projects/spring-data-redis#2537]
level':'INFO','thread':'main','logger':'o.s.d.r.c.RepositoryConfigurationExtensionSupport','message':'Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.y3technologies.aas.repository.TenantUserGroupRepository. If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository.'}

What is the reason for reporting this news?

**Comment by mp911de** [comment]
Because you have multiple store modules on your class path. Check out the documentation at https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.multiple-modules for further guidance.
