### ISSUE TITLE
With regard to the character encoding of RedisSerializer and its implementation classes, it is hoped that the official default setting is UTF-8

### ISSUE THREAD

**Issue by 203579397** [spring-projects/spring-data-redis#2538]
I found key garbled in redis when I was using `JdkSerializationRedisSerializer`. 

Guess that the `JdkSerializationRedisSerializer` serialization transformation does not specify the character encoding as UTF-8. 

But maybe I was wrong?

**Comment by jxblum** [comment]
First, you must understand that Spring Data Redis's `JdkSerializationRedisSerializer` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/serializer/JdkSerializationRedisSerializer.html), [source](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/serializer/JdkSerializationRedisSerializer.java)) uses the core Spring Framework serialization infrastructure, through the Converter framework, under -the-hood.

See [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/serializer/JdkSerializationRedisSerializer.java#L38-L39) and [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/serializer/JdkSerializationRedisSerializer.java#L45), then [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/serializer/JdkSerializationRedisSerializer.java#L94) and [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/serializer/JdkSerializationRedisSerializer.java#L82), converting an `Object` (key or value) to bytes (`byte[]`) on serialization and from bytes (`byte[]`) to an `Object` (key or value) on deserialization.

The `SerializationConverter` ([Javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/serializer/support/SerializingConverter.html)) and `DeserializationConverter` ([Javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/serializer/support/DeserializingConverter.html)) both come from the core Spring Framework. They are not Spring Data Redis specific.

By default, the core Spring Framework `DefaultSerializer` ([Javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/serializer/DefaultSerializer.html), [source](https://github.com/spring-projects/spring-framework/blob/v6.0.8/spring-core/src/main/java/org/springframework/core/serializer/DefaultSerializer.java)) is used for JDK (Java) serialization.

As you can see, a normal `java.io.ObjectOutputStream` ([Javadoc](https://docs.oracle.com/javase/8/docs/api/java/io/ObjectOutputStream.html)) is used to "serialize" the `Object`.

> NOTE: Conversely, and not surprisingly, the Spring Framework `DefaultDeserializer` and ObjectInputStream` are used to convert (deserialize) a `byte[]` (given an `InputStream`) back into a Java `Object`.

As a result, you are at the mercy of the Java Serialization (JRE for your platform) infrastructure. By default, Java uses UTF-8 to encode/decode Strings. See [docs](https://docs.oracle.com/javase/8/docs/platform/serialization/spec/protocol.html), under section "6.2. Stream Elements" (search for "UTF-8" if you have to).

About the only thing you can influence here (using Spring bits) is the `ClassLoader` used to resolve the Java types on deserialization. All the rest is handled by Java and has nothing to do with Spring.

If you are using `String's` for all of your Redis (hash) keys, then it would be a simple matter to configure Spring Data Redis to use the `StringRedisSerializer`. For example:

```java
@Configuration
class MySpringDataRedisApplicationConfiguration {

    @Bean
    RedisConnection redisConnection(..) {
        // return new <JedisConnectionFactory(..) or LettuceConnectionFactory(..)>;
    }

    @Bean
    RedisTemplate customRedisTemplate(RedisConnectionFactory connectionFactory) {

        RedisTemplate redisTemplate = new RedisTemplate();

        redisTemplate.setConnectionFactory(connectionFactory);
        redisTemplate.setKeySerializer(RedisSerializer.string());

        return redisTemplate;
    }
}
```

If you look carefully, the `RedisSerializer.string()` factory method ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/serializer/StringRedisSerializer.html), [source](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/serializer/StringRedisSerializer.java)) returns ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/serializer/RedisSerializer.java#L91-L93)) a `StringRedisSerializer` with UTF-8 encoding.

Alternatively, and after a careful review of your JRE and configuration, if you are still are experiencing issues, then I'd suggest writing your own `RedisSerializer` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/serializer/RedisSerializer.html)) implementation. However, this should be quite unnecessary. Still, it would afford you more control and configurability based on your application use case and requirements (SLAs).

You could then implement the `serialize(:Object)` and `deserialize(:byte[])` methods using `ObjectOutputStream` and `ObjectInputStream`, respectively. However, on serialization, you could use low-level methods like `ObjectOutputStream.writeUTF(:String)` ([Javadoc](https://docs.oracle.com/javase/8/docs/api/java/io/ObjectOutputStream.html#writeUTF-java.lang.String-)) to serialize the `String`.

> NOTE: Subsequently, you and use the `ObjectInputStream.readUTF(..)` method when deserializing the bytes of the key.

I will leave this as an exersize for you.

Given there is no substantial evidence (e.g. a reproducer demonstrating the problem) that Spring Data Redis is causing issues here, I am going to close this ticket.

If you feel this analysis/assessment is in error, then feel free to reopen this ticket and attach a reproducible example of the problem.

Thank you!
