### ISSUE TITLE
Clarification on LettuceConnectionFactory using command timeout for RedisURI connector

### ISSUE THREAD

**Issue by akk202** [spring-projects/spring-data-redis#2544]
We are using spring-data-redis with Lettuce, shared connection, with the following settings:
````
connectionTimeout = 5s (set as part of SocketOptions)
commandTimeout = 200ms
autoReconnect = true
disconnectBehavior = REJECT_COMMANDS
````

While running through a node failover test, we noticed that connection attempts timeout at around 200 ms resulting in off-loading our calls to backend APIs raising alarms. We would like to maintain 200ms command execution timeout during normal operations, however during connectivity issues we would like to ensure 5s window for connection establishment ( autoReconnect retry delay).

We are migrating from Jedis to Lettuce within the spring-data-redis ecosystem, and with the following Jedis configurations:
````
connectionTimeout = 5s
readTimeout = 200ms
maxRetries = 5
````
Since Jedis is single-threaded, we are using a pool of connections (which is something we are trying to move away from managing). We are noticing 5s waiting period before connection retry during node failover test. **Our SLA is acceptability for our app to not respond for 30s-1min but must ensure not to increase off-loading calls to our backend APIs.**

While trying to go over `LettuceConnectionFactory`, specifically `createRedisURIAndApplySettings`, I noticed commandTimeout being set in the `RedisURI.Builder`. Is there any capability to override this setting to use connection timeout, or may be I'm misconstruing how Lettuce connections are established? or a better recommendation in tuning our connection settings with Lettuce so as to not eagerly off-load calls to our backends during a node failover activity?

````
private RedisURI createRedisURIAndApplySettings(String host, int port) {

	RedisURI.Builder builder = RedisURI.Builder.redis(host, port);
        ....
	builder.withTimeout(clientConfiguration.getCommandTimeout()); // can this be overriden?

	return builder.build();
}
````

`TimeoutSource` may be a potential solution? but we are trying our best not add client specific customization hooks and boilerplate.

**Comment by mp911de** [comment]
`TimeoutOptions` and `TimeoutSource` would be good candidates for customization hooks. You can provide these via `ClientOptions`. The difficulty will probably be that you need to correlate a disconnected state with the timeout source, as `ClientOptions` are shared across multiple connections.
