### ISSUE TITLE
ReactiveStreamOperations not support addAll

### ISSUE THREAD

**Issue by yangwenliang123** [spring-projects/spring-data-redis#2548]
ReactiveStreamOperations not support addAll

**Comment by mp911de** [comment]
If you would like us to spend some time helping you, please spend some time describing what you're asking for and what command `addAll` should map to.

**Comment by yangwenliang123** [comment]
Redis Stream XADD key field value [field value ...]

**Comment by yangwenliang123** [comment]
imFriendService.findFriendByUserId(userId)
                .flatMap(imFriend -> reactiveRedisTemplate.opsForStream().add(MapRecord.create("key", imFriend.toMap())))；
This may have performance issues,i need batch add redis stream.
