### ISSUE TITLE
Make `LettuceObservationContext` public to use it with Observation Predicates

### ISSUE THREAD

**Issue by Mitsuder** [spring-projects/spring-data-redis#2550]
https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/connection/lettuce/observability/LettuceObservationContext.java#L32

It is impossible to use this class and span data it stores to filter certain spans like this: https://openvalue.blog/posts/2022/12/16/tracing-in-spring-boot-2-and-3/#:~:text=Observation%20predicates

**Comment by mp911de** [comment]
We made the context public for the time being. With the next release, the observation code will be deprecated in favor of the observation code shipped by the Lettuce driver.

**Comment by Mitsuder** [comment]
Appeared that the LettuceObservationContext is empty at the moment of interception by an ObservationPredicate and it is impossible to determine what command is being executed.
