### ISSUE TITLE
RedisReadOnlyException after restarting the docker container

### ISSUE THREAD

**Issue by jedevelop** [spring-projects/spring-data-redis#2566]
Hi, I have a problem with redis connection after failover process.

When I stop my redis container, failover process is occurs through 60s (down-after-milliseconds). Then I start redis container and try to send commands for writing. RedisReadOnlyException is occurs.

I use RedisSentinelConfiguration, LettuceConnectionFactory, NOT cluster configuration. 
1 master node, 2 replicas and sentinel container on the each node.
replicaHost1:6379 (master as default), replicaHost2: 6379, replicaHost3:6379
sentinelHost1:26379, sentinelHost2:26379, sentinelHost3:26379

When failover process is occurs, my microservice still think that master is replicaHost1 although master is changed either replicaHost2 or replicaHost3.

Help, please

**Comment by mp911de** [comment]
If you failover manually, then there's no way for the driver to know that you've failed over the cluster. 
The Lettuce driver provides also a more elaborate connectivity option with Master/Replica, where the driver subscribes to the Sentinel Pub/Sub channel and listens for config changes. This however, comes at the cost of additional connections.

**Comment by jedevelop** [comment]
Yes, I'm using the Master/Replica API, my lettuce config listens for two types of events with SentinelTopologyRefresh (TopologyRefreshMessagePredicate, SentinelReconnectMessagePredicate), but that doesn't help me. When a disconnect occurs, my application still writes to the old master.

**Comment by mp911de** [comment]
This is then rather a Lettuce driver issue.
