### ISSUE TITLE
Are there any plans to add redis-stack support to spring-data-redis?

### ISSUE THREAD

**Issue by heoYH** [spring-projects/spring-data-redis#2576]
There are various modules in redis-stack. (https://redis.io/docs/stack)

For example, modules like search make Redis more versatile.

Currently, spring-data-redis does not support redis-stack.

I wonder if you have any plans to apply.

If there is no plan, I wonder if there is a plan to support lettuce's custom command function. (https://lettuce.io/core/release/reference/#_custom_commands)

**Comment by mp911de** [comment]
No, we do not plan to extend Spring Data Redis to support Redis Stack.

You can use Lettuce custom commands by obtaining the native Lettuce connection from `LettuceConnection`.
