### ISSUE TITLE
JedisClusterKeyCommands#restore cause thread blocked

### ISSUE THREAD

**Issue by piecebook** [spring-projects/spring-data-redis#2589]
https://github.com/spring-projects/spring-data-redis/blob/ca1fc3043ac7948f09b19d69ba2ca6a013b71c08/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterKeyCommands.java#L410
Hello,
  I got a problem in `JedisClusterKeyCommands#restore`. In `executeCommandOnSingleNode` a connection has acquired and pass to the lambda, but the lambda try to acquire an other connection when `replace`  was true.  It seems to cause thread blocked when the connection pool is exhausted.
![image](https://github.com/spring-projects/spring-data-redis/assets/20704443/b552ed33-bc4a-4b2b-b156-dbba40c71f6d)

**Comment by mp911de** [comment]
You're right, this is a bug on our side. We need to move the `connection.execute` call out of the `executeCommandOnSingleNode` method.
