### ISSUE TITLE
Add a constructor with `Module` to `GenericJackson2JsonRedisSerializer`

### ISSUE THREAD

**Issue by broaden-horizon** [spring-projects/spring-data-redis#2601]
Adding Add a constructor with Module to `GenericJackson2JsonRedisSerializer` would be convenient.

When I tried to register just `JavaTimeModule` to an ObjectMapper of `GenericJackson2JsonRedisSerializer`, I had to configure it from scratch like below.

```
  @Bean
  @Primary
  public ObjectMapper objectMapper() {
    ObjectMapper mapper = new ObjectMapper();
    GenericJackson2JsonRedisSerializer.registerNullValueSerializer(mapper, null);
    StdTypeResolverBuilder builder = new ObjectMapper.DefaultTypeResolverBuilder(ObjectMapper.DefaultTyping.EVERYTHING,
        mapper.getPolymorphicTypeValidator());
    builder = builder.init(JsonTypeInfo.Id.CLASS, null);
    builder = builder.inclusion(JsonTypeInfo.As.PROPERTY);
    mapper.setDefaultTyping(builder);
    mapper.registerModule(new JavaTimeModule());
    return mapper;
  }
```

If the configuration already defined in a default constructor of `GenericJackson2JsonRedisSerializer` can be reused for adding `Module`s, I think it could make codes simpler and easier.

So it would look like below.

```
public GenericJackson2JsonRedisSerializer(List<Module> modules) {
    this((String) null);
    for (Module module : modules) {
        this.mapper.registerModule(module);
    }
}
```

**Comment by jxblum** [comment]
Exposing types from other libraries, such as Jackson, is not in the best interests of  _Spring Data Redis_.  A few reasons include, but are not limited to:

1) The contracts of library types (for example, enabling additional capabilities of Jackson through the "registration" of additional Jackson `Modules` on a Jackson `ObjectMapper`) are subject to change in the future, and. more importantly...
2) There are more ways to configure/customize a Jackson `ObjectMapper` than simply registering additional `Modules`,  such as enable or disabling mapping or de/serialization features, and so on.

A better approach, particularly in the case of configuring and customizing the "internal" Jackson `ObjectMapper` initialized by the `GenericJackson2JsonRedisSerializer` constructors that do not accept a user-provided Jackson `ObjectMapper`, is to expose an API that allows users to provide a callback (after construction) to further configure/customize the "internal" Jackson `ObjectMapper`.

For example:

```java
public GenericJackson2JsonRedisSerializer configure(Consumer<ObjectMapper> configurer) {
  // ...
}
```
