### ISSUE TITLE
When the redis key that TTL has expired is decremented, this key is regenerating with its TTL of -1.

### ISSUE THREAD

**Issue by Nesrinasan** [spring-projects/spring-data-redis#2607]
Hi,
I want to talk about a situation I noticed about the decrement method.

I have a redis key that have 10sec TTL and value is 2.
My case:

1. The user is sent to redis cache with a TTL time of 10 seconds.
2. User calls a service and Service response takes more than 10 seconds and timeout is received.
3. however, since the TTL is 10 seconds, the user on the redis is also deleted when the timeout is taken from the service.
4. so, the value in the redis is desired to be reduced by one and the decrement method is called.
5. A new value with TTL value of -1 is sent to redis with the decrement method called for a key that is no longer in redis.
6. This causes problems with streams such as your rate limit.

I wrote a new method that is including a if condition to check if this key exists in redis.

method :

```
org.springframework.data.redis.core.DefaultValueOperations

@OverRide
public Long decrementIfExist(K key) {

	V valueX = get(key);
	if(valueX != null){
		return decrement(key);
	}
	return -1l;
}
```

test of method:

```
org.springframework.data.redis.core.DefaultValueOperationsIntegrationTests

@ParameterizedRedisTest 
void testDecrementIfExist() {

	K key = keyFactory.instance();
	V value = valueFactory.instance();

	assumeThat(value).isInstanceOf(Long.class);

	valueOps.set(key, value);
	assertThat(valueOps.decrementIfExist(key)).isEqualTo(Long.valueOf((Long) value - 1));

	valueOps.getAndDelete(key);

	assertThat(valueOps.decrementIfExist(key)).isEqualTo(Long.valueOf((Long) value -1));
}
```

If you let me, I want to add this method. Thanks.

**Comment by mp911de** [comment]
Thanks for reaching out. You see the regular behavior of the Redis `DECR` command that creates a key if calling `DECR` (or `INCR`):

```
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> decr foo
(integer) -1
127.0.0.1:6379> keys *
1) "foo"
127.0.0.1:6379>
```

We cannot perform the check as interleaving calls might delete the key after the existence check and before us issuing the decrement command as this would result again in the same behavior.

You can resolve your situation by using Lua scripts as these run atomically with the possibility to include conditional flows.

**Comment by Nesrinasan** [comment]
Hi,
Firstly Thank you for your quick response

Actually I want to speficy that: 
However, persist data occurs when the TTL is exhausted anywhere in the code stream and the decrement method is called afterwards. But I thought we could minimize this with an if block.
Yes of course when the code come to inside “if” condition the redis key is removed from cache and after calling decr method, it will work same flow. 
And of course we can apply Manuel condition our projects. However I think that there will be problems in cases where TTL is important, such as the use of the DEC or INC method without knowing this situation and the rate limit scenario. 

You may not find it right to proceed with the solution proposal I have mentioned, maybe a more effective solution can be considered. If such an update is considered in this project, I think it will be very useful. Thanks.
