### ISSUE TITLE
for old version TTL

### ISSUE THREAD

**Issue by LoliWolf** [spring-projects/spring-data-redis#2618]
how can I set ttl for every method in springboot2.7 when using @Cacheable

**Comment by jxblum** [comment]
TTL is not configured per `@Cacheable` service method in the Spring-managed (`@Service`) beans of your application, but rather per `Cache`. Then, a specific `Cache` can be declared for a particular service method using the `@Cacheable` annotation.

Read Spring Data Redis's [documentation](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:support:cache-abstraction) on how to configure a `Cache`, and specifically TTL for a `Cache`. The available configuration for a `Cache` can be found in `RedisCacheConfiguration` [Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/cache/RedisCacheConfiguration.html).

You can use SD Redis's `RedisCacheManager.RedisCacheManagerBuilder` class to configure each `Cache` instance, required by your application, independently, using either the `withCacheConfiguration(cacheName, :RedisCacheConfiguration)` method ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/cache/RedisCacheManager.RedisCacheManagerBuilder.html#withCacheConfiguration(java.lang.String,org.springframework.data.redis.cache.RedisCacheConfiguration))) for a "named" `Cache` or the `withCacheConfiguration(:Map<String, RedisCacheConfiguration>)` method ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/cache/RedisCacheManager.RedisCacheManagerBuilder.html#withInitialCacheConfigurations(java.util.Map))) for all "named" `Cache` instance at once.

In the context of Spring Boot, you can declare a bean of type `o.s.boot.autoconfigure.cache.RedisCacheManagerBuilderCustomizer` ([Javadoc](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/cache/RedisCacheManagerBuilderCustomizer.html)) to customize the `RedisCacheManagerBuilder` used to build the SD Redis `RedisCacheManager` and configure each Redis `Cache` instance, as needed.

So, if you have a "Users" (Redis) `Cache` instance with specific TTL requirements (and configuration), then you can configure the "Users" `Cache` on a service method as follows:

```java
@Cacheable(cacheNames = "Users")
public User findByUsername(String username) {
  // ...
?
```
