### ISSUE TITLE
Can not find a (Map) Key deserializer for type in redis using GenericJackson2JsonRedisSerializer 

### ISSUE THREAD

**Issue by yulu-deer** [spring-projects/spring-data-redis#2632]
Hi,
I'm using spring-data-redis:2.2.3.
I have stored a data type as Object in redis and using GenericJackson2JsonRedisSerializer.
This object contains a Map attribute, the key of this Map is my customized object.
When I try to retrieve this object from Redis, this error will be reported.
`Can not find a (Map) Key deserializer for type [simple type, class …]`

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by yulu-deer** [comment]
I found that the root cause of this issue is the issue of deserialization of Jackson databind. Therefore, I went to the Jackson databind project to request assistance. Thank you for your reply.
