### ISSUE TITLE
Code endless loop, it will run forever, in fact the total number of redis data is 1000 only

### ISSUE THREAD

**Issue by zzy444626905** [spring-projects/spring-data-redis#2682]
public static void scanMatch(RedisTemplate redisTemplate, String matchKey) {
        long count = 0;
        StopWatch stopWatch = new StopWatch();
        stopWatch.start("scan key:" + matchKey);

        RedisConnectionFactory connectionFactory = redisTemplate.getConnectionFactory();
        try (RedisClusterConnection clusterConnection = connectionFactory.getClusterConnection();) {
            Iterable<RedisClusterNode> redisClusterNodes = clusterConnection.clusterGetNodes();
            ScanOptions scanOptions = ScanOptions.scanOptions().match(matchKey).count(Integer.MAX_VALUE).build();
            for (RedisClusterNode next : redisClusterNodes) {
                try (Cursor<byte[]> scan = clusterConnection.scan(next, scanOptions);) {
                    while (scan.hasNext()) {
                        count++;
                        if (count % 100000 == 0) {
                            System.out.printf("key：%s，count：%s\n", new String(scan.next()), count);
                        }
                    }
                }
            }

            System.out.printf("total count：%s\n", count);
            stopWatch.stop();
            System.out.println(stopWatch.prettyPrint());
        }
    }

console output :

...
...
key：zzz:read:datakeys:6ce7c9a8-9192-4e10-a5b9-aba048b045dd，count： 31947300000
key：zzz:read:datakeys:3bc47056-68bd-4de5-bbfd-d3fce8c3ee6d， count： 31947400000
key：zzz:read:datakeys:c7452fbf-56e3-4d4f-aedd-1efface2ac86，     count： 31947500000

**Comment by mp911de** [comment]
You're using the `Cursor` (`Iterator`) API wrong as the code advances via `scan.next()` only if  `count % 100000` equals `0`. The loop should rather look like:

```java
while (scan.hasNext()) {
	count++;
	scan.next();
}
```

**Comment by zzy444626905** [comment]
> if (count % 100000 == 0) {
>                         System.out.printf("key：%s，count：%s\n", new String(scan.next()), count);
>                     }

Big boss, Thank you very much!  I see.

**Comment by zzy444626905** [comment]
> You're using the `Cursor` (`Iterator`) API wrong as the code advances via `scan.next()` only if `count % 100000` equals `0`. The loop should rather look like:
> 
> ```java
> while (scan.hasNext()) {
> 	count++;
> 	scan.next();
> }
> ```

Big boss, thank you very much! I see.
