### ISSUE TITLE
Add support to (Left|Right) Pop N elements using `ReactiveListOperations`

### ISSUE THREAD

**Issue by ericsouza** [spring-projects/spring-data-redis#2692]
Hey, thanks for this amazing library!

I was converting my blocking ListOperations that uses a leftPop(key, count) to a reactive version. But it seems that the ReactiveListOperations does not have an option to pop N elements. Is there any reason for that?

**Comment by mp911de** [comment]
Seems like an oversight on our end. `leftPop` was introduced with version 2.6.0, there`s even a `lPop` method on the list connection commands interface.
