### ISSUE TITLE
No ping packet was sent during the subscription operation.

### ISSUE THREAD

**Issue by pengyongqiang666** [spring-projects/spring-data-redis#2695]
No ping packet was sent during the subscription operation. In the event of abnormal termination of the TCP connection, the subscription connection will become invalid and cannot be re-established.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by pengyongqiang666** [comment]
@Bean
    public RedisMessageListenerContainer redisMessageListenerContainer(RedisConnectionFactory redisConnectionFactory) {
        RedisMessageListenerContainer redisMessageListenerContainer = new RedisMessageListenerContainer();
        redisMessageListenerContainer.setConnectionFactory(redisConnectionFactory);
        redisMessageListenerContainer.addMessageListener((message, pattern) -> {
            log.info("msg:{}", message);
        }, new ChannelTopic("testChannel"));
        return redisMessageListenerContainer;
    }


For example, in the event of a network disconnection without any TCP FIN packets, which can result in the subscription not being aware of it, it is necessary to periodically send ping packets on the subscription connection.

**Comment by mp911de** [comment]
Thanks for the detail. Spring Data Redis builds on top of Redis drivers and doesn't handle the transport layer. Please look into your driver's configuration to apply KeepAlive or retransmit options.
