### ISSUE TITLE
Constants should be created for the duplicated String literals

### ISSUE THREAD

**Issue by kapilgahlot1998** [spring-projects/spring-data-redis#2713]
There are multiple duplicate String literals present in the classes. I think those should be converted to constants. 
i.e. `BitFieldSubCommands` class have "Offset must not be null" literal which has been used 6 times in the class.

FYI I am new to open source contribution. Not sure are we allowed to open the issues for refactoring the code. I have read the contribution guidelines and I think Its not mentioned anywhere. So opening this issue.

**Comment by jxblum** [comment]
Java String literals are 1) Immutable and 2) allocated to the Java String Pool in the JVM Heap. Therefore the JVM can optimize duplicate String literals by only storing the literal once and using a reference everywhere the String literal appears in code.

The nice [blog post](https://www.baeldung.com/java-string-pool) by **bealdung** explains it nicely.
