### ISSUE TITLE
Executed in pipeline in Reactive context?

### ISSUE THREAD

**Issue by yos1p** [spring-projects/spring-data-redis#2715]
Hi, I wonder if it's possible to have pipelining in reactive context?

One use case I have is to use MSET with TTL for each key, which is also not possible in one command. So I was thinking if it's possible to be done in reactive context.

So far, what I have done is simply wrapping it inside a Mono.defer(). I wonder if it will be part of ReactiveRedisOperation

**Comment by mp911de** [comment]
Reactive usage always uses pipelining (i.e. not waiting until command completion) if you set up the reactive pipeline that way up to subscribe to multiple `Publisher`s instead of awaiting completion of the previous one.
