### ISSUE TITLE
`spring.data.redis.timeout` breaks after setting `ClientOptions` in `LettuceClientConfigurationBuilderCustomizer`

### ISSUE THREAD

**Issue by jhengy** [spring-projects/spring-data-redis#2727]
## Bug Report
We are using `ReactiveStringRedisTemplate` to execute redis operations. After setting `ClientOptions` through `LettuceClientConfigurationBuilderCustomizer`, the configured  `spring.data.redis.timeout` value seems to be broken.

## Current Behaviour
The redis HGET call via `ReactiveStringRedisTemplate` seems to wait indefinitely when the Redis server hangs, although the configured timeout has been exceeded. This likely applies to all redis commands in general.

## Expected Behaviour
Redis Command Timeout exception should be thrown after the configured timeout when redis server hangs.

## Supporting Information
I have created a simple spring boot application to reproduce the bug and noted down the observations under https://github.com/jhengy/spring-redis-timeout-bug

**Comment by jhengy** [comment]
@YeGaung

**Comment by jhengy** [comment]
@jxblum sflr, responding to [your previous comment](https://github.com/spring-projects/spring-data-redis/issues/2698#issuecomment-1710774446), I managed to reproduce the bug using a simple spring boot demo app.

**Comment by mp911de** [comment]
Timeouts for the reactive API are controlled through `TimeoutOptions`, which is configured through `ClientOptions`. If you're setting own `ClientOptions`, make sure to set `timeoutOptions` to `TimeoutOptions.enabled()`.

As this is how the client is designed, there's nothing we can do here.

**Comment by jxblum** [comment]
@jhengy - Thank you for providing an example/test.

As @mp911de (Mark) described in his [comment](https://github.com/spring-projects/spring-data-redis/issues/2727#issuecomment-1752432650)above, you need to do the work of Spring Boot _auto-configuration_ if you are going to override and set your "own" `ClientOptions` instance using the Spring Boot `LettuceClientConfigurationBuilderCustomer` object as you have done in your Spring Boot application configuration ([here](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/java/com/example/demo/redistimeoutbug/RedisConfig.java#L14-L22)).

You definitely "overrode" the `ClientOptions` instance (as seen, [here](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/java/com/example/demo/redistimeoutbug/RedisConfig.java#L20), in your own [application configuration](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/java/com/example/demo/redistimeoutbug/RedisConfig.java)) that would have been [provided by](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.java#L143-L181) Spring Boot's _auto-configuration_ in this case. Spring Boot creates/configures the `ClientOptions` instance when creating/initializing the `LettuceClientConfiguration` object, [here](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.java#L112), which is before your (and any) `LettuceClientConfigurationBuilderCustomizer(s)` get applied by Spring Boot (see [here](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.java#L114)).

Carefully [observe](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.java#L163) where Spring Boot sets the `TimeoutOptions` on the `ClientOptions` instance during creation. This is precisely what @mp911de is referring to.

Both `ClientOptions` ([Javadoc](https://lettuce.io/core/release/api/io/lettuce/core/ClientOptions.html)) and `TimeoutOptions` ([Javadoc](https://lettuce.io/core/release/api/io/lettuce/core/TimeoutOptions.html)) are Lettuce Redis driver specific classes.

Additionally, the `spring.data.redis.timeout` property ([this](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/resources/application.yml#L13)) along with `application.yml` ([this](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/resources/application.yml)) along with your `LettuceClientConfigurationBuilderCustomizer` are all Spring Boot specific things, and nothing to do with Spring Data Redis in particular.

Just based on an eyeball observation (I did test or try this), you should be able to do the following in your `RedisConfig`:

```java
@Configuration
public class RedisConfig {

    @Bean
    @ConditionalOnProperty("customize-client-options")
    public LettuceClientConfigurationBuilderCustomizer tcpKeepAliveReplicaBuilderCustomizer(
        RedisProperties redisProperties) {

        ClientOptions clientOptions = ClientOptions.builder()
            .timeoutOptions(TimeoutOptions.enabled(redisProperties.getTimeout())
            .build();

        return builder -> builder.clientOptions(clientOptions);
    }
}
```

Notice the use of the `RedisProperties` bean isntance that is provided by Spring Boot. This object represents the "spring.data.redis.*" properties from your `application.yml` file.

See `RedisProperties` [source](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/RedisProperties.java#L36-L37) from Spring Boot.

Therefore, the (`Duration`) value of the "_spring.data.redis.timeout_" property ([here](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/resources/application.yml#L13)) from your `application.yml` file will come from `RedisProperties.getTimeout()`.

Hope this helps!

**Comment by jhengy** [comment]
@jxblum, I'd like to confirm that [setting `TimeoutOptions.enabled()` under `ClientOptions`](https://github.com/jhengy/spring-redis-timeout-bug/commit/15f7894d09d47ed6d63122b2965e8828d3d07e03) fixes the issue. 

Let me explain the context a bit more, our use case is to configure TCP keepalive for Redis, we did so by [customising the ClientOptions.SocketOptions](https://github.com/jhengy/spring-redis-timeout-bug/compare/main...fix). However, it seems that it breaks other configurations [provided by](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.java#L143-L181) Spring Boot's auto-configuration, e.g. ClientOptions.timeoutOptions, ClientOptions.sslOptions. May I know if there is a better way to configure tcp keepalive without interfering with `LettuceConnectionConfiguration` auto configuration?

**Comment by jhengy** [comment]
@mp911de If I may, I'd like to follow up with another question. Given the current set up[ without setting timeoutOptions to TimeoutOptions.enabled() under clientOptions](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/java/com/example/demo/redistimeoutbug/RedisConfig.java#L20), I would expect that my [spring.data.redis.timeout](https://github.com/jhengy/spring-redis-timeout-bug/blob/main/src/main/resources/application.yml#L13) to have no effect at all. However, it seems that it does have some effect on connection initialization. The evidence can be shown by doing the following:
1. spin up redis locally
2. start spring boot application (with customized )
3. immediately execute DEBUG SLEEP 30
4. curl localhost:8080/hget-reactive
5. observe that redis command timeout does get triggered after 3s with the following stack
```
2023-10-10T10:07:18.114+08:00 ERROR 40255 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis] with root cause

io.lettuce.core.RedisCommandTimeoutException: Connection initialization timed out after 3 second(s)
	at io.lettuce.core.protocol.RedisHandshakeHandler.lambda$channelRegistered$0(RedisHandshakeHandler.java:67) ~[lettuce-core-6.2.6.RELEASE.jar:6.2.6.RELEASE]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

This seems to be one scenario in which `spring.data.redis.timeout` still takes effect without setting `TimeoutOptions.enabled()`. May I know how can we understand this and if there is any other scenario in which the configured timeout will take effect? Thanks a lot.

**Comment by mp911de** [comment]
Lettuce timeouts are a bit more involved. During connection initialization, the driver sends commands to Redis and the commands aren't guarded by the per-command timeout (because there's no logical connection yet) but rather the connection handshake is guarded by the connection timeout.

**Comment by jxblum** [comment]
@jhengy - Thank you for sharing more details.

Regarding:

> _May I know if there is a better way to configure TCP `keep-alive` without interfering with `LettuceConnectionConfiguration` auto-configuration?_

The first place to look is if Spring Boot itself supplies property configuration for (example) Redis [[Socket] connection] settings, such as the TCP `Socket` `keep-alive`.

> NOTE: See property configuration for Redis beginning [here](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.data.redis.client-name).

Of course, in this particular case, Spring Boot does not. In general, Spring Boot will not necessarily cover all manners of configuration via properties, but it is best to check here first, anyway.

Although, maybe not completely ideal, you could do something like the following:

GIVEN:

```java
package example.app.redis.lettuce.client.config;

import io.lettuce.core.ClientOptions;
// ...

class CustomClientOptions extends ClientOptions {

    private final SocketOptions socketOptions;

    CustomClientOptions(@NotNull ClientOptions original, @NotNull SocketOptions socketOptions) {
        super(original);
        this.socketOptions = socketOptions;
    }

    @Override
    public SocketOptions getSocketOptions() {
        this.socketOptions;
    }
}
```

THEN:

```java
@SpringBootConfiguration
class MyApplicationRedisConfiguration {

    @Bean
    LettuceClientConfigurationBuilderCustomizer clientConfigurationBuilderCustomizer(
            RedisProperties properties) {

        SocketOptions customSocketOptions = SocketOptions.builder()
            ... // all your custom settings here (e.g. keep-alive)
            .connectTimeout(properties.getConnectTimeout()) // be careful of null
            .build();

        return builder -> {

            LettuceClientConfiguration configuration = builder.build();

            // "original" will be the ClientOptions created & auto-configured by Spring Boot
            ClientOptions original = configuration.getClientOptions()
                .orElseThrow(() -> new IllegalStateException("Expected ClientOptions");

            builder.clientOptions(new CustomClientOptions(original, customSocketOptions));
        };
    }
}
```

I am sure you can think of other ideas as well.
