### ISSUE TITLE
add ValueOperation setIFAbsent with expiry for key

### ISSUE THREAD

**Issue by XKXK1** [spring-projects/spring-data-redis#2730]
I already ran into the problem of not being able to set an expiry time for a key when using the `setIfAbsent` method for the `ValueOperation` multiple times now.

What do you think about adding the possibility to set the expiry time when using `setIfAbsent` `ValueOperation`?

It is possible to execute this directly by doing the following, but not directly using the `ValueOperation`:

```java
redisTemplate.execute((RedisCallback<Object>) connection -> {
            StringRedisConnection stringRedisConn = (StringRedisConnection) connection;
            return stringRedisConn.set(
                "key",
                "locked",
                Expiration.from(Duration.ofSeconds(10)),
                RedisStringCommands.SetOption.SET_IF_ABSENT);
        });
```

**Comment by XKXK1** [comment]
> I'm not sure I follow. Are you referring to `ValueOperations.setIfAbsent(K key, V value, Duration timeout)`?

exactly, and I am not talking about the timeout but about an expiry for the key itself

**Comment by mp911de** [comment]
`setIfAbsent` calls `connection.set(rawKey, rawValue, expiration, SetOption.ifAbsent())` (`SET <key> <value> EX … NX`)

> I am not talking about the timeout but about an expiry for the key itself

The `Duration timeout` parameter translates to the TTL. So I still don't understand what you're asking for.

**Comment by XKXK1** [comment]
Sorry this was a mistake on my side. You are absolutely right. At some point I probably was checking the wrong documentation. Thanks for checking
