### ISSUE TITLE
Why not use V as the value type for an Operations?

### ISSUE THREAD

**Issue by junghoon-vans** [spring-projects/spring-data-redis#2740]
Some operations related to **set** or **zset** use `Object` as the value type.

```java
public Boolean isMember(K key, Object o)
```

A typical example is `DefaultSetOperations#isMember`.

```java
public Boolean isMember(K key, V value)
```

I think it could be modified to use a `V` type instead of an `Object`.

Why do some operations use `Object` instead of `V` as the value type?
I'm curious about what cases require the Object type.

**Comment by junghoon-vans** [comment]
@brido4125

**Comment by mp911de** [comment]
These methods pre-date (2010) the presence of everyone working on the team. 

As far as I can see, these methods align with `Collection.contains(Object)` that uses `Object` instead of the collection element type.

**Comment by junghoon-vans** [comment]
@mp911de Aha, so that means it follows Java's data structure API as closely as possible.
Thank you for your quick response.
