### ISSUE TITLE
Potential race condition in listener adding code

### ISSUE THREAD

**Issue by o-l-o** [spring-projects/spring-data-redis#2755]
I'm pretty sure that there is potential race condition in the following code:
```java
               Set<Topic> set = listenerTopics.get(listener);

		if (set == null) {
			set = new CopyOnWriteArraySet<>();
			listenerTopics.put(listener, set);
		}
```

The solution could be to replace it with something like this:
```java
Set<Topic> set = listenerTopics.computeIfAbsent(listener, $ -> new CopyOnWriteArraySet<>());
```

https://github.com/spring-projects/spring-data-redis/blob/fc9f9d8e5cda0595349255c9e9a1332a52001c27/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L649

**Comment by jxblum** [comment]
Yes!

Any [compound action](https://github.com/spring-projects/spring-data-redis/blob/3.2.0-RC1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L648-L655) (i.e. the `Map` `get(:MessageListener)`, followed by a `put(:MessageListener, :Set<Topic>)`, and then `addAll(:Collection<Topic>)`) is going to necessarily have possible _race conditions_ if the affected area of code is 1) accessed by multiple Threads and 2) is not properly guarded by a lock, even if the underlying data structure(s) (`Map` & `Set`) are Thread-safe, which in this case, they are (a `ConcurrentHashMap` [here](https://github.com/spring-projects/spring-data-redis/blob/3.2.0-RC1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L159) and `CopyOnWriteArraySet` [here](https://github.com/spring-projects/spring-data-redis/blob/3.2.0-RC1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L651)).

Given 1) the [Javadoc](https://github.com/spring-projects/spring-data-redis/blob/3.2.0-RC1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L91-L93) on the `RedisMessageListenerContainer` states the `addMessageListener(..)` method can be called concurrently without external synchronization, and 2) the `addMessageListener(..)` method [calls](https://github.com/spring-projects/spring-data-redis/blob/3.2.0-RC1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L91-L93) the `private addListener(..)` method, then I'd say the code in question has _race conditions_.

**Comment by rotilho-bv** [comment]
I may also being affected by race condition in RedisMessageListenerContainer. It doesn't happens while debugging the shutdown hook but it happens every single time I don't. The thread dump makes me believe the error is caused by race condition during re-registration during shutdown due to messages being sent.
