### ISSUE TITLE
Too many CacheEvaluationContext instances

### ISSUE THREAD

**Issue by liudaac** [spring-projects/spring-data-redis#2764]
Recently, I discovered a phenomenon where there is a large amount of CacheEvaluationContext instances in the jmap histo from my Spring Boot 2.7.15 application. When I examined the creation points in the source code, I found that the creation of this instance is triggered by three methods in CacheOperationContext: canPutToCache, generateKey, and isConditionPassing. The triggering conditions for these methods are StringUtils.hasText(unless), StringUtils.hasText(this.metadata.operation.getKey()), and StringUtils.hasText(this.metadata.operation.getCondition()) respectively. How should I optimize to reduce the number of CacheEvaluationContext instances?

**Comment by mp911de** [comment]
Thanks for reaching out. `CacheEvaluationContext` is provided by Spring Framework (similar to `CacheOperationContext`). Please file a ticket at https://github.com/spring-projects/spring-framework/issues.
