### ISSUE TITLE
Where is the adaptor's error handling?

### ISSUE THREAD

**Issue by junghoon-vans** [spring-projects/spring-data-redis#2765]
The methods in `RedisKeyValueAdapter` split the request into multiple commands,
However, I don't see any code for failure handling.

```java
connection.hMSet(objectKey, rdo.getBucket().rawMap());

if (isNew) {
    connection.sAdd(toBytes(rdo.getKeyspace()), key); // Can't fail?
}
```

For example, if the put method is called, the object has been saved via `hMset`,
but the keyspace operation via `sAdd` may be missing.

I'm wondering if I'm missing something that should be exception-handled,
or if there's some other reason it doesn't need to be handled.

**Comment by mp911de** [comment]
There's no failure handling. Any failures result in partially executed commands. We do not roll back nor we have atomicity.

**Comment by junghoon-vans** [comment]
@mp911de So, if a particular command fails, it should be thrown as a runtime exception in the failed operation, correct?

**Comment by mp911de** [comment]
Yes, exactly. To some extent, these are consequences of using Redis as store. If there was e.g. a network partition, there would be no chance of recovering quickly and so we accept partial state as outcome.

**Comment by junghoon-vans** [comment]
@mp911de I understand what you mean. Thank you for detailed and quick response.
I'll close this issue.
