### ISSUE TITLE
`RedisMessageListenerContainer` resubscribe using Jedis fails after exception

### ISSUE THREAD

**Issue by ssu888** [spring-projects/spring-data-redis#2782]
![image](https://github.com/spring-projects/spring-data-redis/assets/45167549/c5fc0a58-4fc9-46bd-9c54-1ae938a25218)
When redis is failing at this point and the program is running to the
' connectionFactory.getConnection()'
then it will report a RedisConnectionFailureException;
![image](https://github.com/spring-projects/spring-data-redis/assets/45167549/c94c4f0a-09c8-465a-830c-b6040ee0bcb6)
But it's caught by the outer catch, which causes it to not go to the inner 'handleSubscriptionException' method, resulting in an inability to keep retrying

**Comment by mp911de** [comment]
Thanks for raising the issue. I can confirm that problem and we need to fix it.
