### ISSUE TITLE
RedisCacheWriter.lockingRedisCacheWriter deadlock

### ISSUE THREAD

**Issue by dayuange123** [spring-projects/spring-data-redis#2793]
RedisCacheWriter lockingRedisCacheWriter could lead to a deadlock.
That led to my database connection  leak and i use HikariCP.

Here is my configuration:
        RedisCacheConfiguration defaultCacheConfig = RedisCacheConfiguration.defaultCacheConfig()
                .entryTtl(Duration
                        .ofMinutes(10L));
	    return RedisCacheManager.builder(RedisCacheWriter.lockingRedisCacheWriter
                        (userCacheRedisConnectionFactory, BatchStrategies.scan(1000)))
//	    return RedisCacheManager.builder(userCacheRedisConnectionFactory)
                .cacheDefaults(defaultCacheConfig)
                .transactionAware()
                .build();

**Comment by dayuange123** [comment]
<img width="749" alt="image" src="https://github.com/spring-projects/spring-data-redis/assets/34415174/41163089-9664-41aa-afcd-68fff43764de">
endless loop here

**Comment by mp911de** [comment]
Technically, it isn't a deadlock as there aren't two competing locks waiting for each other. It is rather that the lock isn't being unlocked. 
If the lock doesn't time out, then this is expected behavior.

As of Spring Data Redis 3.2, you can configure a locking cache writer that sets a TTL on the lock:

```java
TtlFunction lockTtl = (key, value) -> Duration.ofSeconds(10);  
RedisCacheWriter.lockingRedisCacheWriter(connectionFactory, Duration.ofMillis(50), lockTtl, BatchStrategies.scan(50));
```

**Comment by bert82503** [comment]
> Technically, it isn't a deadlock as there aren't two competing locks waiting for each other. It is rather that the lock isn't being unlocked. If the lock doesn't time out, then this is expected behavior.
> 
> As of Spring Data Redis 3.2, you can configure a locking cache writer that sets a TTL on the lock:
> 
> ```java
> TtlFunction lockTtl = (key, value) -> Duration.ofSeconds(10);  
> RedisCacheWriter.lockingRedisCacheWriter(connectionFactory, Duration.ofMillis(50), lockTtl, BatchStrategies.scan(50));
> ```

I think, the root cause of this issue is use `BatchStrategies.keys()` as default BatchStrategy in RedisCacheWriter.
It need to change `BatchStrategies.scan(batchSize)` as default BatchStrategy.

```java
public interface RedisCacheWriter extends CacheStatisticsProvider {
	static RedisCacheWriter nonLockingRedisCacheWriter(RedisConnectionFactory connectionFactory) {
		return nonLockingRedisCacheWriter(connectionFactory, BatchStrategies.keys());
	}

	static RedisCacheWriter lockingRedisCacheWriter(RedisConnectionFactory connectionFactory) {
		return lockingRedisCacheWriter(connectionFactory, BatchStrategies.keys());
	}
}
```

**Comment by bert82503** [comment]
> Technically, it isn't a deadlock as there aren't two competing locks waiting for each other. It is rather that the lock isn't being unlocked. If the lock doesn't time out, then this is expected behavior.
> 
> As of Spring Data Redis 3.2, you can configure a locking cache writer that sets a TTL on the lock:
> 
> ```java
> TtlFunction lockTtl = (key, value) -> Duration.ofSeconds(10);  
> RedisCacheWriter.lockingRedisCacheWriter(connectionFactory, Duration.ofMillis(50), lockTtl, BatchStrategies.scan(50));
> ```

Maybe use `RedisCacheWriter.nonLockingRedisCacheWriter(connectionFactory, BatchStrategies.scan(20))` to better, and run in `ThreadPoolExecutor`.

For example
```java
@Slf4j
@Service("cacheService")
public class CacheServiceImpl implements CacheService {

    /**
     * 并发开关
     */
    private final ConcurrentMap<String, Boolean> concurrentSwitch = new ConcurrentHashMap<>(16);

    private final ExecutorService executorService = new ThreadPoolExecutor(
            1, 1, 5L, TimeUnit.MINUTES,
            new ArrayBlockingQueue<>(1),
            new ThreadFactoryBuilder().setNamePrefix("cache-clean-")
                    .setDaemon(true).build()
    );

    private final RedisConnectionFactory redisConnectionFactory;

    public CacheServiceImpl(
            RedisConnectionFactory redisConnectionFactory
    ) {
        this.redisConnectionFactory = redisConnectionFactory;
        log.info("create CacheServiceImpl");
    }

    @Override
    public boolean cleanCache(CacheKey cacheKey) {
        String keyPattern = cacheKey.getKeyPattern();
        // 避免多次重复地操作
        if (concurrentSwitch.putIfAbsent(keyPattern, Boolean.TRUE) == null) {
            // 异步地执行
            executorService.execute(() -> this.clean(cacheKey));

            return true;
        }
        return false;
    }

    private void clean(CacheKey cacheKey) {
        log.info("cleanCache start, cacheKey={}", cacheKey);
        StopWatch stopWatch = new StopWatch("cleanCache");
        stopWatch.start();
        try {
            this.clean(cacheKey.getCacheName(), cacheKey.getKeyPattern());
        } finally {
            stopWatch.stop();
            log.info("cleanCache end, cacheKey={}, stopWatch={}", cacheKey, stopWatch);
        }
    }

    /**
     * 缓存Redis的历史数据清理
     * <pre>
     * 【批量策略】在线异步地批量扫描匹配删除，每批20个key
     * 先SCAN，再批量DEL
     * 【执行策略】预发环境，业务低峰时期
     * </pre>
     *
     * @see org.springframework.data.redis.cache.RedisCacheWriter#clean
     * @see org.springframework.data.redis.cache.DefaultRedisCacheWriter#clean
     */
    private void clean(String cacheName, String keyPattern) {
        // 【批量策略】SCAN，每批20个key
        RedisCacheWriter redisCacheWriter = RedisCacheWriter.nonLockingRedisCacheWriter(
                redisConnectionFactory, BatchStrategies.scan(20));
        // 先SCAN，再批量DEL
        redisCacheWriter.clean(cacheName, keyPattern.getBytes(StandardCharsets.UTF_8));
    }

}

```

**Comment by mp911de** [comment]
`SCAN` isn't supported by Jedis in a Redis Cluster environment.

**Comment by bert82503** [comment]
> `SCAN` isn't supported by Jedis in a Redis Cluster environment.

Yes, it is right.
But, Using the keys command in a production environment is very dangerous.

However, it is best for us to have a clear understanding of the user's usage scenarios. 😄
First, we are not using Redis Cluster.
Second, the user may not be using Jedis and may be using other clients, such as Redisson, Lettuce.
