### ISSUE TITLE
Using getRequiredAdapter in RedisQueryEngine to avoid NPE

### ISSUE THREAD

**Issue by junghoon-vans** [spring-projects/spring-data-redis#2800]
The `getAdapter` used by the `RedisQueryEngine` logic to get the adapter can return null.
To avoid this, we can use `getRequiredAdapter`.

**Comment by mp911de** [comment]
Did you encounter a NPE or how did you find out about the issue?

**Comment by junghoon-vans** [comment]
@mp911de I didn't experience any NPEs myself, I just thought I should fix anything in the source code that might cause an error. 

I'm currently working on creating a Spring Data Implementation, and in the process I came across this and decided to open an issue.

**Comment by mp911de** [comment]
Alright, thanks for the detail.
