### ISSUE TITLE
Convert an implementation of IndexedData to a Record. 

### ISSUE THREAD

**Issue by junghoon-vans** [spring-projects/spring-data-redis#2806]
Record is Java's inconvenience data class, so it's a great fit for `IndexedData` for holding and passing data.
It's also nice not to have to define `getters` or methods like `hashcode` and `equals`, especially if it changes.

**Comment by christophstrobl** [comment]
Thank you for getting in touch.
While records are a great enhancement, simply switching class to record, especially for public API, breaks, as you probably noticed when creating the PR, existing contracts. 
Therefore I'll close this issue.
