### ISSUE TITLE
Can't get data after setting data using RedisConnection's commands

### ISSUE THREAD

**Issue by PudgeKim** [spring-projects/spring-data-redis#2811]
I'm using StringRedisTemplate (RedisTemplate<String, String>)
```
val connectionFactory = redisTemplate.connectionFactory ?: throw ConnectionFailedException("Redis connection factory is null")
val conn = connectionFactory.connection

val myKey = someKey
val myValue = someValue.toByteArray()

conn.commands().set(myKey.toByteArray(), myValue) // I checked this data from redis
conn.commands().get(myKey) // this returns null!
redisTemplate.opsForValue().get(someKey) // this returns data..!
```

How can I get data using conn.commands?

**Comment by christophstrobl** [comment]
usage of any `byte[]` variant method within the connection bypasses the configured `RedisSerializer` so you'd have to use the same strategy for `set / get`. 

If you'd like us to spend some time investigating further, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.
