### ISSUE TITLE
Incompatibility with AWS ElastiCache Serverless 7.0

### ISSUE THREAD

**Issue by fripoli** [spring-projects/spring-data-redis#2815]
We are trialing the migration from ElastiCache Redis to ElastiCache Serverless 7.0, both within AWS, and the startup fails with the following error:

```
"Caused by: io.lettuce.core.RedisCommandExecutionException: ERR unknown command 'psubscribe', with args beginning with: __keyevent@*__:expired"
```

The problem seems to be that the serverless version of AWS Elasticache does not support the `psubscribe` command as it can be seen here https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/SupportedCommands.html#RestrictedCommandsRedis

currently using version `3.1.6`

also using the annotation on our configuration

```
@EnableRedisRepositories(enableKeyspaceEvents = RedisKeyValueAdapter.EnableKeyspaceEvents.ON_STARTUP,
    keyspaceNotificationsConfigParameter = "")
```

any suggestions around it?

**Comment by mp911de** [comment]
If your Redis server doesn't support pattern subscriptions then please disable keyspace events via `EnableKeyspaceEvents.OFF`. Redis Repositories require subscriptions for index maintenance when using TTL. 
We cannot listen using channels as each key has its own unique identifier and we cannot know these upfront. Also, we would exhaust the subscription table by creating a subscription for each possible channel.

**Comment by dreamstar-enterprises** [comment]
I'm getting the same error with AWS Serverless: https://github.com/redisson/redisson/issues/3992
