### ISSUE TITLE
Tests with PubSub Messaging never ends when redis crash in 3.2.1

### ISSUE THREAD

**Issue by nicolasb29** [spring-projects/spring-data-redis#2822]
Hi,

Since spring-data-redis 3.2.1, when running tests (with Redis PubSub Messaging), the process no longer ends if the instance of redis crash. In 3.2.0, the test process ends well.

After some research, it seems that a cause could be this [commit](https://github.com/spring-projects/spring-data-redis/commit/13f87a2332ddbdd7be7fbf8a60e01e9680228e84) . When the connection fails: 

1. we enter in the [function `handleSubscriptionException` of the class `RedisMessageListenerContainer`](https://github.com/spring-projects/spring-data-redis/blob/3.2.1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L865) which is calling `potentiallyRecover` function
2. in [`potentiallyRecover` function](https://github.com/spring-projects/spring-data-redis/blob/3.2.1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L915), there is a call to `recoveryFunction`
3. the function  [`recoveryFunction`](https://github.com/spring-projects/spring-data-redis/blob/3.2.1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L885) is calling `lazyListen`
4. in [`lazyListen` function](https://github.com/spring-projects/spring-data-redis/blob/3.2.1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L394), there is a call to [`doSubscribe` function](https://github.com/spring-projects/spring-data-redis/blob/3.2.1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L411) in a while loop
5. the function `doSubscribe` is calling the function [`initialize`](https://github.com/spring-projects/spring-data-redis/blob/3.2.1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L427)
6. in this function, there is a [`RuntimeException`](https://github.com/spring-projects/spring-data-redis/blob/3.2.1/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L1261) and a call is made to function `handleSubscriptionException`, so we return to step 1 and there is a loop

I tried to make a quick and simple app to be able to test and reproduce the problem: 
- clone this [project](https://github.com/nicolasb29/springredislooptest)
- start a redis instance with the docker compose (without daemon : `docker compose up`)
- launch tests
- let the tests run until `KafkaApplicationTests4`
- when [`KafkaApplicationTests4`](https://github.com/nicolasb29/springredislooptest/blob/main/src/test/java/bzh/bonamy/redis/loop/KafkaApplicationTests4.java#L62) is running, kill the redis process
- Tests are ending but the process never ends

Sample output with version 3.2.0 with a "BUILD SUCCESSFUL in 43s"
[320.txt](https://github.com/spring-projects/spring-data-redis/files/13846975/320.txt)

In 3.2.1, the process never ends because of the loop (in this case I waited 3min) :
[321.txt](https://github.com/spring-projects/spring-data-redis/files/13847107/321.txt)

When I set a FixedBackOff with a maxAttempts value on `RedisMessageListenerContainer` with `setRecoveryBackoff`, it ends because he reaches the number of attempts when calling nextBackOff. Is it a workaround or is it the right way to do ?

**Comment by mp911de** [comment]
With #2782 we reintroduced fail-safety to `RedisMessageListenerContainer` to continue subscription attempts. The container works the following:

1. If it cannot subscribe initially, subscription (`lazyListen`) fails.
2. If the initial subscription was a successful and a Redis failure occurs, the container tries to resubscribe until reaching `BackOff.maxAttempts`.

By default, `BackOff.maxAttempts` is unlimited.

**Comment by mp911de** [comment]
Yes, using `BackOff` is the recommended approach. Spring Boot doesn't configure a container bean out of the box. However, when using Spring Session, you get a pre-configured container.

Shutdown hooks aren't reliable in terms of ordering and therefore, you experience quite some issues.

**Comment by nicolasb29** [comment]
Ok thanks !
