### ISSUE TITLE
Redundant assertion in `RedisTemplate.afterPropertiesSet(…)`

### ISSUE THREAD

**Issue by foaw** [spring-projects/spring-data-redis#2832]
In [`RedisTemplate#afterPropertiesSet`](https://github.com/spring-projects/spring-data-redis/blob/014634e94c3b0ae71d8b269a480861882b21c8eb/src/main/java/org/springframework/data/redis/core/RedisTemplate.java#L127-L169), if any of serializers are null and `enableDefaultSerializer` is true, they are set to `defaultSerializer`. After this, it checks if the `defaultSerializer` was also null, in which case an exception should be thrown. However, this cannot be the case, as `defaultSerializer` is pre-initialized to `JdkSerializationRedisSerializer`, if null.

https://github.com/spring-projects/spring-data-redis/blob/014634e94c3b0ae71d8b269a480861882b21c8eb/src/main/java/org/springframework/data/redis/core/RedisTemplate.java#L134-L138

https://github.com/spring-projects/spring-data-redis/blob/014634e94c3b0ae71d8b269a480861882b21c8eb/src/main/java/org/springframework/data/redis/core/RedisTemplate.java#L160-L162

**Comment by christophstrobl** [comment]
Thank you @foaw for raising the issue. We'll have a look.
