### ISSUE TITLE
@CacheEvict(... allEntries = true) do not work!

### ISSUE THREAD

**Issue by Shapoval1van** [spring-projects/spring-data-redis#2834]
**Version**:  3.1.1
**Description**: `@CacheEvict(... allEntries = true)` for Redis Cache with the next key serializer `JdkSerializationRedisSerializer` do not work.

In this [PR](https://github.com/spring-projects/spring-data-redis/issues/2379) probably was introduced a bug. In case of usage `allEntries = true` method [RedisCache#clear()](https://github.com/spring-projects/spring-data-redis/blob/25a6981544401f55d0d54a2681f342434184df2a/src/main/java/org/springframework/data/redis/cache/RedisCache.java#L252) will called. But when we want to clear all entries we going to pass '\*' to the [RedisCache#clear()](https://github.com/spring-projects/spring-data-redis/blob/25a6981544401f55d0d54a2681f342434184df2a/src/main/java/org/springframework/data/redis/cache/RedisCache.java#L252) method. 
Therefore this symbol '\*' will be serialised to and used as pattern to search keys for remove, obviously Redis do not recognise such patter and keys for delete will be not found and keys will be not deleted.

Before 3.0 version Redis received the next comand after clear
`KEYS cache:* `
But for versions after 3.0 I see the next
`KEYS cache:\\xac\\xed\\x00\\x05t\\x00\\x01*`

Can you please verify it since you was responsible to merge PR @mp911de?

**Comment by Shapoval1van** [comment]
@mp911de 

> `JdkSerializationRedisSerializer` isn't a great choice

I know it, but when I have 30 more services and everithing worked on previous major version
 

> Using a plain String-serializer (or providing your own serializer) is our suggested approach.

I just checked it and it do not work with all keySerializer except String-serializer


> That being said, this is expected behavior.

I would say No,  we have `cache:* ` where:

- cache ->  is cache name 
- : -> is separator
- * -> Redis search mask
So there is no a key in this line so serialised should not serialise it

P.S let me second I going to create PR with test to show you.

**Comment by mp911de** [comment]
`RedisCache.clear(…)` can be used to override the specific functionality that you want to align for your specific use. All necessary components (`getCacheWriter()`, `createCacheKey(…)`) are accessible so you can decide in your own implementation whether to override just `clear()` of its overload accepting the key pattern.
