### ISSUE TITLE
Question: Keep creating new connections every 5min when using connection pool

### ISSUE THREAD

**Issue by joycezhou0621** [spring-projects/spring-data-redis#2839]
Hello team,

I'm using the Spring Data Redis library to interact with Redis, specifically the AWS Elasticache service, and implementing the Lettuce connection pool. I've set the maxTotal, maxIdle, and minIdle parameters in the pool to 50 each, with the assumption that we would maintain a consistent pool of 50 connections. My expectation was that if all connections in the pool were in use, the client would be blocked, waiting until a new connection is released from the pool. Consequently, new connections should only be created during pool warm-up or when the connection pool manager attempts to remove invalid connections (closed or idle for a very long time).

However, we've encountered two issues:

1. While attempting to warm up the connection pool during the Spring Boot startup, I observed sufficient "Connecting to Redis at * <success>" logs, leading me to believe that the connection pool was adequately warmed up. However, when the web server started serving requests, we experienced numerous command timeout errors, indicating ongoing attempts to create new connections. I'm puzzled as to why new connections are still being created. Shouldn't we directly obtain connections from the warmed-up connection pool?
2. After node startup and stability, I've noticed the creation of new connections every 5 minutes, as indicated by AWS CloudWatch metrics. Debug-level logging shows multiple "Connecting to Redis at *" entries every 5 minutes, aligning with the server metrics.

This recurrent pattern of creating connections during node startup and every 5 minutes thereafter is perplexing. Our web server nodes handle around 200 requests per second, and the Redis server's timeout parameter is set to 0, indicating that idle connections should not be disconnected. I've also set the MinEvictableIdleDuration to 60 minutes. So, I'm questioning why new connections are needed when accessing Redis.

Despite thorough examination of the logs and configuration settings, I haven't found any clear indications as to why these new connections are consistently being created at 5-minute intervals. I've raised this issue here, seeking your expertise and insights to help uncover the reasons behind this behavior.

Your assistance and guidance would be highly valued.

Here is my configs. 
```
   @Bean
    public RedisConnectionFactory redisConnectionFactory(){
        final RedisClusterConfiguration redisServerConfig = new RedisClusterConfiguration(Collections.singletonList(redisConfig.getRedisHost() + ":" + redisConfig.getRedisPort()));
        return poolingRedisConnectionFactory(redisServerConfig);
    }
```

```
    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        final RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        redisTemplate.setEnableDefaultSerializer(false);
        redisTemplate.setKeySerializer(RedisSerializer.string());
        redisTemplate.setValueSerializer(RedisSerializer.string());
        redisTemplate.setHashKeySerializer(RedisSerializer.string());
        redisTemplate.setHashValueSerializer(RedisSerializer.string());
        redisTemplate.afterPropertiesSet();
        return redisTemplate;
    }
```

```
    private RedisConnectionFactory poolingRedisConnectionFactory(RedisClusterConfiguration redisServerConfig) {
        LettuceClientConfiguration poolingClientConfig = RedisClientConfigBuilder.poolingClientConfiguration(rtrue);
        LettuceConnectionFactory connectionFactory = new LettuceConnectionFactory(redisServerConfig, poolingClientConfig);
        connectionFactory.setShareNativeConnection(false);
        connectionFactory.afterPropertiesSet();
        return connectionFactory;
    }
```
```
   @Slf4j
public class RedisClientConfigBuilder {
    private RedisClientConfigBuilder() {
    }

    public static LettuceClientConfiguration poolingClientConfiguration(boolean useSsl) {
        log.info("Use pooling client configuration");
        final LettucePoolingClientConfiguration.LettucePoolingClientConfigurationBuilder configBuilder = LettucePoolingClientConfiguration.builder()
                .readFrom(ReadFrom.REPLICA_PREFERRED)
                .commandTimeout(Duration.ofSeconds(2))
                .clientOptions(clusterClientOptions(Duration.ofSeconds(10)))
                .poolConfig(connectionPoolConfig());

        if (useSsl) {
            configBuilder.useSsl();
        }
        return configBuilder.build();
    }

    private static GenericObjectPoolConfig connectionPoolConfig() {
        final GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        poolConfig.setMaxTotal(50);
        poolConfig.setMaxIdle(50);
        poolConfig.setMinIdle(50);
        poolConfig.setMinEvictableIdleDuration(Duration.ofMinutes(60));
        poolConfig.setTestWhileIdle(true);
        poolConfig.setTimeBetweenEvictionRuns(Duration.ofSeconds(10));
        poolConfig.setNumTestsPerEvictionRun(10);
        return poolConfig;
    }

    private static ClusterClientOptions clusterClientOptions(Duration connectTimeout) {
        final SocketOptions socketOptions = SocketOptions.builder()
                .connectTimeout(connectTimeout)
                .keepAlive(true)
                .build();

        final ClusterTopologyRefreshOptions clusterTopologyRefreshOptions =  ClusterTopologyRefreshOptions.builder()
                .enableAllAdaptiveRefreshTriggers()
                .dynamicRefreshSources(true)
                .build();

        return ClusterClientOptions.builder()
                .topologyRefreshOptions(clusterTopologyRefreshOptions)
                .socketOptions(socketOptions)
                .autoReconnect(true)
                .build();
    } 
```

  We use redisTemplate to run redis command. For example, `redisTemplate.opsForHash().entries(key)`

**Comment by mp911de** [comment]
Spring Data Redis hosts multiple connection pools. There are separate pools for reactive and for synchronous usage. Also, if your application uses the Cluster API to run commands on specific nodes, then there's a third pool being created.

Please also keep in mind that Cluster connections consist of multiple connections to the individual Redis Cluster nodes.

If you observe a regular disconnect after 5 minutes, then it seems that some active network component disconnects idle connections. Please watch out for Lettuce logs mentioning disconnects and connection watchdog attempting reconnects.

**Comment by joycezhou0621** [comment]
@mp911de Thank you for your assistance. I have an additional question. I experimented with not using a connection pool and instead utilizing a shared native connection for our redis cluster, while also enabling eager initialization. Here is our setup. 
```
connectionFactory.setShareNativeConnection(true);
connectionFactory.setEagerInitialization(true);
connectionFactory.afterPropertiesSet();

```
I noticed some logs indicating that a shared connection was created during bean initialization. However, when a new EC2 node starts up and begins serving traffic, we observe a significant number of Redis command timeout errors. Interestingly, these errors only occur for the first few requests, and afterward, they no longer appear.
Due to the at least 5-minute gap between bean initialization and the node actually starting to serve traffic, is it possible that the shared native connection closed during this time interval?  However, we have not set any timeout from the server side. Do you have any insights into why these peculiar Redis command timeout errors only occur during node startup?

**Comment by mp911de** [comment]
> Due to the at least 5-minute gap between bean initialization and the node actually starting to serve traffic, is it possible that the shared native connection closed during this time interval?

If Redis is configured to drop a connection, then yes, this might happen. Watch closely the debug log to determine what is happening on the transport level.
