### ISSUE TITLE
Spring Data Redis saveAll very slow

### ISSUE THREAD

**Issue by Kvark900** [spring-projects/spring-data-redis#2844]
Please support Redis command pipelining within Spring Data Redis `repository.saveAll` method.

### Problem
`SimpleKeyValueRepository<T, ID>` iterates over each entity and invokes `save()` method not using Redis pipelining.

    @Override  
    public <S extends T> List<S> saveAll(Iterable<S> entities) {  
      
        Assert.notNull(entities, "The given Iterable of entities must not be null");  
      
        List<S> saved = new ArrayList<>();  
      
        for (S entity : entities) {  
           saved.add(save(entity));  
        }  
      
        return saved;  
    }

**Comment by mp911de** [comment]
We cannot use pipelining because we require command responses at certain steps to decide how to proceed with index updates/saving. Generally, Redis Repositories aren't built for top-notch performance, instead, these are a utility for occasionally saving data.
