### ISSUE TITLE
SerializationException when using RedisTemplate

### ISSUE THREAD

**Issue by Welkin1027** [spring-projects/spring-data-redis#2857]
When I used RedisTemplate to set & get data, the program throwed org.springframework.data.redis.serializer.SerializationException, the exception message was "Could not resolve type id 'xxx.entity.DeptNode' as a subtype of `xxx.entity.DeptNode`", the two paths are absolutely the same. 
I found that the RedisTemplate used different types of classloader, so, the class DeptNode was recgonized as different class. By removing spring-boot-devtools in pom.xml, the problem could be solved, but I was not permitted to remove this package, what could I do to resolve this problem?

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.
