### ISSUE TITLE
Add reactiveRepository

### ISSUE THREAD

**Issue by mollder** [spring-projects/spring-data-redis#2858]
Hello, in the case of Redis, it is a common case to use it reactive, so I think providing a reactive repository is a good option, what do you think about this?

If it's okay, I'll look at the source code, refer to it, and then start adding a reactive repository

**Comment by mp911de** [comment]
Duplicate of #1823

Thanks for reaching out. We do not intend to support reactive repositories.

**Comment by mollder** [comment]
thank you for your answer
