### ISSUE TITLE
Redis Query-by-Example does not support string matcher STARTING, ENDING using Spring data redis

### ISSUE THREAD

**Issue by sujitp149** [spring-projects/spring-data-redis#2859]
We are building an application using JDK17, Spring Data Redis(3.x), spring boot (3.x) which uses AWS Elastic Redis cache (cluster mode enabled), lettuce client by looking at https://docs.spring.io/spring-data/redis/reference/data-commons/query-by-example.html however it ends up with **"Redis Query-by-Example does not support string matcher STARTING, Supported matchers are [DEFAULT, EXACT] "**

**Code snippet** 

public class Person {

@Id
private String id;
private String firstname;
private String lastname;
// … getters and setters omitted
}

**Repository**
public interface PersonRepository extends CrudRepository\<Person, String\>,
QueryByExampleExecutor\<Person\> {}

**Service class**

@Autowired
PersonRepository personRepository;
Person person = new Person();  
person.setFirstname("Dave");  
ExampleMatcher matcher = ExampleMatcher.matching()  
.withIgnorePaths("lastname")  
.withIncludeNullValues()  
.withStringMatcher(StringMatcher.STARTING); // Error is being thrown here  
Example\<Person\> example = Example.of(person, matcher);
personRepository.findAll(example);
Redis Query-by-Example support for StringMatcher STARTING,ENDING, CONTAINING`

**Comment by mp911de** [comment]
These are unsupported operations, see https://docs.spring.io/spring-data/redis/reference/redis/redis-repositories/query-by-example.html#query-by-example.running:

> The following list shows properties not supported by Query by Example:
> 
> - Case-insensitive matching
> - Regex, prefix/contains/suffix String-matching
> - Querying of Associations, Collection, and Map-like properties
> - Inclusion of null values from the criteria
> - findAll with sorting

**Comment by sujitp149** [comment]
thanks @mp911de  for your resposne. Does it not contradicting with below example provided in documentation https://docs.spring.io/spring-data/redis/reference/redis/redis-repositories/query-by-example.html#query-by-example.running

<html>
<body>
<h2 id="query-by-example.matchers" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; color: rgb(255, 255, 255); font-weight: var(--asciidoctor-heading-font-weight); margin: 1.3rem -1rem 0px; font-size: 2.5em; font-family: var(--font-family-special); hyphens: none; line-height: 1.3; padding: 1.8rem 1rem 0.1rem; border-bottom: 1px solid var(--section-divider-color); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: -0.0444444px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(27, 31, 35); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Example Matchers</h2><div class="sectionbody" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; color: rgb(255, 255, 255); font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15.1111px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: -0.0444444px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(27, 31, 35); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="paragraph" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; margin: 1rem 0px 0px;"><p style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; margin: 0px;">Examples are not limited to default settings. You can specify your own defaults for string matching, null handling, and property-specific settings by using the<span> </span><code style="box-sizing: inherit; font-family: var(--monospace-font-family); scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; font-weight: 400; hyphens: none; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat: ; background-attachment: ; background-origin: ; background-clip: ; background-color: rgb(27, 31, 35); border-radius: 0px; color: rgb(255, 255, 255); font-size: 0.95em; padding: 0.125em 0.25em; border: 1px solid rgb(43, 47, 51);">ExampleMatcher</code>, as shown in the following example:</p></div><div class="exampleblock" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; margin: 1rem 0px 0px;"><div class="title" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; color: var(--asciidoctor-caption-font-color); font-size: calc(14/var(--pixel-to-rem)); font-weight: var(--asciidoctor-caption-font-weight); font-style: italic; hyphens: none; letter-spacing: 0.01em; padding-bottom: 0.075rem; text-align: left;">Example 2. Example matcher with customized matching</div><div class="content" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; background: var(--asciidoctor-example-background); border: 1px solid var(--asciidoctor-example-border-color); border-radius: 4px; padding: 0.75rem;"><div class="listingblock" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; margin: 0px;"><div class="content" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin;"><pre class="highlightjs highlight" style="box-sizing: inherit; font-family: var(--monospace-font-family); scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; font-size: calc(14/var(--pixel-to-rem)); line-height: 1.3; font-weight: 400; hyphens: none; margin: 0px; position: relative;"><code class="language-java hljs" data-lang="java" style="box-sizing: inherit; font-family: var(--monospace-font-family); scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; background: var(--asciidoctor-pre-background); color: var(--highlight-font-color); display: block; overflow-x: auto; padding: 1rem; font-weight: 400; hyphens: none; box-shadow: inset 0 0 1.75px var(--asciidoctor-pre-border-color); border-radius: 4px;">Person person = <span class="hljs-keyword" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; color: var(--highlight-keyword-font-color); font-weight: var(--monospace-font-weight-bold);">new</span> Person();                          <i class="conum" data-value="1" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; border: 1px solid; font-family: var(--monospace-font-family); font-size: calc(12.5/var(--pixel-to-rem)); background: var(--asciidoctor-callout-background); border-radius: 100%; color: var(--asciidoctor-callout-font-color); display: inline-block; font-style: normal; height: 1.25em; letter-spacing: -0.25ex; line-height: 1.2; text-align: center; text-indent: -0.25ex; width: 1.25em;"></i>
person.setFirstname(<span class="hljs-string" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; color: var(--highlight-string-font-color);">"Dave"</span>);                           <i class="conum" data-value="2" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; border: 1px solid; font-family: var(--monospace-font-family); font-size: calc(12.5/var(--pixel-to-rem)); background: var(--asciidoctor-callout-background); border-radius: 100%; color: var(--asciidoctor-callout-font-color); display: inline-block; font-style: normal; height: 1.25em; letter-spacing: -0.25ex; line-height: 1.2; text-align: center; text-indent: -0.25ex; width: 1.25em;"></i>

ExampleMatcher matcher = ExampleMatcher.matching()     <i class="conum" data-value="3" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; border: 1px solid; font-family: var(--monospace-font-family); font-size: calc(12.5/var(--pixel-to-rem)); background: var(--asciidoctor-callout-background); border-radius: 100%; color: var(--asciidoctor-callout-font-color); display: inline-block; font-style: normal; height: 1.25em; letter-spacing: -0.25ex; line-height: 1.2; text-align: center; text-indent: -0.25ex; width: 1.25em;"></i>
  .withIgnorePaths(<span class="hljs-string" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; color: var(--highlight-string-font-color);">"lastname"</span>)                         <i class="conum" data-value="4" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; border: 1px solid; font-family: var(--monospace-font-family); font-size: calc(12.5/var(--pixel-to-rem)); background: var(--asciidoctor-callout-background); border-radius: 100%; color: var(--asciidoctor-callout-font-color); display: inline-block; font-style: normal; height: 1.25em; letter-spacing: -0.25ex; line-height: 1.2; text-align: center; text-indent: -0.25ex; width: 1.25em;"></i>
  .withIncludeNullValues()                             <i class="conum" data-value="5" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; border: 1px solid; font-family: var(--monospace-font-family); font-size: calc(12.5/var(--pixel-to-rem)); background: var(--asciidoctor-callout-background); border-radius: 100%; color: var(--asciidoctor-callout-font-color); display: inline-block; font-style: normal; height: 1.25em; letter-spacing: -0.25ex; line-height: 1.2; text-align: center; text-indent: -0.25ex; width: 1.25em;"></i>
  .withStringMatcher(StringMatcher.ENDING);            <i class="conum" data-value="6" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; border: 1px solid; font-family: var(--monospace-font-family); font-size: calc(12.5/var(--pixel-to-rem)); background: var(--asciidoctor-callout-background); border-radius: 100%; color: var(--asciidoctor-callout-font-color); display: inline-block; font-style: normal; height: 1.25em; letter-spacing: -0.25ex; line-height: 1.2; text-align: center; text-indent: -0.25ex; width: 1.25em;"></i>

Example&lt;Person&gt; example = Example.of(person, matcher); <i class="conum" data-value="7" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; border: 1px solid; font-family: var(--monospace-font-family); font-size: calc(12.5/var(--pixel-to-rem)); background: var(--asciidoctor-callout-background); border-radius: 100%; color: var(--asciidoctor-callout-font-color); display: inline-block; font-style: normal; height: 1.25em; letter-spacing: -0.25ex; line-height: 1.2; text-align: center; text-indent: -0.25ex; width: 1.25em;"></i></code><div class="source-toolbox" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; background-color: var(--body-background-color); border-color: var(--pre-annotation-font-color); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 2px; bottom: 0.5rem; display: flex; font-family: var(--body-font-family); line-height: 1; opacity: 0; position: absolute; right: 0.5rem; transition: opacity 0.15s ease-in-out 0s; z-index: 1;"><button class="copy-button" title="Copy to clipboard" style="box-sizing: inherit; cursor: pointer; font-family: inherit; font-size: inherit; line-height: inherit; margin: 0px; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; background: url(&quot;../img/octicons-16.svg#view-clippy&quot;) 50% center / 16px 16px no-repeat; border: none; color: inherit; height: 24px; outline: none; padding: 0px; width: 24px; filter: var(--codetools-button-filter); align-items: center; display: flex; flex-direction: column;"><span class="copy-toast" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; background-color: var(--doc-font-color); border-radius: 0.25em; color: var(--color-black); cursor: auto; display: inline-flex; flex: 0 0 auto; justify-content: center; margin-top: 1em; opacity: 0; padding: 0.5em; position: relative; top: 24px; transition: opacity 0.5s ease 0.75s; white-space: nowrap; filter: var(--codetools-button-filter);">Copied!</span></button></div></pre></div></div><div class="colist arabic" style="box-sizing: inherit; scrollbar-color: var(--scrollbar-thumb-color) transparent; scrollbar-width: thin; font-size: calc(16/var(--pixel-to-rem)); word-break: break-all; margin: 0.25rem 0px -0.25rem;">
  | Create a new instance of the domain object.
-- | --
  | Set properties.
  | Create an ExampleMatcher to expect all values to match. It is usable at this stage even without further configuration.
  | Construct a new ExampleMatcher to ignore the lastname property path.
  | Construct a new ExampleMatcher to ignore the lastname property path and to include null values.
  | Construct a new ExampleMatcher to ignore the lastname property path, to include null values, and to perform suffix string matching.
  | Create a new Example based on the domain object and the configured ExampleMatcher.

</div></div></div></div>
</body>
</html>

**Comment by mp911de** [comment]
To some extent it does. The entire query by example fragment comes from our commons documentation to avoid duplicates. The price for reuse is ambiguity to some extent.

**Comment by sujitp149** [comment]
Thanks for your quick response @mp911de .
can you please confirm if spring data redis does not support search with matchers STARTING,ENDING on firstname, lastname fields ?
                                                             (or)

spring data redis can support search with matchers STARTING,ENDING on firstname, lastname fields with some changes like adding @Index annotation on firstname, lastname ?
                                                         
Can you please  share soem other alternatives to address requirement fo searching based on STARTING,ENDING while using AWS Elastic Redis cache (AWS managed service) ?

Thanks in advance!

**Comment by mp911de** [comment]
Redis secondary indices support only exact matches. Substring search and different letter casing are not supported.
