### ISSUE TITLE
Let `QueryByExampleRedisExecutor` implement `ListQueryByExampleExecutor`

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-data-redis#2880]
Hi

There's special "Query By Example" section in Spring Data Redis reference documentation: https://docs.spring.io/spring-data/redis/reference/redis/redis-repositories/query-by-example.html

However it mentions QueryByExampleExecutor type only:

```
interface PersonRepository extends QueryByExampleExecutor<Person> {
}

```

But Spring Data Redis 3.0 introduced new type ListQueryByExampleExecutor which is more convenient for list operations. However it's not mentioned in this section.

**Comment by mp911de** [comment]
`QueryByExampleRedisExecutor` doesn't implement `ListQueryByExampleExecutor` in the first place, so we need to adopt the implementation first.
