### ISSUE TITLE
AWS ElasticCache issue with Config command

### ISSUE THREAD

**Issue by hanysakr** [spring-projects/spring-data-redis#2894]
AWS ElasticCache has disabled few commands one of them is Config command
When I try to set keyspaceNotificationsConfigParameter to any value it will try to call the config command and fail with error
"ERR unknown command 'CONFIG', with args beginning with: 'GET' 'notify-keyspace-events' "
I found that KeyspaceEventMessageListener class is trying to register this value on ElasticCache, and there is no way to escape it unless using empty string with EnableRedisRepositories annotation, but the empty string is not sending the events from ElasticCache to the listener, so I cannot use it as empty.
There should be a way to set the keyspaceNotificationsConfigParameter value without registering it on ElasticCache with Config command

**Comment by mp911de** [comment]
`@EnableRedisRepositories(keyspaceNotificationsConfigParameter)` is designed for getting started locally quickly. You should not use this mechanism in production to avoid reconfiguring your Redis server that might be configured differently to serve multiple applications.

That being said, please configure your Elasticsearch server via the console with at least `Ex` for `notify-keyspace-events`.
