### ISSUE TITLE
Use SET command instead of SETEX

### ISSUE THREAD

**Issue by ehsanalemzadeh** [spring-projects/spring-data-redis#2897]
In DefaultValueOperations, the set method with timeout argument calls the setEx command internally. However, SETEX command was deprecated in version 2.6.12 of Redis. According to Redis documentation, it is recommended to replace SETEX with SET using the EX argument. [Redis documentation](https://redis.io/docs/latest/commands/setex/)

**Comment by mp911de** [comment]
Good catch. Do you want to submit a pull request?

**Comment by ehsanalemzadeh** [comment]
Sure. I will do it soon.
