### ISSUE TITLE
Support Lettuce SSL/TLS Verification Modes

### ISSUE THREAD

**Issue by philsttr** [spring-projects/spring-data-redis#2899]
[Lettuce 6.1.0.RELEASE](https://github.com/redis/lettuce/releases/tag/6.1.0.RELEASE) added support for three SSL/TLS verification modes (`SslVerifyMode`):
* `NONE` (corresponds with `setVerifyPeer(false)`)
* `CA`  (only verifies the CA and cert, without verifying the hostname matches)
* `FULL` (corresponds with `setVerifyPeer(true)`)

The new `CA` mode is most helpful for cluster mode, where the seed connection is made via hostname (and thus matches hostnames in the certificate), but then cluster node connections are made by IP address (which typically do not appear in SubjectAltNames of the certificate, particularly for redis instances from cloud providers).

Currently, Spring Data Redis only supports `setVerifyPeer(boolean)`.  I would like Spring Data Redis to support the three verification modes that Lettuce >= 6.1 now supports.

**Comment by philsttr** [comment]
Also somewhat related, I filed https://github.com/redis/lettuce/issues/2837 to request an enhancement to verification modes to better secure connecting to redis in cluster mode from cloud providers.

**Comment by AnneMayor** [comment]
I think this is a good issue to approach for me. I am going to open PR within this weekend :)

**Comment by AnneMayor** [comment]
Since I have to do my work as soon as quickly I am going to open this PR until 6.16. Thanks.

**Comment by baojian123** [comment]
Hi @AnneMayor, I have opened a PR on this issue.

**Comment by AnneMayor** [comment]
Thank, @baojian123 👍
