### ISSUE TITLE
Add overloads to `StreamOperations` accepting `XAddOptions`

### ISSUE THREAD

**Issue by sanwzzz** [spring-projects/spring-data-redis#2915]
HI

**Comment by sanwzzz** [comment]
Hi,

I am currently using redisTemplate.opsForStream() to operate on Redis streams. When using the add method, I want to support more parameters such as MAXID and MINID. However, it is not supported at the moment. I noticed that RedisStreamCommands already provides XAddOptions, but currently (in version 3.3.X), there is no way to set these options, and only the default None is called.

Is it possible to enhance the DefaultStreamOperations.add method to support these parameters?

Example

**Comment by sanwzzz** [comment]
``` code
default RecordId add(Record<K, ?> record, XAddOptions ops) {
    return add(record, null)
};
RecordId add(Record<K, ?> record, XAddOptions ops);
```

And some img
![PixPin_2024-05-24_17-03-40](https://github.com/spring-projects/spring-data-redis/assets/39424325/ea65b57b-49fd-4002-b7d8-e3434522b3ea)
![PixPin_2024-05-24_17-14-44](https://github.com/spring-projects/spring-data-redis/assets/39424325/5039c35e-2e31-436d-87b5-4512364c5a72)
![PixPin_2024-05-24_17-16-31](https://github.com/spring-projects/spring-data-redis/assets/39424325/a08ffd2e-e0b9-4029-a80c-96635a6f17eb)

**Comment by mp911de** [comment]
Not exactly sure why you've posted details about `DefaultStreamOperations`. In any case, adding options for the `XADD` operations are held by `XAddOptions`. `minId` and `maxlen` are already supported, so not sure what you're asking for. Please elaborate.

**Comment by sanwzzz** [comment]
> Not exactly sure why you've posted details about `DefaultStreamOperations`. In any case, adding options for the `XADD` operations are held by `XAddOptions`. `minId` and `maxlen` are already supported, so not sure what you're asking for. Please elaborate.

I want to set the XAddOptions in redisTemplate.opsForStream().add(...) in the redisTemplate.opsForStream(.add(...)) with a new XAddOptions parameter, but no method.
![old](https://github.com/spring-projects/spring-data-redis/assets/39424325/3b75e9f0-33d0-4587-a9a4-f0dcd5803824)

Could you please add the following API
RecordId add(Record<K, ? > record, XAddOptions ops);
![new](https://github.com/spring-projects/spring-data-redis/assets/39424325/0229111d-4805-4819-b048-aadd5efc7ce9)

**Comment by mp911de** [comment]
Ah, I got it. All the screenshots are pretty distracting and contribute a lot of noise to this ticket.

**Comment by jinkshower** [comment]
Hello, @mp911de 
May I take this issue? 

I've looked through issue and code. I am planning to add interface method
`RecordId add(Record<K, ?> record, XAddOptions options)`
and override this method in `DefaultStreamOperations`. 
same with `ReactiveStreamOperations`

Do you expect the client code should be like this? 
```java
XAddOptions options = XAddOptions.maxlen(1000);
redisTemplate.opsForStream().add("stream", Map.of("key", "value"), options);
```

if this is the way you implied, i'm happy to make a pr with a few tests to support this change.

**Comment by jinkshower** [comment]
Hello, @mp911de 
May I take this issue? 

I've looked through issue and code. I am planning to add interface method
`RecordId add(Record<K, ?> record, XAddOptions options)`
and override this method in `DefaultStreamOperations`. 
and also same with `ReactiveStreamOperations`

Do you expect the client code should be like this? 
```java
XAddOptions options = XAddOptions.maxlen(1000);
redisTemplate.opsForStream().add("stream", Map.of("key", "value"), options);
```

if this is the way you implied, i'm happy to make a pr with a few tests to support this change.

**Comment by sanwzzz** [comment]
Is it possible set global default options?
