### ISSUE TITLE
RedisNode creation from bare hostname should assign default port

### ISSUE THREAD

**Issue by lukasz-glapinski-exa** [spring-projects/spring-data-redis#2928]
Current code is expecting node information to not contain port but is not assigning default port to portString variable resulting in exception being thrown.

https://github.com/spring-projects/spring-data-redis/blob/a7d39147cf3f9649b0609a10fc43e5672c732193/src/main/java/org/springframework/data/redis/connection/RedisNode.java#L97

**Comment by LeeHyungGeol** [comment]
May I handle this PR? I'll create PR within tomorrow.

**Comment by LeeHyungGeol** [comment]
Fix PR: #3002
