### ISSUE TITLE
@RedisHash timeToLive is a long, which is not compatible with the use of spring-style / SPeL

### ISSUE THREAD

**Issue by alexisgayte** [spring-projects/spring-data-redis#2931]
org.springframework.data.redis.core.RedisHash has a field timeToLive typed as long therefor you cannot use SPeL/Spring-style expression.

timeToLive is often a property coming from env properties and therefor pass from parameter.
The current definition of @RedisHash is @RedisHash(value="myIndex", timeToLive=60)

The issue seems to come from a long running issue (compiler issue) here @Scheduled
<img width="709" alt="image" src="https://github.com/spring-projects/spring-boot/assets/7965274/b7011769-7efa-41b0-a427-9088d0d8d176">

However this is annoying because that force user of @RedisHash to define all index/entity globally using RedisMappingContext bean

```
    @Bean
    public RedisMappingContext keyValueMappingContext() {
        return new RedisMappingContext(new MappingConfiguration(new IndexConfiguration(), new MyKeyspaceConfiguration()));
    }

    public class MyKeyspaceConfiguration extends KeyspaceConfiguration {

        @Override
        protected Iterable<KeyspaceSettings> initialConfiguration() {
            KeyspaceSettings keyspace = new KeyspaceSettings(Index.class, "myindex:Index");
            keyspace.setTimeToLive(MyIndex.getTtlInSeconds().longValue());
            return Collections.singleton(keyspace);
        }
    }

```

linked to : https://github.com/spring-projects/spring-boot/issues/41256

**Comment by mp911de** [comment]
Have you seen that you can annotate individual properties with `@TimeToLive`? A numeric property within the data model can serve as a customization hook where you pre-initialize the TTL value with a config value.

**Comment by alexisgayte** [comment]
Yes I have seen it, 
But for me this option is not an option as I can't change my data model.

**Comment by mp911de** [comment]
We cannot change `@RedisHash(timeToLive)` to a `String` as that would break existing applications. Right now, we provide a number of approaches assuming a good fit for the majority of applications. If your specific case comes with limitations that do not match our assumptions, then using the global TTL approach is the best approach.

**Comment by alexisgayte** [comment]
I understand what you are saying but, I do think that not been integrated with spring-style is a missed feature for spring-data-redis.

spring-data-redis is not a redis client.

**Comment by mp911de** [comment]
This is a nuanced topic as introducing a `String`-based annotation attribute won't make the cut. `@Scheduled` introduced a series of `String` attribute alternatives that clutter the API. Their format isn't really convenient. We will reconsider this ticket once https://github.com/spring-projects/spring-framework/pull/30396 has been merged so that string-based durations can be expressed in a more readable manner.
