### ISSUE TITLE
Typo in method name hasExplictTimeToLiveProperty in RedisPersistentEntity class

### ISSUE THREAD

**Issue by ziyao0** [spring-projects/spring-data-redis#2933]
**Description**
In the [`org.springframework.data.redis.core.mapping.RedisPersistentEntity`](https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/core/mapping/RedisPersistentEntity.java) class, the method name `boolean hasExplictTimeToLiveProperty();` contains a typo. The correct spelling should be `hasExplicitTimeToLiveProperty`.

**Suggested fix**
Rename the method `hasExplictTimeToLiveProperty` to `hasExplicitTimeToLiveProperty`.

**Comment by christophstrobl** [comment]
good catch - thank you @ziyao0 !
