### ISSUE TITLE
Default shutdownQuietPeriod should be 0 or some fraction of the shutdownTimeout

### ISSUE THREAD

**Issue by seabamirum** [spring-projects/spring-data-redis#2945]
In `DefaultLettuceClientConfiguration`, the shutdownQuietPeriod is set as follows

```
this.shutdownQuietPeriod = shutdownQuietPeriod != null ? shutdownQuietPeriod : shutdownTimeout;
```

This effectively makes it so that clients who do not set this parameter in their `LettuceClientConfiguration` builder are forced to wait for the entire shutdownTimeout period before shutting down. 

**Proposed Solution**
Modify the default value of shutdownQuietPeriod to be 0 or a fraction of the shutdownTimeout (e.g., 10% of shutdownTimeout). This change will ensure that the shutdown process is initiated promptly without waiting for the entire shutdownTimeout period.

**Comment by mp911de** [comment]
Shutdown timeouts are here to protect your application in a best-effort basis during shutdown. If your application shuts down cleanly without lagging Redis I/O during the shutdown, then you can set the timeouts to zero.

**Comment by seabamirum** [comment]
Thanks, I think that would be a good improvement. Until I found the `shutdownQuietPeriod` parameter, it took me a while to figure out why increasing `shutdownTimeout` only ended up increasing the actual shutdown time by the same amount. I had assumed there were active processes, etc. but this occurred even on an idle server.
