### ISSUE TITLE
Refactor Tests to `instanceof` pattern variable

### ISSUE THREAD

**Issue by arefbehboudi** [spring-projects/spring-data-redis#2967]
In some of our test cases, we are currently using the traditional instanceof checks followed by explicit type casting. With the introduction of Pattern Matching in recent Java versions, we can refactor these checks to make the code more concise and readable.

**Example:**
  `
  if (redisOperations instanceof DisposableBean) {
	  ((DisposableBean) redisOperations).destroy();
  }
  `

Tasks:
  - Locate instanceof checks in tests.
  - Refactor them to use Pattern Matching.
  - Ensure all tests pass after changes.

If this approach is approved, I will proceed with the changes and create a pull request.

**Comment by mp911de** [comment]
Hey @arefbehboudi thanks for your suggestion. It makes sense to go over the entire codebase and use `instanceof` pattern matching. Feel free to submit a pull request.

**Comment by arefbehboudi** [comment]
@mp911de Thank you very much. I'll make the changes and keep you updated.
