### ISSUE TITLE
Negative maxlen for XAddOptions is ignored

### ISSUE THREAD

**Issue by jinkshower** [spring-projects/spring-data-redis#2982]
This issue refers to a comment in [#2936](https://github.com/spring-projects/spring-data-redis/pull/2936#issuecomment-2220383705)

As we now can use XAddOptions in streamOperations,

```java
XAddOptions options = XAddOptions.maxlen(-1);
redisTemplate.opsForStream("myStream", Map.of("key", "value"), options);
```

This executes without throwing an error or warning the client. Instead, the result is that the maxlen option is not applied.

IMO, this is because the XAddOptions hasMaxlen() method gets called before every time XAddOptions is used, and it checks maxlen > 0, which results in ignoring negative values for maxlen.

- Reproducible code

```java
@ParameterizedRedisTest
void addMinusMaxlenDoesNotThrowsException() {
	K key = keyFactory.instance();
	HV value = hashValueFactory.instance();
	XAddOptions options = XAddOptions.maxlen(-1).approximateTrimming(false);
	assertDoesNotThrow(() -> redisTemplate.opsForStream().add(StreamRecords.objectBacked(value).withStreamKey(key), options));
	assertThat(redisTemplate.opsForStream().range(key, Range.unbounded())).hasSize(1);
}
```
![image](https://github.com/user-attachments/assets/a96bd099-1670-4ec2-a0ca-16e0ec6b0a88)

**Comment by jinkshower** [comment]
@mp911de,
I’d like to continue and finish what I started for this issue. Would you mind if I handle this issue? Also, do you want the PR to cover the `XPendingOptions` `count` as well?

**Comment by mp911de** [comment]
Sounds good, feel free to address both concerns within a single pull request.
