### ISSUE TITLE
Use before assignment of asyncDedicatedConnection in LettuceConnection

### ISSUE THREAD

**Issue by oldium** [spring-projects/spring-data-redis#2984]
I found issue while reading how Lettuce integration works in this method:

https://github.com/spring-projects/spring-data-redis/blob/777f0791143c5c42975760e5e027925c7b3f050c/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L966-L975

The method creates a new connection, which is stored by the caller into a `asyncDedicatedConnection` attribute:

https://github.com/spring-projects/spring-data-redis/blob/777f0791143c5c42975760e5e027925c7b3f050c/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L1026-L1033

But it looks like the `asyncDedicatedConnection` is used before assignment in `potentiallySelectDatabase()` called by `doGetAsyncDedicatedConnection()`:

https://github.com/spring-projects/spring-data-redis/blob/777f0791143c5c42975760e5e027925c7b3f050c/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L1068-L1073

**Comment by mp911de** [comment]
This is a bug, good catch. We need to apply the database selection clearly on the newly created connection. Do you want to submit a pull request?

**Comment by oldium** [comment]
Turns out the logic is broken here. `select()` refuses to use shared connection, so it executes the `select` command on a dedicated connection. This means that the `potentiallySelectDatabase()` call is superfluous in `doGetAsyncDedicatedConnection`, because the database change will be executed in `select` call anyway.

I am not able to tell the difference between `connection.sync().select()` (used in `potentiallySelectDatabase` method) and `invokeStatus().just(..., CommandType.SELECT, ...)` (used in `select` method), though.

**Comment by oldium** [comment]
Please check https://github.com/oldium/spring-data-redis/commit/e47545a9119962fccf140848fdf1d707cf75c164 for possible fix. As I said, I am not sure whether the `invokeStatus()` (it uses `RedisClusterAsyncCommands::dispatch`, which is actually `BaseRedisAsyncCommands::dispatch`) is comparable/equivalent to `connection.sync().select()` call.

**Comment by oldium** [comment]
@christophstrobl I do not think the fix is correct and the change to the test proves it. The `SELECT` Redis command is executed twice, first time in `RedisCommands.select()` call and second time in the `BaseRedisAsyncCommands.dispatch(SELECT)` call. Please see my former comments.

**Comment by christophstrobl** [comment]
thanks for the heads up - true - working on it.

**Comment by mp911de** [comment]
You're right, we're setting now the database index twice. We had initially a different understanding. By removing the database index customization check and db selection in `doGetAsyncDedicatedConnection(…)` we can address the issue.
