### ISSUE TITLE
When a service has a class that inherits KeyspaceEventMessageListener and the Redis is deployed in a cluster, the local keyevent event is overwritten.

### ISSUE THREAD

**Issue by 1294125139** [spring-projects/spring-data-redis#2987]
Redis mode: cluster mode
Component and version: spring-data-redis-3.1.11

If the value of keyspaceNotificationsConfigParameter is not set, the value is EA by default.
Go to the method 79-94, where the 85th line of code
Properties config = connection.getConfig("notify-keyspace-events");The data is obtained by cluster. Multiple Redis connections can be obtained.
![image](https://github.com/user-attachments/assets/e22e63b6-0efd-43d8-b68e-68f3a6ec8ff4)

In line 87, you can use the config.getProperty("notify-keyspace-events") Redis single-node system to obtain the value. In cluster mode, you can obtain the value. In this case, the system executes line 88 and overwrites AE.
![image](https://github.com/user-attachments/assets/29446d94-9777-4776-b7ef-b74ac30c8bcb)

**Comment by mp911de** [comment]
`keyspaceNotificationParameter` is in place to get started locally with the least amount of configuration. It is not intended for configuration use. Please configure your Redis servers externally as much as possible.
