### ISSUE TITLE
Add builder customizer for `DefaultJedisClientConfig.Builder`

### ISSUE THREAD

**Issue by bshain-vtinfo** [spring-projects/spring-data-redis#3007]
I would like to request the addition of a means to set / configure the `JedisClientConfig.clientSetInfoConfig` property.

As of right now, there is not a clear path to set `clientSetInfoConfig` on the `JedisClientConfig` instance within the `JedisConnectionFactory`. This property is already present on currently released Jedis artifacts [Jedis v5.1.5 Example](https://github.com/redis/jedis/blob/v5.1.5/src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java#L46).

The use case for this request is that in some instances, it would be useful to set this property to disabled, (`ClientSetInfoConfig.DISABLED`) instead of the `ClientSetInfoConfig.DEFAULT` value.

**Comment by mp911de** [comment]
Looking at the configuration, we're creating `JedisClientConfig` in several places so it would be best to introduce a customizer for `DefaultJedisClientConfig.Builder` that allows you to control additional properties on the client config.

**Comment by bshain-vtinfo** [comment]
Thanks! 
Agree your suggested solution sounds like a better fit for this scenario & would help with future-proofing.

This seems like it could also potentially address [issue 2972](https://github.com/spring-projects/spring-data-redis/issues/2972) as well. (Or at least as a temporary measure until new config options are explicitly added)
