### ISSUE TITLE
Inconsistent Redis Scripting API

### ISSUE THREAD

**Issue by ghoshbishakh** [spring-projects/spring-data-redis#3010]
The following example does not work:

https://github.com/spring-projects/spring-data-redis/blob/main/src/main/antora/modules/ROOT/pages/redis/scripting.adoc?plain=1#L55

Correct code will be:

```
public class Example {

  @Autowired
  ReactiveRedisOperations<String, String> redisOperations;

  @Autowired
  RedisScript<Boolean> script;

  public Flux<Boolean> checkAndSet(String expectedValue, String newValue) {
    return redisOperations.execute(script, singletonList("key"), expectedValue, newValue);
  }
}
```

**Comment by mp911de** [comment]
Thanks for bringing this to our attention. We've updated documentation for 3.2 and 3.3 development lines. For 3.4, we introduced an overload accepting varargs in the reactive flow allowing a simpler invocation scheme.
