### ISSUE TITLE
When using IPv6 with a Redis cluster, executing the keys method will be unable to retrieve the node

### ISSUE THREAD

**Issue by silentmoooon** [spring-projects/spring-data-redis#3015]
![image](https://github.com/user-attachments/assets/03f28877-0d50-4243-b570-662abf0de639)
The clusterNodes returned by Jedis uses ip:port as the key, but the format of node.asString() is [ip]:port.

**Comment by mp911de** [comment]
That's fixed now. Please use the latest snapshots to verify whether the fix works for you.
