### ISSUE TITLE
Conflict on Garnet(Replacement of Redis, Implemented by MS, to resolve licensing issue of recent Redis)

### ISSUE THREAD

**Issue by yuseok-kim-edushare** [spring-projects/spring-data-redis#3052]
### Describe the bug

When I use [Garnet](https://github.com/microsoft/garnet) to replace Redis
My app written in Java with Spring Boot 3.3 and Spring Data Redis

I tried to test on container side and
Redis CLI works well in PING command
also Application's Execution of Ping works well

but Spring Application Try to connect Garnet, Fail to connect

and I checked logs, and finally found, when using Hello, fault on 

### Steps to reproduce the bug

1. create app with some Spring boot app with using Spring Data Redis, will trying to connect garnet
2. look fail message from spring boot's failure to application run

### Expected behavior

working well

### Screenshots

Applicaiont Failure message
![image](https://github.com/user-attachments/assets/1725344f-e6cc-456e-9290-65bbb8fe9fe9)

Garnet's Message When Try to RESP v3 Client (Use Hello)
![Image](https://github.com/user-attachments/assets/17359761-3353-47c9-9cd6-3bf7b9a421fe)

Garnet's Message When Try to RESP v2 Client (Just only Use PING)
![Image](https://github.com/user-attachments/assets/164e5c39-b620-4685-a2d3-ad098f735eb0)

### Release version

Spring Boot & Data 3.3.5 // Garnet v1.0.39

### OS version
**Problem first find in**
Ubuntu 24.04 LTS Host
running on docker compose (garnet latest, eclipse-temurin:21-jre

**test also perfomed on**
Windows 10 22H2 latest
.NET 8 latest
Eclipse-Temurin 21 JDK latest

---
### Additional context

I asked first to Microsoft/Garnet but, then I found Garnet's log is clear
https://github.com/microsoft/garnet/issues/811
(Also you can Spring Log in here) https://github.com/Prompt-oven/auth-service/issues/16

**Comment by mp911de** [comment]
This is actually an issue of the Garnet server that is sending the connection Id as String and not as number. Unfortunately, the Lettuce client doesn't propagate the failure and so you see only a timeout. I filed a PR at https://github.com/redis/lettuce/pull/3058 to propagate the failure. On the Garnet side, it would be great if the HELLO response would stick to how Redis replies.

**Comment by yuseok-kim-edushare** [comment]
@mp911de Thanks!
