### ISSUE TITLE
ZonedDateTime serialize with @JsonFormat pattern never uses it, and then while deserialization can't parse it

### ISSUE THREAD

**Issue by verve111** [spring-projects/spring-data-redis#3057]
Hi, I'm using JavaTimeModule() in spring-data-redis implementation of my app and there's a strange thing:
When JsonFormat-annotation with pattern is added:
```
data class CacheValue(
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    val zonedDateTime: ZonedDateTime
)
```
Current object is always stored in Redis as an ISO_ZONED_DATE_TIME, e.g. "2024-11-15T18:27:06.921054+01:00[Europe/Germany]", the pattern is not taken into an account.
But then when deserialization comes, it tries to deserialize the ISO_ZONED_DATE_TIME formatted object from Redis with "yyyy-MM-dd'T'HH:mm:ss.SSSZ" pattern and fails.
Could you please give a hint, what is wrong here. I guess jackson serializer supposed to use pattern to encode the date, thank you!

**Comment by mp911de** [comment]
Which Jackson serializer do you use? It would be the easiest if you could provide a reproducer, it can be as simple as a self-contained JUnit test file that contains your entire setup of the serializer, the reproducer code and your data model.

**Comment by verve111** [comment]
Sorry, it seems the issue completely relates to fasterxml jackson lib, I'm moving the question there: https://github.com/FasterXML/jackson-modules-java8/issues/333
Regards
