### ISSUE TITLE
Problem of code in README

### ISSUE THREAD

**Issue by yeoleobun** [spring-projects/spring-data-redis#3060]
Field name of `RedisTemplate` is `template` at
https://github.com/spring-projects/spring-data-redis/blob/49f3f4e0d3ae4aa29a4cb4e45f535dcf6259a8a7/README.adoc?plain=1#L39

but the `addLink` method use it as `redisTemplate`
https://github.com/spring-projects/spring-data-redis/blob/49f3f4e0d3ae4aa29a4cb4e45f535dcf6259a8a7/README.adoc?plain=1#L49
I think it's a mistake.

**Comment by mp911de** [comment]
Good catch, that's fixed now.
