### ISSUE TITLE
RedisMessageListenerContainer has race conditions [DATAREDIS-389]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#964]
**[Adrian Riley](https://jira.spring.io/secure/ViewProfile.jspa?name=adrianriley)** opened **[DATAREDIS-389](https://jira.spring.io/browse/DATAREDIS-389?redirect=false)** and commented

The lazyListen() method sets the listening flag to true, then starts a Thread to run the SubscriptionTask. Calls to addMessageListener() then use the same JedisConnection to subscribe to further topics. But there is no guard on the SubscriptionTask startup process, a call to addMessageListener() may arrive before that process is complete, so the subscription may be lost entirely or both threads may write to the same output stream at the same time, so Redis is sent a corrupted command.

There is a similar issue when the task is shutdown after all topics have been unsubscribed. It is possible for a new subscribe command to be sent on the connection before it is returned to the pool. If that connection is then used for non-subscription commands, an error occurs.

Attached is a TestNG test which shows the problem, sometimes. You can modify the two constants to control the multi-threaded execution, but for me it usually fails every few times I run it. You may also hit the issue https://github.com/xetorthio/jedis/issues/933

---

**Affects:** 1.5 GA (Fowler)

**Reference URL:** http://stackoverflow.com/questions/29353615/spring-data-redis-redismessagelistenercontainer-seems-to-have-race-conditions

**Attachments:**
- [SpringDataRedisPubSubIT.java](https://jira.spring.io/secure/attachment/22722/SpringDataRedisPubSubIT.java) (_6.50 kB_)

4 votes, 6 watchers

**Comment by jebeaudet** [comment]
I just hit that bug using Spring Session which use the same container for a pattern + channel topic. Some fonky race condition leads to silently unsubscribed pattern topic and corrupted streams on shutdown.

I saw that it was rewritten on the 2.7 branch but are you open on fixing some race conditions on the 2.5 and 2.6 branch?

Thanks

**Comment by christophstrobl** [comment]
@jebeaudet we are.Please open a new issue (or a PR if you have the time).
